### ISSUE TITLE
Option enableTime  change is not updating component

### ISSUE THREAD

**Issue by stonko1994** [ankurk91/vue-flatpickr-component#1]
I would like to implement something like a `allDay` checkbox. 
Set `enableTime` to false dynamically.

But when changing the options the component is not redrawing itself as mentioned.
The functionality is working fine! (Dialog closes when selecting a new date, but does not hide the Time select bar)

[Quick jsFiddle](https://jsfiddle.net/vLvfy11f/2/)

**Comment by ankurk91** [comment]
Hi, @stonko1994 

Seems like this is a bug within flatPickr ``redraw()`` method.
See my plain js [jsFiddle](https://jsfiddle.net/ankurk91/hd0wo4xv/4/), you will found it is not working there are well.

I would suggest to report the issue on flatpickr [repo](https://github.com/chmln/flatpickr/issues) instead.
