### ISSUE TITLE
Changing the `clicksOpen` config attribute does not change the behavior.

### ISSUE THREAD

**Issue by yakky** [ankurk91/vue-flatpickr-component#101]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.1
* Vue.js version : 2.5.2
* Browser name and version : Any
* This package version : 7.0.4

**Current behavior**

Changing the `clicksOpen` config attribute does not change the behavior.

**Expected behavior**

Date picker behavior changes when setting `clicksOpen` configuration.

**Minimal reproduction of the problem with instructions**

A simplified version of the component is something like:
```
<template>
  <vue-flatpickr-component
    class="vuestic-date-picker"
    :config="config"
  />
</template>

<script>
  import VueFlatpickrComponent from 'vue-flatpickr-component'

  export default {
    name: 'modified-date-picker',
    data: {
      return {
        config: {clicksOpen: false}
      }
    }
    components: {
      VueFlatpickrComponent,
    },
    method: {
      updateConfig: function () {
        return {clicksOpen: this.someMethod()};
      },
    },
  }
</script>
```

It works by implementing this workaround https://github.com/ankurk91/vue-flatpickr-component/issues/77#issuecomment-384274378 

Am I missing something?

**Comment by ankurk91** [comment]
Its is not good to destroy the instance on each config change.

Flatpickr itself does not respect the change in this property.
Vue component passes all changes to flatpickr now it is upto flatpickr to apply them

**Comment by ankurk91** [comment]
Someone has send a PR to fix this

https://github.com/flatpickr/flatpickr/pull/1129

**Comment by yakky** [comment]
Thanks @ankurk91 for your prompt reply, the link and the suggestion on the example (I am quite new to Vue your suggestion is really :100: )
I think we can close this here, maybe, and I will followup on the upstream issue
