### ISSUE TITLE
Add blur event for validation libraries

### ISSUE THREAD

**Issue by pareeohnos** [ankurk91/vue-flatpickr-component#102]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

A PR (#22) was opened a while back adding the `blur` event, and you said you couldn't see a use case and that it would mean other events would need adding. In our application, there is a use case for this, and that is when using the `vuelidate` where validations can be triggered when a field is blurred. Currently I cannot apply this with vue-flatpickr due to this event not being registered/emit.

I don't disagree with your statement that it may make sense then to allow other events to be added such as keyboard events, however since Vue 2.4 it is possible to simply bind all listeners provided to a component via the `$listeners` property. 

This would allow the developer to decide which listener they wish to bind rather than vue-flatpickr having to pick and choose. I don't know the all of the code, but at a quick glance it would as simple as changing the template of the component to

```html
<input type="text" data-input v-on="inputListeners">
```

and adding a computed property

```javascript
inputListeners() {
  let vm = this;
  return Object.assign({},
    vm.$listeners,
    {
      input: vm.onInput,
    }
  );
}
```

With this change, I would be able to do something like

```html
<flat-pickr
  v-model="model"
  :config="config"
  @blur="onBlur"
  @keydown="onKeydown">
```

**Comment by ankurk91** [comment]
I know about the `$listeners` method. But i found it buggy.
Today itself i removed this approach from one of my package, [see](https://github.com/ankurk91/vue-cleave-component/commit/cd1152b017ca6c12713a95628d909791a427a946)

I am happy to add `blur` event.
But you can still trigger vee-validate validations like this.
```js
import VeeValidate from 'vee-validate';
Vue.use(VeeValidate,{
     events:'input|blur|on-close'
});
```
The `on-close` event is emitted by vue-flatpickr. Above config is global but you can also limit the config to component basis.

**Comment by pareeohnos** [comment]
Ah fair enough, haven't run into any issues with it as of yet but equally haven't made a lot of use of it.
I realise that's possible on `VeeValidate`, but not with `vuelidate`. Vuelidate doesn't do any binding to inputs automatically at all, and leaves that part up to the developer.

The on-close event would work to a point, but we also allow users to manually enter the dates rather than just using the date picker, so in this scenario the `on-close` event would have fired before the new date had actually been entered so the blur even would be crucial here really.

**Comment by ankurk91** [comment]
Ah, i did not notice that you have written `vuelidate`.
I will ass blur event soon, may be in few minutes.

**Comment by pareeohnos** [comment]
ah that would be amazing, thank you so much :)

**Comment by pareeohnos** [comment]
awesome thank you!!

**Comment by pareeohnos** [comment]
Just tried this out and it doesn't seem to work. I think what's happening is the input that the blur event is bound to is changed by flatpickr to the hidden input and thus never actually gets a blur event.

**Comment by ankurk91** [comment]
Oh no, the hidden input is nightmare.
I will look into, there is a workaround

**Comment by ankurk91** [comment]
Please update to v7.0.6 and let me know it it works for you.
