### ISSUE TITLE
Black background color for some mobile devices

### ISSUE THREAD

**Issue by DeepakAryal** [ankurk91/vue-flatpickr-component#103]
i tested this for more than 10 mobile devices. but getting black background color some mobile devices like samsung j5 and lg. is this issue with this package or with mobile device?
![vue-date](https://user-images.githubusercontent.com/17777925/44831121-d2408f00-ac44-11e8-8b84-3a22a432a1d8.png)

**Comment by ankurk91** [comment]
@DeepakAryal 
This is native OS date time picker, You can disable this behaviour 
```js
{
    disableMobile: "true"
}
```
Read more here
https://flatpickr.js.org/mobile-support/
