### ISSUE TITLE
Class binding only happening on hidden input

### ISSUE THREAD

**Issue by DM2489** [ankurk91/vue-flatpickr-component#104]
**I'm submitting a bug report** 

**Tell about your platform**
* flatPickr version : 4.5.1
* Vue.js version : 2.5.17
* Browser name and version : Chrome 68
* This package version : 7.0.6

**Current behavior**
When trying to dynamically change the class of the flatpickr element, it is only applied to the hidden element, and not the element being displayed. In this case, I am using vee-validate to detect errors. When errors are found, I want to change the input background from green to red. This class binding happens, but only on the hidden element, and not the actual element being displayed.

![gif1](https://user-images.githubusercontent.com/40390596/44847649-11261300-ac4c-11e8-8994-443100e9b8d8.gif)

**Expected behavior**
Changes to class should be applied to both the hidden and the visible input element.

**Minimal reproduction of the problem with instructions**
https://jsfiddle.net/63kzdwLx/2409/

**Comment by ankurk91** [comment]
This is a known issues.
Any workaround or suggestion are welcome.

**Comment by DM2489** [comment]
I decided to abandon the 'altFormat' propery and style the standard element instead. THis seems to work as expected.

https://jsfiddle.net/63kzdwLx/2429/

**Comment by paulm17** [comment]
Just wanted to chime in and say this is solvable just by thinking out of the box.

If you use vee validation, then you can watch the errors array using: https://stackoverflow.com/questions/51944897/how-to-watch-computed-vee-validate-errors

All you need to do, is determine whether the field is present and then set an error class to the input.  If it's not, then remove the error class from the input.

**Comment by Tarabass** [comment]
I solved this by adding a class name in the mounted lifehook of the component where I use flatpickr.

```html
<template>
    <flat-pickr ref="flatPickerWrapper" v-model="date"></flat-pickr>
</template>

<script>
import flatPickr from "vue-flatpickr-component";
import "flatpickr/dist/flatpickr.css";

export default {
    name: 'myComponent',
    data() {
        return {
            date: null
        };
    },
    components: {
        flatPickr
    },
    mounted() {
        this.$refs.flatPickerWrapper.getElem().className = "my-own-css-class";
    }
};
</script>

<style>
.my-own-css-class {
    border: 1px solid red;
}
</style>
```

I would like to bind a class as well like in the "normal" way.

**Comment by robertguss** [comment]
@Tarabass I just tried this and it seems to still attach to the hidden element
