### ISSUE TITLE
Question: Why is jQuery Included in this project?

### ISSUE THREAD

**Issue by Codermar** [ankurk91/vue-flatpickr-component#106]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ x] Other, please describe
```

**Comment by ankurk91** [comment]
It is a Dev dependency, it will not be installed by package consumers.

It is installed to satisfy bootstrap js.
It is being used in examples.
