### ISSUE TITLE
Selected date on minDate config change should be set on minDate value

### ISSUE THREAD

**Issue by thepill** [ankurk91/vue-flatpickr-component#107]
```
[x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* jsfiddle

**Current behavior**
When updating the config with a new `minDate`, the selected date gets erased.

**Expected behavior**
When updating the config with a new `minDate`, the selected date should be updated to the new `minDate` value

**Minimal reproduction of the problem with instructions**
https://jsfiddle.net/qeLwag08/4/

Click on `update min-date`

**Comment by ankurk91** [comment]
i was able to reproduce the issue with plain js version.
see
https://jsfiddle.net/9qze7yj5/

You should report this to parent library instead.

**Comment by thepill** [comment]
thanks - i did: https://github.com/flatpickr/flatpickr/issues/1500

lets see what happens :)

**Comment by thepill** [comment]
@ankurk91 Colud you take a look at https://github.com/flatpickr/flatpickr/issues/1500#issuecomment-420193595

Is it reasonable to add like a `update-default-date-on-change` prop to your component so it will than set the new default value?

**Comment by ankurk91** [comment]
Doing this already
https://github.com/ankurk91/vue-flatpickr-component/blob/41cbb66bb21725adc57bbd37fa8d4b3bf75b3c5d/src/component.vue#L145

It means you need to update v-model rather then `defaultDate`

**Comment by ankurk91** [comment]
@thepill 
I am working on this issue. I think i am very close.

**Comment by ankurk91** [comment]
@thepill 
Please update to v8.0.0 and let me know

please see update fiddle -
https://jsfiddle.net/qeLwag08/14/

**Comment by thepill** [comment]
@ankurk91 seems to work 👍
