### ISSUE TITLE
showMonths bug when programatically updating MinDate

### ISSUE THREAD

**Issue by DM2489** [ankurk91/vue-flatpickr-component#108]
**I'm submitting a ...**  (check one with "x")
```
[X] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.2
* Vue.js version : 2.5.17
* Browser name and version : Chrome 68
* This package version : 8.0.0

**Current behavior**
I'm trying to use two flatpickr elements to implement a range picker, as described in https://github.com/ankurk91/vue-flatpickr-component/issues/20.

However I've discovered a bug when using showMonths.

When programatically setting the minDate and when showMonths is set (to 3 in this example), the month/year display is offset by 3 months incorrectly. The dates within the datepicker themselves are correct, however.

Every time the minDate is updated, it is further offset by the showMonths value.

This should show the issue:
![gif2](https://user-images.githubusercontent.com/40390596/45769089-71e6b100-bc36-11e8-8e49-4e51cf1c15f7.gif)

**Expected behavior**
The current Month / Year should display the correct month/year values.

Demo Link:
https://jsfiddle.net/63kzdwLx/2751/

PS- Working fiddle
https://jsfiddle.net/63kzdwLx/2760/

**Comment by ankurk91** [comment]
I was able re-produce the issue.
The culprit is `showMonths` property, it happens when `showMonths` is set to 1.
I will look into it, will try to find a workaround.

**Comment by DM2489** [comment]
I was literally just about to say that setting showMonths to 1 also increments - just by 1 at a time.

What's weird is that the actual dates within the datepicker are correct. It's literally just the months and years that are wrong.

**Comment by ankurk91** [comment]
Try this fiddle, this is plain js

https://jsfiddle.net/wxLb6m4n/720/

Follow these steps -
1 - Open up end picker, notice the starting month
2 - click outside to close this picker
3 - click on "Update showMonths config" button
4 - open end picker again and notice starting month

Seems like a bug in flatpickr itself.

**Comment by DM2489** [comment]
Looks like you may be correct. I'll open up a ticket in flatpickr directly and report back if it is their end.

**Comment by DM2489** [comment]
Possibly fixed by this PR in flatpickr:

https://github.com/flatpickr/flatpickr/pull/1413/commits/83cd33f60cb5c0bb4a730eebefd6594b49dc45b7
