### ISSUE TITLE
Have to pick date twice to make it available in my @on-change function

### ISSUE THREAD

**Issue by Brotzka** [ankurk91/vue-flatpickr-component#112]
I'm using the latest releases of vuejs and flatpickr.

The problem is, that the selected date is only available/set after it was selected for the second time. Here is my code:

```html
// Component
<flat-pickr
    v-model="fields.birthday"
    :config="birthdayConfig"
    class="form-control"
    placeholder="Geburtsdatum"
    name="consumer[birthday]"
    @on-change="validateBirthday">
</flat-pickr>

// my Vue-component
<script>
    import flatPickr from 'vue-flatpickr-component';
    import 'flatpickr/dist/flatpickr.css';
    import {German} from "flatpickr/dist/l10n/de.js"

    export default {
        name: "NewCustomerRegistration",
        props: ['csrfToken', 'vehicleId', 'formAction'],
        data() {
            return {
                test: 1,
                addressLines: [],
                fields: {
                    birthday: "02.10.2018",
                    // ...
                },
                birthdayConfig: {
                    wrap: true,
                    utc: true,
                    dateFormat: 'd.m.Y',
                    time_24hr: true,
                    locale: German
                },
                validation: {
                    birthday: false,
                    // ...
                }
            }
        },
        methods: {
            validateBirthday() {
                console.log(selectedDate);
                // do some validation..
                this.enableButton();
            },
            enableButton() {
                // ...
            }
        },
        components: {
            flatPickr
        }
    }
</script>
```

Steps (assuming the predefined date is 22.09.2018):
- select new date (02.10.2018) => the new date is set in data but referencing it in my function ``validateBirthday`` returns the old one.
- select new date (02.10.2018) again => date is stil set in data and referencing it in my function returns the selected date

So everytime I select a data, I have to select it twice to make it available.

Any ideas why?

**Comment by ankurk91** [comment]
Can you share complete example
```
console.log(selectedDate);
```
This variable seems undefined.
Fork this fiddle
https://jsfiddle.net/ankurk91/63kzdwLx/

**Comment by Brotzka** [comment]
Here is my fiddle: [JSFiddle](https://jsfiddle.net/62t7hpL8/)

It has the same behaviour as described above. The console.log-output shows the old value although the new value is set to data.fields.birthday.

**Comment by ankurk91** [comment]
Checkout this fiddle
https://jsfiddle.net/62t7hpL8/7/

The `on-change` event gets called before `input` event. `input` event is responsible for updating the v-model property.
You are trying to access v-model in on-change callback, but v-model yet to be updated via `input` event.

So there are various ways to detect changes in v-model.
* Watch for v-model data property, `this.$watch('form.date',this.callbackMethod)`
* Add a callback to `@input="yourCallback"`
* Add a calback to `"@on-chnage="callbackMethod"` and check for the arguments that are passed to callback, see [docs](https://flatpickr.js.org/events/) about events
