### ISSUE TITLE
Setting `v-model` value in `on-change` event does not change the date in the input 

### ISSUE THREAD

**Issue by kanteankit** [ankurk91/vue-flatpickr-component#115]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.5.16
* Browser name and version : Chrome 68.0.3440.106
* This package version : 8.0.0

**Current behavior**
Here is a jsfiddle: https://jsfiddle.net/ux18nLm6/
1) Click on the input field to open the datepicker
2) Select any date
3) Again click on the input field
4) This time, press backspace to clear the form
5) The `on-change` handler gets called and it sets the new `date`, but, the input field value does not show the new date

**Expected behavior**
When the statement `this.date = "2017-10-01"` gets executed in the `on-change` handler, it should set the value in the input form also

**Comment by kanteankit** [comment]
The aim of doing this is to prevent the user from clearing the input field using backspace. The only solution I could come up was to check the `dateStr` in the `on-change` event handler. If it is an empty string, I want to reset the date to another value. But, setting the date is not changing the input value.

**Comment by ankurk91** [comment]
Read
https://github.com/ankurk91/vue-flatpickr-component/issues/112#issuecomment-426504538
