### ISSUE TITLE
Add data-toggle support

### ISSUE THREAD

**Issue by pixelizedPeanut** [ankurk91/vue-flatpickr-component#116]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version :  -
* Vue.js version : 2.5.17
* Browser name and version : Either
* This package version : 4.5.2

**Current behavior**
I am looking for a way to implement the data toggle button as shown in the final example https://flatpickr.js.org/examples/

```
<div class=flatpickr>
    <input type="text" placeholder="Select Date.." data-input> <!-- input is mandatory -->

    <a class="input-button" title="toggle" data-toggle>
        <i class="icon-calendar"></i>
    </a>

    <a class="input-button" title="clear" data-clear>
        <i class="icon-close"></i>
    </a>
</div>
```

Can this feature be enabled?

**Comment by ankurk91** [comment]
This example has been documented in readme.md as well as `examples` folder.
