### ISSUE TITLE
How to set a global configuration?

### ISSUE THREAD

**Issue by 2112chris** [ankurk91/vue-flatpickr-component#118]
Is there a way to set the configuration globally instead of having to add it to each component via the config prop?

```js
import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/themes/airbnb.css';
import {Locale} from 'flatpickr/dist/l10n/locale.js';

// flatPickr.set('config', {
//     altFormat: 'j M. Y',
//     altInput: true,
//     dateFormat: 'Y-m-d',
//     locale: Locale,
// });

Vue.use(flatPickr);
```

**Comment by ankurk91** [comment]
Please look into examples folder.
You can also search through existing issues

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-flatpickr-component/blob/53ecf6bb4f36821349a89115c35214533a2eed4a/examples/App.vue#L196-L199

**Comment by weblikero** [comment]
I'm using Laravel&Vue.js and what I want to acheive is to have 1 global config for datePicker and one global config for timePicker,
in app.js I have this declared:
`/*   Begin of date time   */
import VueFlatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';

//how to set here a datePicker config globally and then use it components?

//how to set here a timePicker config globally and then use it components?
 

Vue.use(VueFlatPickr);

/*End of date time picker */`

I have searched other issues but not concludent here.
Thank you in advance.
