### ISSUE TITLE
Placing a screenshot can make the project more attractive.

### ISSUE THREAD

**Issue by Kuchiriel** [ankurk91/vue-flatpickr-component#12]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : x.x.x
* Vue.js version : 2.x.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Agree,
But this package is just a wrapper around [flatpickr](https://github.com/chmln/flatpickr) and one should go and see what this datepicker can do and what are options available.

**Comment by Kuchiriel** [comment]
@ankurk91 True, even so, I think this would make the project more attractive. But you are right, I'll be closing the issue.
