### ISSUE TITLE
"includedEvents is not Defined"

### ISSUE THREAD

**Issue by mitevpi** [ankurk91/vue-flatpickr-component#122]
I'm having a strange issue when trying to place a date/time picker component.

This is the error:
![image](https://user-images.githubusercontent.com/25568566/48490217-cee78900-e7d9-11e8-9d79-45043a1ecf74.png)

This is my .vue file imports:
![image](https://user-images.githubusercontent.com/25568566/48490236-db6be180-e7d9-11e8-9bff-1e164e572981.png)

And this is my imported .css in the same .vue file:
![image](https://user-images.githubusercontent.com/25568566/48490269-e9216700-e7d9-11e8-9b12-bf22226dd659.png)

I'm pretty new to JS/vue in general, but generally tried to replicate the examples on the repo. Not sure what I'm doing wrong here.

**Comment by ankurk91** [comment]
Unfortunately i can not help in this way.
You need to fill out the ISSUE_TEMPLATE.
Also you need tp provide a minimal re-production.

Have you tried the examples on readme?

**Comment by mitevpi** [comment]
Thanks.
