### ISSUE TITLE
how to set the picker's width or size？

### ISSUE THREAD

**Issue by mexhfl** [ankurk91/vue-flatpickr-component#125]
how to set the picker's width or size？

**Comment by ankurk91** [comment]
Try to find such option at

https://flatpickr.js.org

**Comment by dyakant** [comment]
There is no such option in the Flatpickr.
Currently I'm using the following solution, but it's permanent:
```
<style lang="less">
    .input-group /deep/ input {
        width: 190px;
    }
...
```
I want to change the "width" dynamically when I added my component  based on Flatpickr.
