### ISSUE TITLE
vee-validate does not trigger 'required' error since v8.1.0 of this component

### ISSUE THREAD

**Issue by someniatko** [ankurk91/vue-flatpickr-component#126]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.2
* Vue.js version : 2.5.21
* Browser name and version : Chrome 71.0.3578.98
* This package version : 8.1.0
* vee-validate version: 2.1.5

**Current behavior**
main.js:
```js
// ...
Vue.use(VeeValidate, { validity: true });
// ...
```

MyComponent.vue
```html
<template>
  <form>
    <button type="button" @click="$validator.validateAll()">check</button>
    <flatpickr
        data-vv-name="date"
        required
        v-validate="'required'"
        v-model="date"
    />
    <input
        data-vv-name="input"
        required
        v-validate="'required'"
        v-model="input"
    >
    <span v-if="errors.has('date')">date has error</span>
    <span v-if="errors.has('input')">input has error</span>
  </form>
</template>

// ...
```

I click the "check" button, and...
v8.0.0: both `<span>`s show up
v8.1.0: only `<span>` "input has error" shows up, because for 'date' vee-validate does not trigger an error.

**Expected behavior**
v8.1.0: both `<span>`s show up

**Minimal reproduction of the problem with instructions**
see above

**Comment by ankurk91** [comment]
Thanks for reporting, this has been fixed in 8.1.1

You can check this fiddle 
https://jsfiddle.net/rkj30dng/
