### ISSUE TITLE
[support] How add icon for input?

### ISSUE THREAD

**Issue by LusenkoSasha** [ankurk91/vue-flatpickr-component#13]
How to add an icon for input?

![image](https://user-images.githubusercontent.com/27783985/28669096-6b15395a-72db-11e7-9fae-18144ec94d68.png)
![image](https://user-images.githubusercontent.com/27783985/28669105-774c102c-72db-11e7-8324-6cb258f074e1.png)
![image](https://user-images.githubusercontent.com/27783985/28669124-91bd2e32-72db-11e7-8a4f-274f41e92450.png)

**Comment by ankurk91** [comment]
I thought examples should be sufficient,
https://github.com/ankurk91/vue-flatpickr-component/blob/master/examples/App.vue#L51-L71

**Comment by lawsonjt** [comment]
Those examples show how to append elements after the dropdown, but not inside.  Has anyone figured a solution for OP's question?  It appears you can only display dates in the input, except for the Placeholder.

**Comment by ankurk91** [comment]
This is more like a css related question.

You can style your input field as you want.
