### ISSUE TITLE
Input Group toggle issue with 2 Flat picker

### ISSUE THREAD

**Issue by theromie** [ankurk91/vue-flatpickr-component#130]
https://jsfiddle.net/roy1/rzkx1ndf/

When I first click on `If` button it opens flatpicker after clicking on change button `else` button shows up, but when I click on `else` button flatpicker is not showing up

**Comment by ankurk91** [comment]
I really don't know what you are trying achieve.

But the toggle works fine here
https://jsfiddle.net/qujc02b8/12/

Notice that `form-group` div is not not visible by default. (v-if="false")
Click on "TOGGLE" button, the date picker will show up.
Now click on "OPEN" button, you will see the date-picker widget.
Now you can show/hide the form group and it show open as usual.

**Comment by ankurk91** [comment]
I think this may help you.
Read about `key`

**Comment by theromie** [comment]
I have two flatpicker components. 1 in v-if and another one in v-else. V-if flatpicker component working fine but other one ie v-else is not opening

**Comment by ankurk91** [comment]
Try to add key to both components.
See what happens

**Comment by theromie** [comment]
Key prop worked. Thanks :)
