### ISSUE TITLE
Error on setting value

### ISSUE THREAD

**Issue by aquadk** [ankurk91/vue-flatpickr-component#132]
**I'm submitting a ...**  (check one with "x")
```
[x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**
Get this error in console:
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'value' of null"
stacktrace:
```
warn | @ | vue.runtime.esm.js:619
-- | -- | --
  | logError | @ | vue.runtime.esm.js:1874
  | globalHandleError | @ | vue.runtime.esm.js:1869
  | handleError | @ | vue.runtime.esm.js:1835
  | (anonymous) | @ | vue.runtime.esm.js:1972
  | flushCallbacks | @ | vue.runtime.esm.js:1896
  | Promise.then (async) |   |  
  | timerFunc | @ | vue.runtime.esm.js:1923
  | nextTick | @ | vue.runtime.esm.js:1980
  | Vue.$nextTick | @ | vue.runtime.esm.js:3490
  | onInput | @ | vue-flatpickr.min.js:141
  | invokeWithErrorHandling | @ | vue.runtime.esm.js:1847
  | invoker | @ | vue.runtime.esm.js:2169
  | original._wrapper | @ | vue.runtime.esm.js:6855
  | triggerEvent | @ | flatpickr.js:1980
  | setDate | @ | flatpickr.js:1860
  | value | @ | vue-flatpickr.min.js:167
```
**Expected behavior**
    /**
     * Watch for value changed by date-picker itself and notify parent component
     *
     * @param event
     */
    onInput(event) {
      // Lets wait for DOM to be updated
      this.$nextTick(() => {
        event.target && this.$emit('input', event.target.value);
      });
    },

Can be solved by checking for target is assigned

**Minimal reproduction of the problem with instructions**
Error when setting value on component.

**Comment by ankurk91** [comment]
Could not reproduce the error described.

https://jsfiddle.net/nzypq8gw/

**Comment by Silentscripter** [comment]
The bug seems to happen when the component is used in a vue app that is wrapped inside a webcomponent. A pull request to fix the issue has been provided and linked.
