### ISSUE TITLE
Set locale not working

### ISSUE THREAD

**Issue by Naaach** [ankurk91/vue-flatpickr-component#134]
**I'm submitting a ...**  (check one with "x")
```
[ X ] Bug report 
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.7
* Vue.js version : 2.0.5
* Browser name and version : Chrome 72.0.3626
* This package version : x.x.x

**Current behavior**

Importing and setting the locale not working.
I'm trying to set the Spanih locale but it dosen't work

**Expected behavior**
 set the flatpickr 
```javascript
import flatpickr from 'flatpickr'
const Spanish = require('flatpickr/dist/l10n/es');
flatpickr.localize(Spanish);

import vueFlatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
```

add the config to the elements (tied two different but anyone of the work form me)

```javascript
customJobHous: {
        start: {
          time: null,
          dateFormat: 'H:i',
          wrap: true,
          enableTime: true,
          enableSeconds: false,
          noCalendar: true,
          time_24hr: true,
          locale: Spanish,
          onClose: (selectedDates, dateStr) => {
            this.changeTime('start', dateStr);
          }
        },
        end: {
          time: null,
          dateFormat: 'H:i',
          wrap: true,
          enableTime: true,
          enableSeconds: false,
          noCalendar: true,
          time_24hr: true,
          locale: Spanish,
          onClose: (selectedDates, dateStr) => {
            this.changeTime('end', dateStr);
            this.validJobTemplateHours();
          }
        }
      }
```
```vue
<vue-flat-pickr
	class="form-control jobTemplateHour flat-date-picker"
	:placeholder="langStartDate"
	:config="customJobDate.start"
	v-model="form.dateStart"
	@on-change="onStartChange"
>
</vue-flat-pickr>
```

**Comment by ankurk91** [comment]
Try importing locale like this

https://github.com/ankurk91/vue-flatpickr-component/blob/eeab13f52a5c48e72b063c07b626d6be5bd07fe9/examples/App.vue#L201

**Comment by Naaach** [comment]
I tried to impor as you tell me, but also is no t working

```javascript
import { Spanish as SpanishLocale} from 'flatpickr/dist/l10n/es'

//////////////////////////////////////////////////////////////////////

customJobHous: {
        start: {
          time: null,
          dateFormat: 'H:i',
          wrap: true,
          enableTime: true,
          enableSeconds: false,
          noCalendar: true,
          time_24hr: true,
          locale: SpanishLocale,
          onClose: (selectedDates, dateStr) => {
            this.changeTime('start', dateStr);
          }
        },
        end: {
          time: null,
          dateFormat: 'H:i',
          wrap: true,
          enableTime: true,
          enableSeconds: false,
          noCalendar: true,
          time_24hr: true,
          locale: SpanishLocale,
          onClose: (selectedDates, dateStr) => {
            this.changeTime('end', dateStr);
            this.validJobTemplateHours();
          }
        }
      },
```
![test1](https://user-images.githubusercontent.com/19396332/54017746-407f8480-4187-11e9-9a11-9c3bee1c2e6f.png)
![test2](https://user-images.githubusercontent.com/19396332/54017747-41181b00-4187-11e9-91f9-15db223e7dc6.png)


----------------------------------------------------------------------------------------------

The import locale is correct but it isn't displaying on the view

**Comment by ankurk91** [comment]
Can you re produce it on
https://codesandbox.io

**Comment by ankurk91** [comment]
I have created one for you

https://codesandbox.io/s/94o3ol0rp4

**Comment by MarFelix** [comment]
Try importing locale like this

vue-flatpickr-component/examples/App.vue

Line 201 in eeab13f

   import {Hindi as HindiLocale} from 'flatpickr/dist/l10n/hi.js'; 
Read the doc on how to import locale properly.
https://flatpickr.js.org/localization/

// right  way to import 
const Russian = require("flatpickr/dist/l10n/ru.js").default.ru;

Esta es la manera correcta de hacerlo 
Gracias @ankurk91
