### ISSUE TITLE
Calendar show wrong when set minDate

### ISSUE THREAD

**Issue by laypassmail** [ankurk91/vue-flatpickr-component#136]
I have a problem when setting minDate
When I set start date = someday in next month and set minDate of the end date is that day, when I open end date calendar, It still displays the current date, I think it wrong

Sorry about my skill English, you can check it in https://jsfiddle.net/Lt08j61p/1/

**Comment by ankurk91** [comment]
It is flatpickr issue for sure.

v4.5.7 (broken)
https://jsfiddle.net/6fmes4qt/3/

v4.5.1 (working)
https://jsfiddle.net/6fmes4qt/4/

You can report it here
https://github.com/flatpickr/flatpickr/issues
