### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by someniatko** [ankurk91/vue-flatpickr-component#138]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.7
* Vue.js version : 2.6.10
* Browser name and version : Google Chrome 73.0.3683.103
* This package version : 8.1.2

**Current behavior**
```
yarn add @types/vue-flatpickr-component
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fvue-flatpickr-component: Not found".
```

**Expected behavior**
It would be nice to have typescript definitions for this library.

**Comment by ankurk91** [comment]
No plans to learn TS.

You can release a package as "@types/vue-flatpickr-component".
I will link back the package here for sure.

Thanks
