### ISSUE TITLE
VeeValidate scoped validation not working

### ISSUE THREAD

**Issue by seanhak** [ankurk91/vue-flatpickr-component#139]
**I'm submitting a ...**  (check one with "x")
```
[ X] Bug report => search github for a similar issue or PR before submitting
[] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.4
* Vue.js version : 2.6.3
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 8.1.1
* VeeValidate : 2.1.7

**Current behavior**
VeeValidate returns valid true when scoped.

Based on example from previous ticket #126, but with scopes.
https://jsfiddle.net/odwz5me0/

Do you have any ideas why this might be happening?

**Comment by ankurk91** [comment]
You need to add `data-vv-scope` to component.

https://baianat.github.io/vee-validate/examples/scopes.html

I have updated the fiddle, check
https://jsfiddle.net/b1o23pmg/
