### ISSUE TITLE
[support] Editing vue component

### ISSUE THREAD

**Issue by LusenkoSasha** [ankurk91/vue-flatpickr-component#14]
Hello. Maybe you can explain to me. How can I change the architecture of a vue? For example wrap the input in a div? Those. I can somehow edit the structure of the vue element? Because I'm modifying the vue component, but nothing happens. I know that you can not change something in node_modules, but what if I want to add something of my own to your vue architecture?

**Comment by ankurk91** [comment]
i believe you are talking about html.
What html structure do you want ? Can you paste the code here ? Thanks.

Yes, you should not change anything in node modules.

**Comment by LusenkoSasha** [comment]
@ankurk91 

<template>

  <input type="hidden"
         class=""
         :id="id"
         :class="inputClass"
         :name="name"
         :placeholder="placeholder"
         :required="required"
         v-model="mutableValue"
         data-input>

</template>

vue Builds from this code? For example, I want to add something like this that would match the design

<template>
  <div class="el-input">
  <input type="hidden"
         class=""
         :id="id"
         :class="inputClass"
         :name="name"
         :placeholder="placeholder"
         :required="required"
         v-model="mutableValue"
         data-input>
    <i class="el-input__icon el-icon-caret-top"></i>
  </div>
</template>

**Comment by ankurk91** [comment]
Then do like this in your component ->
```html

 <div class="el-input">
    <flat-pickr v-model="date"></flat-pickr>
    <i class="el-input__icon el-icon-caret-top"></i>
  </div>

```
This will render the expected html.

You no need to edit it through node_modules.
