### ISSUE TITLE
ShowTimeInput styling issues with mobile devices.

### ISSUE THREAD

**Issue by jcjabros** [ankurk91/vue-flatpickr-component#141]
Bug report

There is a issue with the `.showTimeInput` (currently tested with Iphone X).When a user selects a time and touch the body the `.flatpickr-calendar` div doesn't remove the `.open` class causing that the `.showTimeInput` no closes.

**Tell about your platform**
* flatPickr version : latest
* Vue.js version : latest
* Browser name and version : Mobile Chrome|Safari
* This package version : latest

**Current behavior**
element doesn't remove the `.open` class causing that the `.showTimeInput` no to close.

**Expected behavior**
remove the `.open` class when user touch on screen.

**Minimal reproduction of the problem with instructions**
Check my JS Fiddle to get a better idea of what I'm saying, it is important to open it from a mobile device to see the issue because on desktop works fine.
https://jsfiddle.net/mkdowtvc/

**Comment by ankurk91** [comment]
Are you sure that it is specific to this vue component.
And it is not happening with plain js version of flatpickr.

https://github.com/flatpickr/flatpickr

**Comment by jcjabros** [comment]
> Are you sure that it is specific to this vue component.
> And it is not happening with plain js version of flatpickr.
> 
> You example does not include any Vue.js component, you might want to report this issue at
> 
> https://github.com/flatpickr/flatpickr

I think is happening with the plain js , maybe it can be fix with the toggle() function when clicking the element. Have any idea of how to do that with your component?

**Comment by ankurk91** [comment]
Unfortunately I can't , you have to report there
