### ISSUE TITLE
An example usage for validation provider of vee-validate

### ISSUE THREAD

**Issue by koraykupe** [ankurk91/vue-flatpickr-component#142]
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.1
* Vue.js version : 2.6.6
* Browser name and version : Chrome
* This package version : 8.1.2

I have base input fields for form elements which have validation errors and some more customisations. I created a base date picker (wrapper) component to include the error messages in the component itself. To achieve that I use ValidationProvider of vee-validate. I could not see any example usage with vue-flatpickr-component on the documentation.

It is something like this:

```vue
<ValidationProvider
            :name="$attrs.label"
            :rules="rules"
            :immediate="!!value"
            v-slot="{ errors, valid, flags }">
        <div :class="{'has-error': errors.length > 0 && touched === false && flags.dirty,
        'form-group': true}">
            {{ rules }}
            <label v-if="$attrs.label">{{ $attrs.label }}</label>
            <flat-pickr :v-validate="rules" v-model="innerValue" :config="config" v-bind="$attrs" @focusout="touched = false"></flat-pickr>
            <template v-if="errors.length > 0 && touched === false && flags.dirty">
                <base-validation-error :error-messages="errors"></base-validation-error>
            </template>
        </div>
    </ValidationProvider>
```

Probably something is wrong in the code.
Although I don't send any rule, it still acts like it is required. Can you help me, please?

Regards.

**Comment by ankurk91** [comment]
I have not used `ValidationProvider` component before. I don't know how it works.
I could not understand what you are trying to do in your example.

**Comment by koraykupe** [comment]
My goal is having a custom component, and I have to share the validation object between components for this case. Anyway, I will use the standalone flatpickr with my own solution. Thanks!
