### ISSUE TITLE
Update calendar on input blur

### ISSUE THREAD

**Issue by tnylea** [ankurk91/vue-flatpickr-component#143]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```
[x] Helpful Tip!

> Here was what I needed to happen: 

I needed to allow users the ability to type in a date in the textbox, I then needed the calendar to reflect that change. Here was my solution:

Add the `on-close` event, like so:
```
<flat-pickr v-model="dob" placeholder="Date of Birth (ex. 01-10-1990)" :config="config" @on-close="datePickerClosed"></flat-pickr>
```

Then, here is the `datePickerClosed` method you can add to make the calendar update:
```
datePickerClosed: function(date, value, instance){
    instance.setDate(value);
}
```

Hope that helps someone else who needs the same functionality.

FYI, in order to allow user to edit the input your config needs the `allowInput` option to be true:

```
config: {
    allowInput: true,
    dateFormat: 'm-d-Y',    
},
```

You can close this Issue, I just wanted to have it documented in case someone else finds it useful.

Cheers! 🍻

**Comment by ankurk91** [comment]
This has been reported before. I need to search.
This should be handled by flatpickr itself.

**Comment by bublik93** [comment]
Hello @ankurk91, I needed to allow users the ability to type in a date in the textbox too. And I then needed the calendar to reflect that change too. But if config has property` { clickOpens: false }`  the calendar does not update.

**Comment by ankurk91** [comment]
Create a jsfiddle to reproduce your issue, i will look into it

**Comment by bublik93** [comment]
@ankurk91, here is an example https://codepen.io/bublek/pen/oNNPVOr 
1) If I select date with button — all works perfect 
2) If I select date with textbox after blur v-model and calendar does not update.

I know that I can do `v-on:blur="listenToOnChangeEvent"` and create method
```
listenToOnChangeEvent(date) {
  this.date = date
}
```
but I don’t know how many dates I can have on the page, their number is unknown.

**Comment by gp0** [comment]
> This has been reported before. I need to search.
> This should be handled by flatpickr itself.
> 
> P.S Related #137

From your reply on #137 

> It does not fix any existing issue, user is supposed to press enter to confirm the date after input.

Are users supposed to _guess_ that they have to hit enter?

**Comment by ankurk91** [comment]
@gp0 
The original (parent library) requires user to hit enter key.

**Comment by bublik93** [comment]
@ankurk91  still actual issue
