### ISSUE TITLE
iOS native calendar is not shown

### ISSUE THREAD

**Issue by danielcharrua** [ankurk91/vue-flatpickr-component#145]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report 
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.1
* Vue.js version : 3.8.2
* Browser name and version : iOS 12 Safari
* This package version : 8.1.2

**Current behavior**
The issue is when using the vue-flatpickr-component on an iPhone, the native calendar is not shown. I have tried the demos https://ankurk91.github.io/vue-flatpickr-component/ on my iPhone and they are not showing natively.. Also looked into https://flatpickr.js.org/examples/ and they look as they should. 

**Expected behavior**
Run natively on iPhone devices.

**Minimal reproduction of the problem with instructions**
Just run the demos on https://ankurk91.github.io/vue-flatpickr-component/ and https://flatpickr.js.org/examples/ and see the differences.

**Comment by ankurk91** [comment]
You could not see them because I have disabled them via
`
disableMobile: true
`
