### ISSUE TITLE
onMonthChange does not trigger

### ISSUE THREAD

**Issue by sreerajr137** [ankurk91/vue-flatpickr-component#147]
```vue
      <flat-pickr
        v-model="date"
        :config="config"
        class="form-control"
        placeholder="Select date"
        name="date"
        @on-change="doSomethingOnChange"
        @onMonthChange="doSomethingonMonthChange"
      ></flat-pickr>
```
``

      config: {
        wrap: true, // set wrap to true only when using 'input-group'
        altFormat: "M	j, Y",
        altInput: true,
        dateFormat: "Y-m-d",
         enable: ["2019-06-22", "2019-06-23", "2019-06-24", "2019-07-05", "2019-07-25", "2019-07-24"]
      },
```

The code above is not working, for some reason the onMonthChange doesn't fire when you change the month.

**Comment by ankurk91** [comment]
Event names should be in kebab case.
Can you try that?

**Comment by ankurk91** [comment]
Closing due to in-activity
