### ISSUE TITLE
Cannot set placeholder dynamically

### ISSUE THREAD

**Issue by doyaaaaaken** [ankurk91/vue-flatpickr-component#148]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report
```

**Tell about your platform**

In Js Fiddle
https://jsfiddle.net/ankurk91/63kzdwLx/

**Current behavior**

I tried to set vuejs data property on placeholder value.
But cannot change placeholder dynamically.
Below is the code.
```html
<main id="app">
  <input v-model="sampleRadio" type="radio" name="sampleRadio" value="a"><label>a</label>
  <input v-model="sampleRadio" type="radio" name="sampleRadio" value="b"><label>b</label>
  <p>{{sampleRadio}}</p>
  <flat-pickr v-model="date" :config="config" :placeholder="'Select a date' + sampleRadio" name="birthdate"></flat-pickr>
</main>
```

**Minimal reproduction of the problem with instructions**

Past above code in js fiddle (https://jsfiddle.net/ankurk91/63kzdwLx/) .

**Comment by ankurk91** [comment]
Can you set `altInput` to false and check again.

This is  known issue, i am helpless because the original flatpickr create a hidden input when `altInput` is true.

**Comment by doyaaaaaken** [comment]
Thank you, I confirmed it!
My question is resolved, so please close this issue.
