### ISSUE TITLE
time_24hr not reactive when using Vue.set

### ISSUE THREAD

**Issue by Katherraptor** [ankurk91/vue-flatpickr-component#149]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.1
* Vue.js version : 2.6.10
* Browser name and version : Chrome 75.0.3770.100
* This package version : 8.1.2

**Current behavior**
Changing config value `time_24hr` doesn't impact shown timepicker even when config value is changing via Vue.set()

**Expected behavior**
I would expect when `time_24hr` is set to true in the config the 'AM/PM' at the end of the timepicker would be hidden and I'd be able to click through all 24 hours

**Minimal reproduction of the problem with instructions**
https://jsfiddle.net/katherraptor/qzhn3psv/29/

**Comment by ankurk91** [comment]
I could not re-produce it with plain version of flatpickr

https://jsfiddle.net/e30kn7uz/6/

I parent library does not support this then sadly we cant support it in vue.js too.

**Comment by Katherraptor** [comment]
drat that's unfortunate, I found a workaround by forcing a re-render of the component using the `key` attribute:
https://jsfiddle.net/katherraptor/qzhn3psv/42/

**Comment by Jogai** [comment]
It worked for me when I made the config a computed method.
