### ISSUE TITLE
Webpack 4, splitchunks, webpack dev server: Failed to read the 'cssRules' property from 'CSSStyleSheet'

### ISSUE THREAD

**Issue by MaikelGG** [ankurk91/vue-flatpickr-component#150]
**I'm submitting a bug report**  

**Tell about your platform**
* flatPickr version : 4.6.1
* Vue.js version : 2.6.10
* Browser name and version : Chrome 75
* This package version : 8.1.2
* Webpack version: 4.32.2
* Webpack dev server: 3.7.2

**Current behavior**
I am switching from webpack 3 to version 4 and get an error. It is set up with splitchunks enabled. When splitchunks is disabled the problem is gone, also in webpack 3 it was no problem. All files locally are served over http. 

Has anyone else had this problem? I think I have set all CSP correctly and since it is all the same local server, I do not see where the difference is, except the files are split up in chunks.

```
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at positionCalendar (http://localhost:5000/packs/js/8-f97ce01bc1b88fb4bbbf.chunk.js:27433:31)
    at open (http://localhost:5000/packs/js/8-f97ce01bc1b88fb4bbbf.chunk.js:27244:9)
    at HTMLInputElement.<anonymous> (http://localhost:5000/packs/js/8-f97ce01bc1b88fb4bbbf.chunk.js:26314:28)
positionCalendar @ flatpickr.js:1958
open @ flatpickr.js:1769
(anonymous) @ flatpickr.js:839
```

**Comment by ankurk91** [comment]
Try to re-produce it on
https://codesandbox.io/

I have no clue.

**Comment by MaikelGG** [comment]
The problem seems unrelated to flatpickr, chrome gives a wrong indicating on the problem. I solved the issue with changing the webpack configuration.

**Comment by kriss145** [comment]
@MaikelGG  Could you write your solution? we have the same problem

**Comment by eliamartani** [comment]
That would be good, I'm facing the same issue here
