### ISSUE TITLE
Calendar not updating when using allowInput: true

### ISSUE THREAD

**Issue by add1ct3dd** [ankurk91/vue-flatpickr-component#152]
Hey guys,

So it's going to be a similar issue to this: https://github.com/flatpickr/flatpickr/issues/1371

However according to https://github.com/ankurk91/vue-flatpickr-component#events it looks like we can use the events as in the normal flatpickr events, but I haven't seen any examples to know what kind of format this is or how to write them.

Is there any chance we can expand further on the basic README to cover this, or do you know how I can essentially update the calendar on input? Having to press enter (standard flatPickr behaviour) is certainly not ideal in a lot of cases if the user chooses to write it rather than use the calendar.

If you need anymore information please let me know.

Thanks.

**Comment by ankurk91** [comment]
This is how you can listen to events
https://github.com/ankurk91/vue-flatpickr-component/blob/30bd5f75d1a69fc24b434e3ff4730b4cda7344a2/examples/App.vue#L298-L300

Event listener methods will receive same parameters like original flatpickr.

**Comment by add1ct3dd** [comment]
That doesn't work - @on-change only triggers if you select via the calendar control - is there not a way to trigger that event when the input is modified?

**Comment by ankurk91** [comment]
It was just an example.

I think you need to listen to native input event.

https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

**Comment by SmelayaPanda** [comment]
`<flat-pickr v-model="date" :config="config"`

`config: {
    allowInput: true,
    dateFormat: "Y-m-d",
    parseDate: dateString => new Date(moment(dateString))
},
`
You can use the Momentjs library to convert any dates and return the Date object to the flatpckr.
