### ISSUE TITLE
Range mode minDate issue

### ISSUE THREAD

**Issue by LeonAlvarez** [ankurk91/vue-flatpickr-component#153]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.2
* Vue.js version : 2.6.6
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 8.1.2

**Current behavior**
In range mode if the value is equals to the minDate its trucated and only the end date of the range shows. You can select it and its shows correctly but if value set using v-model it will only show the last date.

![image](https://user-images.githubusercontent.com/22636643/62294462-3ed29800-b46b-11e9-9534-1ab51c521f9d.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/22636643/62294414-2498ba00-b46b-11e9-844c-0d072a34b896.png)

**Minimal reproduction of the problem with instructions**

Config 
```
 date_range_config: {
        minDate: new Date(),
        mode: "range"
      },
```

**Comment by ankurk91** [comment]
Please describe more,
try to reproduce here
https://jsfiddle.net/zn4fr2o1/

**Comment by LeonAlvarez** [comment]
Sorry forgot to add the link https://jsfiddle.net/n53dpfha/3/

With truncated I mean it only shows the `start_date` instead of `start _date to end_date`

**Comment by ankurk91** [comment]
Okay, i will try to reproduce it with original flatpickr.
I dont think it is vue.js issue.

**Comment by LeonAlvarez** [comment]
Hi, I have done some testing with flatpickr itself and its the same behavior:
https://jsfiddle.net/9ghfca2y/
found a workaround with minDate: 'today' 
https://jsfiddle.net/9ghfca2y/1/

Wich also work with vue:
https://jsfiddle.net/4mwx8qkv/

Im gonna try setting the date to start of the day.
