### ISSUE TITLE
Update flatpickr version

### ISSUE THREAD

**Issue by bcorcoran** [ankurk91/vue-flatpickr-component#154]
Can you please update the flatpickr version to ^4.6.0 ?

**Comment by ankurk91** [comment]
It is already updated.

https://github.com/ankurk91/vue-flatpickr-component/blob/30bd5f75d1a69fc24b434e3ff4730b4cda7344a2/package.json#L38


The caret ^ sign already allows package consumers to install v4.6

**Comment by bcorcoran** [comment]
Odd, I have 8.1.2 and my package.json says ^4.5.1

**Comment by ankurk91** [comment]
Like i said the caret sign already allows you to install 4.6.
Uninstall this package and reinstall should pick latest version
