### ISSUE TITLE
Value can be changed in inline disabled component

### ISSUE THREAD

**Issue by nastassiadanilova** [ankurk91/vue-flatpickr-component#156]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**
`
<flat-pickr 
    disabled
    :config="{
       inline: true
    }"
    v-model="dateInline"
/>
`
Only input is disabled, value still can be changed via datepicker 
![Sep-03-2019 17-59-36](https://user-images.githubusercontent.com/11391037/64184799-b2a1ff00-ce74-11e9-9475-c5998a017586.gif)

**Expected behavior**
`disabled` prop should disable both input and date picker

**Comment by ankurk91** [comment]
Does original flatpickr have the same issue?

**Comment by nastassiadanilova** [comment]
@ankurk91, original flatpickrs `disable` option doesn't disable hole date-picker. It's possible to disable just specific dates or ranges of dates

**Comment by ankurk91** [comment]
`<flat-pickr disabled :config="{ inline: true }" v-model="dateInline" />`

The disable prop you are talking about will be applied on the input field itself.
```
<input type="text" disabled >
```

**Comment by ankurk91** [comment]
It turns out that original flatpickr behaves the same

https://jsfiddle.net/w7tm1n08/
