### ISSUE TITLE
Fflatpickr not close in modal

### ISSUE THREAD

**Issue by AndriyYushko** [ankurk91/vue-flatpickr-component#158]
When I set properties static: true and enableTime: true flatpickr not close on lost focus in modal window.
My version: flatpickr@3.0.6

**Comment by ankurk91** [comment]
I wish if you can setup a js-fiddle to demonstrate that.

We maintainers are also employees under some organisation. Help us to save some time.

No worries, i will try to reproduce it.

**Comment by ankurk91** [comment]
I am sure this issue is not related to vue, please report this issue to 
https://github.com/flatpickr/flatpickr
Someone may have asked/reported this already
