### ISSUE TITLE
css not working on desktop size

### ISSUE THREAD

**Issue by y-ogura** [ankurk91/vue-flatpickr-component#159]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.1
* Vue.js version : 2.6.10
* nuxt version: 2.8.1
* Browser name and version : Chrome 77.0.3865.90
* This package version : 8.1.3

**Current behavior**

Not working css on PC size.  
Reproduction procedure is
1. npm run build
2. npm run start

![image](https://user-images.githubusercontent.com/30112982/66288396-055b5480-e914-11e9-887d-9cb8c90e9cf5.png)

but use `npm run dev`
![image](https://user-images.githubusercontent.com/30112982/66288891-f1b0ed80-e915-11e9-84e6-1dea7fa3dc31.png)

this is my code
```vue
<template>
  <div>
    <flat-pickr
      v-model="dateItem"
      class="bg-white mr-1 ml-2 outline-none w-full"
      placeholder="2018-01-01"
      :config="config"
    />
  </div>
</template>
<script>
import flatPickr from 'vue-flatpickr-component'
import { Japanese } from 'flatpickr/dist/l10n/ja'
require('flatpickr/dist/themes/material_green.css')

export default {
  components: {
    flatpickr
  },
  data() {
    return {
      dateItem: '',
      config: {
        locale: Japanese
      }
    }
  }
}
</script>
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Can you setup a codesandbox with nuxt.js ?
What is  meant by PC size?

**Comment by y-ogura** [comment]
sorry.
'PC size' meant window size.
mobile device was expected behovior.

this is [codesandbox](https://codesandbox.io/s/vue-flatpickr-with-nuxt-3nzhy?fontsize=14).
but I couldn't reproduce with codesandbox.

**Comment by y-ogura** [comment]
I reproduce with codesandbox.
1. export to zip
2. open zip
3. npm install
4. npm run build && npm run start

**Comment by ankurk91** [comment]
Most likely it is a css issue.

Do you think it is caused by nuxt.js, if not then try to re-produce it without nuxt.js, this will remove some complexity
