### ISSUE TITLE
Not able to change class name from form-control to uk-input

### ISSUE THREAD

**Issue by theromie** [ankurk91/vue-flatpickr-component#16]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 3.x.x
* Vue.js version : 2.x.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

I want to change class name from form-control to uk-input to work with getuikit css and i change flatpicker.vue component and re run watch command but its not updating
` <input type="text"
         class="uk-input input"
         :id="id"
         :class="inputClass"
         :name="name"
         :placeholder="placeholder"
         :required="required"
         v-model="mutableValue"
         data-input>`

**Comment by ankurk91** [comment]
First thing first :
Issue template needs to filled property, this way package maintainers can solve your issues quickly. 

Second thing :
You should not directly edit files inside node_modules.

Last thing:
Please share your minimal reproduction of code.
The code you have shared is from node_modules.

**Comment by theromie** [comment]
thanks solve the issue
