### ISSUE TITLE
[8.1.3] Issue with defaultHour and defaultMinute

### ISSUE THREAD

**Issue by lk77** [ankurk91/vue-flatpickr-component#160]
```
[x] Bug report
[ ] Feature request
[ ] Other, please describe
```

* flatPickr version : 4.6.3 :
* Vue.js version : 2.6.10
* Browser name and version : Chrome 77
* This package version : 8.1.3

**Current behavior**

Hello,

i have an issue with `defaultHour` and `defaultMinute` that is ignored :

vue js :

https://jsfiddle.net/lk77/q7s092k1/7/

plain js :

https://jsfiddle.net/lk77/7x3br8o6/6/

in plain js, when i click, i have 00:00,
and with vue i have the current time.

thanks.

**Comment by ankurk91** [comment]
Thanks for reporting, will debug more.

**Comment by lk77** [comment]
Hello,

on 8.1.2 it's working fine :
https://jsfiddle.net/lk77/bqn0s5e3/1/

**Comment by lk77** [comment]
Thanks
