### ISSUE TITLE
When Changing minDate programmatically, month dropdown doesn't update

### ISSUE THREAD

**Issue by solankivj94** [ankurk91/vue-flatpickr-component#162]
[vue-flatpickr-demo.zip](https://github.com/ankurk91/vue-flatpickr-component/files/3701615/vue-flatpickr-demo.zip)
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.3
* Vue.js version : 2.6.10
* Browser name and version : Firefox 69.0.1
* This package version : 8.1.3

**Current behavior**
When `minDate=new Date()`, then month dropdown shows month from current date to end of year, which is correct, But when `minDate=null` month dropwdown show month from current date and when changing month from arrow, then month changes but it doesnt show name of month in dropwdown

**Expected behavior**
when programmatically changing `minDate=null` , it should show all month in year.

**Demo**: https://codesandbox.io/s/vue-flatpickr-demo-8hxu5
**if codesanbox gives error i have added source code**

**Comment by ankurk91** [comment]
The original (plain.js) flatpickr behaves the same, see 
https://jsfiddle.net/7km0q92t/
