### ISSUE TITLE
Can't clear the input date

### ISSUE THREAD

**Issue by vitality82** [ankurk91/vue-flatpickr-component#163]
Question

* flatPickr version : 4.6.2
* Vue.js version : 2.6.10
* Browser name and version : Chrome latest

When hitting backspace or selecting everything inside the input and clicking backspace why doesn't the v-model binding update my data prop? It does so for the time picker...

```
<flat-pickr
	v-model="atTime"
	name="atTime"
	:config="timePickerConfig"
	:class="classes"
	placeholder="Select time..."
	autocomplete="off"
></flat-pickr>

<flat-pickr
	v-model="onDate"
	name="onDate"
	:config="datePickerConfig"
	:class="classes"
	placeholder="Select date..."
></flat-pickr>


data() {
	return {
		onDate: null,
		atTime: null,
                datePickerConfig: {
	                wrap: false,
	                allowInput: true,
	                altInput: true,
	                altFormat: 'M j, Y',
	                dateFormat: 'm-d-y'
                }.
	        timePickerConfig: {
                        allowInput: true,
		       noCalendar: true,
		       enableTime: true,
		       dateFormat: 'h:i K',
		       minuteIncrement: 1
               }
	}
}
```

**Comment by ankurk91** [comment]
Does original flatpickr behaves the same?
I think someone raised this issue before, please search.

**Comment by vitality82** [comment]
I found 2 related issues on the original:
[https://github.com/flatpickr/flatpickr/issues/1910 (https://github.com/flatpickr/flatpickr/issues/1910)

[https://github.com/flatpickr/flatpickr/issues/1621](https://github.com/flatpickr/flatpickr/issues/1621)

I got it working (v-model data reacting to backspace) if doing either of the following workarounds:

1. Remove `altInput: true`
2. Remove `allowInput: true`

So there might be a bug in the original Flatpickr...

**Comment by moh1434** [comment]
This will help if someone want to clear the date and time
```
<template>
 <flat-pickr  ref="datePickerWrap"
    :config="{
      enableTime: true,
      dateFormat: 'Y-m-d h:i K',
      altInput: true,
    }"
></flat-pickr>
<button @click="clearDate()">clear</button>
</template>
```
```
<script setup lang="ts">
import { ref } from "vue";
import flatPickr from "vue-flatpickr-component";
import { Instance } from "flatpickr/dist/types/instance";
const datePickerWrap = ref<{ fp: Instance }>();
function clearDate() {
  if (!datePickerWrap.value) {
    console.error("datePickerWrap not found");
    return;
  }
  datePickerWrap.value.fp.clear();
}
</script>
```
https://github.com/flatpickr/flatpickr/issues/1494#issuecomment-419551559
