### ISSUE TITLE
Demo code example not available - Question

### ISSUE THREAD

**Issue by bsienn** [ankurk91/vue-flatpickr-component#164]
**I'm submitting a ...**
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Question
```
In the demo page, there is a very neat date `from/to`  range type picker.
I don't find any config or sample code for that demo. Can you please provide the code for that?

https://ankurk91.github.io/vue-flatpickr-component/

![asd](https://user-images.githubusercontent.com/3149876/67068594-ff773600-f193-11e9-813b-d57acee8a09b.png)

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-flatpickr-component/blob/master/examples/App.vue
