### ISSUE TITLE
Change locale doesn't work

### ISSUE THREAD

**Issue by do-yeon** [ankurk91/vue-flatpickr-component#172]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**

Change locale doesn't work even your demo page (https://ankurk91.github.io/vue-flatpickr-component/)

**Expected behavior**

locale should be changed.

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
it is working fine for me.

<img width="782" alt="change-locale" src="https://user-images.githubusercontent.com/6111524/68295644-d245e580-00b8-11ea-9843-d4650b333f37.png">

You can browse the example code
examples/App.vue

**Comment by ankurk91** [comment]
It is working fine for me.
![screen-record](https://user-images.githubusercontent.com/6111524/68295721-fe616680-00b8-11ea-9b70-033573b3380e.gif)

You can see code here
examples/App.vue

**Comment by do-yeon** [comment]
The year selectbox didn't change!

**Comment by ankurk91** [comment]
Please report this issue on parent repo, try to re-produce it with plain flatpickr.
