### ISSUE TITLE
RTL Suport

### ISSUE THREAD

**Issue by jd-0001** [ankurk91/vue-flatpickr-component#173]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.3
* Vue.js version : 8.1.4
* Browser name and version : Chrome 78.0.3904.70
* This package version : x.x.x

**Current behavior**
In RTL version of my app datepicker opens from left

**Expected behavior**
It should open from right - due to js-styles. I can't change it using CSS as component is rendered in root not as sibling of input.

**Minimal reproduction of the problem with instructions**
I can give you GIF as you already know how it works.

**How it works**
![rtl-support](https://user-images.githubusercontent.com/47495003/68652654-f473b380-054f-11ea-9726-620159965f9f.gif)

**How it should work in RTL** (this opens like RTL due to no space on right)
![rtl-like](https://user-images.githubusercontent.com/47495003/68652778-33a20480-0550-11ea-9a24-368b0e22ff83.gif)

**Comment by ankurk91** [comment]
Please report such issue here
https://github.com/flatpickr/flatpickr
