### ISSUE TITLE
no month in date range

### ISSUE THREAD

**Issue by mihakot** [ankurk91/vue-flatpickr-component#174]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.3
* Vue.js version : 2.6.10
* Browser name and version : Chrome 78.0.3904.108
* This package version : 8.1.5

**Current behavior**

The name of months is incorrectly displayed for a given permitted date range.
version 8.1.5
![image](https://user-images.githubusercontent.com/1734182/70227112-146b5100-1763-11ea-876d-b28838118574.png)

in dropdown select only current month

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Used `ru` locale and set `min` and `max` date
````
{"allowInput":true,"minDate":"27.11.2019","maxDate":"05.12.2019","dateFormat":"d.m.Y","locale":{"weekdays":{"shorthand":["Вс","Пн","Вт","Ср","Чт","Пт","Сб"],"longhand":["Воскресенье","Понедельник","Вторник","Среда","Четверг","Пятница","Суббота"]},"months":{"shorthand":["Янв","Фев","Март","Апр","Май","Июнь","Июль","Авг","Сен","Окт","Ноя","Дек"],"longhand":["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"]},"firstDayOfWeek":1,"ordinal":{"_custom":{"type":"function","display":"<span>ƒ</span> ordinal()"}},"rangeSeparator":" — ","weekAbbreviation":"Нед.","scrollTitle":"Прокрутите для увеличения","toggleTitle":"Нажмите для переключения","amPM":["ДП","ПП"],"yearAriaLabel":"Год","time_24hr":true},"disable":[]}

````

**Comment by ankurk91** [comment]
Please create a re-production of the issue on jsfiddle or codesandbox.

**Comment by mihakot** [comment]
https://jsfiddle.net/mihakot/93vL14wy/14/

**Comment by ankurk91** [comment]
related issue
https://github.com/ankurk91/vue-flatpickr-component/issues/162

**Comment by ankurk91** [comment]
You are updating the min and max dates after initialisation.
The original flatpicker does not consider this change and does not update months dropdown.
https://jsfiddle.net/7km0q92t/

please report this issue to  
https://github.com/flatpickr/flatpickr/issues
