### ISSUE TITLE
Configuration "enableTime: true" random date picking

### ISSUE THREAD

**Issue by antonxvoro** [ankurk91/vue-flatpickr-component#175]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.3
* Vue.js version : 3.1.2
* Browser name and version : Chrome (79.0.3945.79) | Firefox (71.0)
* This package version : 8.1.4

**Current behavior**
When flatPickr component is open, no date time is selected and you click outside component's DOM flatPickr automatically set random date time (no event is triggered)

**Expected behavior**
When flatPickr component is open, no date time is selected and you click outside component's DOM flatPickr must not set value

**Minimal reproduction of the problem with instructions**
https://jsfiddle.net/antonvoro/tfwezacL/12

**Comment by ankurk91** [comment]
The [parent](https://github.com/flatpickr/flatpickr) library behaves the same, check:
http://jsfiddle.net/bqcp63vm/1/

i have no control on it.
