### ISSUE TITLE
Disable automatic month switching with Multiple months

### ISSUE THREAD

**Issue by chrisgrim** [ankurk91/vue-flatpickr-component#176]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ x] Other, Issue with performance, though I am not sure its a bug
```

**Tell about your platform**
* vue-flatpickr-component@8.1.5
* Vue.js version : 2.6.11
* Browser name and version : Chrome

**Current behavior**
When I show two months side by side (Jan Feb). If I click on any of the dates in February it switches the calendar so it now shows February and March.

**Expected behavior**
I would expect it to just select the days I am selecting in February and then if I wanted to add dates in March I could use the arrows at the top.

**Minimal reproduction of the problem with instructions**

**Comment by chrisgrim** [comment]
Hi,
I created this https://jsfiddle.net/8mj4ay3g/ to show an example with vue. I did find this with flatpickr js 

https://github.com/flatpickr/flatpickr/issues/1496

Which makes me think that it was fixed with flatpickr. I can't seem to get it working in jsfiddle with plain js

**Comment by ankurk91** [comment]
The plain js flatpickr behaves the same, see
http://jsfiddle.net/z9618jgq/1/

You should report this issue to parent repo.
Feel free to re-open the issue if get it wrong.

**Comment by chrisgrim** [comment]
Gotcha! Thanks @ankurk91  I reported it on the parent repo.
