### ISSUE TITLE
Different design if altInput = true

### ISSUE THREAD

**Issue by mikelmao** [ankurk91/vue-flatpickr-component#177]
It seems that the design of the input box changes when altInput is set to true. How would I achieve both of the views to be the same?

![image](https://user-images.githubusercontent.com/1472972/71173044-0557c900-2262-11ea-878c-2f52ae988330.png)

**Comment by ankurk91** [comment]
Please create a re-production on js-fiddle.

FYI: When `altInput` is set to true the actual input field goes hidden and flatpickr creates a new one for user.

**Comment by mikelmao** [comment]
Ah ok @ankurk91 ,

How would i achieve being able to set the same classes as the original input field?

**Comment by ankurk91** [comment]
Flatpickr will auto copy all css classes, you no need to, see

http://jsfiddle.net/nzasftom/2/

**Comment by mikelmao** [comment]
> Flatpickr will auto copy all css classes, you no need to, see
> 
> http://jsfiddle.net/nzasftom/2/

Thanks @ankurk91 , setting the classes on the flat-pickr component fixed it indeed :)
