### ISSUE TITLE
How to access the altInput: true for use in another part of page

### ISSUE THREAD

**Issue by chrisgrim** [ankurk91/vue-flatpickr-component#179]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 8.1.5
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**
As my date value I see 2020-01-07 00:00:0 to 2020-01-08 00:00:0"

**Expected behavior**
I have setup the config to have altFormat:'M d' and  altInput: true, which gives me 
Jan 07 to Jan 09. Is there any way I can get access to the alt format to display elsewhere on my page?

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Flatpicker has some utility method exposed to public, that can be used. check

https://github.com/flatpickr/flatpickr/blob/5116b013c2e74cfacb96ae73496333f311c84600/src/index.ts#L2935

https://flatpickr.js.org/instance-methods-properties-elements/#methods
