### ISSUE TITLE
It displays UTC dates as the local time rather than UTC Time

### ISSUE THREAD

**Issue by reginsmol** [ankurk91/vue-flatpickr-component#180]
**I'm submitting a ...**  (check one with "x")
```
[X ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.1
* Vue.js version : 2.6.5
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 8.1.3

**Current behavior**

Giving a default date & time to `VueFlatPicker` in UTC displays the value as the local browser's time rather than in UTC 
**Expected behavior**

Displaying the date and time as UTC
**Minimal reproduction of the problem with instructions**
```vue
<template>
    <vue-flat-pickr
            ref="inputDateTimeWrapper"
            v-model="input"
            class="dateTimeInput"
            :config="dateTimeConfig"> 
    </vue-flat-pickr>
</template>
<script>
export default {
data() {
    return {
        input: '2020-01-14T21:27:34Z',
        dateTimeConfig: {
             defaultDate: '2020-01-14T21:27:34Z',
             enableTime: true,
             altInput: true,
             mode: 'single',
             static: true,
             position: 'below',
             altFormat: 'Y-m-d h:i'
         },
      }
  }
}
</script>
```

**Comment by ankurk91** [comment]
Can you try to re-produce it with plain js version

https://jsfiddle.net/gf3jtkL6/1/

If you can. it means you should report the issue to parent repo instead.

**Comment by ankurk91** [comment]
Please check
https://github.com/flatpickr/flatpickr/issues/930
