### ISSUE TITLE
How do you append the picker to an arbitrary element?

### ISSUE THREAD

**Issue by paolomangiadev** [ankurk91/vue-flatpickr-component#182]
I'm trying to append the picker to an icon, is it possible?
Also i tried to hide the input as i don't want it but then when i toggle the picker it shows centered on the icon that i use to toggle it.

config:
```javascript
{
  wrap: true,
  altInputClass: "d-none",
  appendTo: this.$refs.rand // reference of the icon (i want the picker to display below it)
}
```

**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by m1stermanager** [comment]
@paolomangiadev did you resolve this?

**Comment by paolomangiadev** [comment]
@m1stermanager no i ended up using: vuejs-datepicker
