### ISSUE TITLE
Update wording " to " in range mode

### ISSUE THREAD

**Issue by webkupas** [ankurk91/vue-flatpickr-component#183]
Hello, could you please suggest how to replace word "to" with others in input field of datepicker in range mode.

E.g. instead of **28/02/2020 to 29/02/2020**
Im gonna see **28/02/2020 - 29/02/2020**

**Comment by ankurk91** [comment]
Everything is documented here

https://flatpickr.js.org/options/

**Comment by MariusTechweb** [comment]
It's not documented there, @ankurk91
