### ISSUE TITLE
Default displayed month is the month last month with selected dates

### ISSUE THREAD

**Issue by chrisgrim** [ankurk91/vue-flatpickr-component#184]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**
Hi,
If I load an array of dates into vue flatpickr ranging from March to July, the default month shown in the browser will be July since that is the last month with dates.

**Expected behavior**
Is there a way to instead show the current month as the default month even if I have loaded days in June or July?

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Can you re-produce thid issue with plain js version?

**Comment by chrisgrim** [comment]
Hi @ankurk91 
Sorry I am not very proficient with plain js. I bet it happens with the original. I did find in the original they have 
jumpToDate(date, triggerChange)https://flatpickr.js.org/instance-methods-properties-elements/
 but I am not sure how to integrate this with vue flatpickr.

**Comment by ankurk91** [comment]
@chrisgrim 
If you could provide me a vue.js based js-fiddle, it would be helpful.

Here is the plain js version
http://jsfiddle.net/wyre6Lq0/

If you think it behaves same in plain.js, then please report/ask on original(parent) repo instead.

**Comment by ankurk91** [comment]
Closing since this issue is not related to vue component.
