### ISSUE TITLE
Calendar width collapsed inside tab not actively loaded with page

### ISSUE THREAD

**Issue by chrisgrim** [ankurk91/vue-flatpickr-component#185]
**I'm submitting a ...**  (check one with "x")
```
[ x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**
On my current page I have 3 tabs and my calendar is inside one of them. If I have the tab with the calendar set to the active tab when the page loads everything works great. However if the tab isn't the active tab, when I switch to the calendar tab my calendar has been compressed to 2px wide. Here is what I am getting in my html
```html
<div class="flatpickr-calendar animate multiMonth inline showTimeInput" tabindex="-1" style="width: 2px;">
<div class="flatpickr-days" tabindex="-1" style="width: 2px;">
```
**Expected behavior**
Here is what I get with the calendar active tab open
```html
<div class="flatpickr-calendar animate multiMonth inline" tabindex="-1" style="width: 602px;">
<div class="flatpickr-days" tabindex="-1" style="width: 602px;">
```
**Minimal reproduction of the problem with instructions**
I am not exactly sure how to recreate this on codepen. How is the width for the calendar generated?

**Comment by ankurk91** [comment]
Sorry, i was not able to re-produce it.
https://jsfiddle.net/nmvwhsgu/

The date-picker widget works well even when not visible initially.

I don't think your issue is related to vue component, you might want to redirect your issue to [parent](https://github.com/flatpickr/flatpickr) repo instead.

Thanks

**Comment by chrisgrim** [comment]
Hi @ankurk91 
I edited your fiddle and was able to recreate the error. Please check here 
https://jsfiddle.net/bu8nrx07/1/

**Comment by ankurk91** [comment]
I have changed v-show to v-if.

https://jsfiddle.net/xg61pzw8/

It worked fine now. 
Certainly this issue is not related to vue component, the flatpicker itself is unable to calculate the width when not visible.

**Comment by chrisgrim** [comment]
I guess so! That solved my problem though so thank you so much!!
