### ISSUE TITLE
previous value showing when on change fires

### ISSUE THREAD

**Issue by marianne-fullstack** [ankurk91/vue-flatpickr-component#187]
Hi, im trying to use this library for my project and Im trying to get the value of my flatpickr during the onchange event but it's always returning the previous value of the flatpickr before the event fires.. i need to parse the date before reaching my db and i have to do it during the onchange event :))

**Here's my flatpickr instance**
```html
 <flat-pickr v-model="dateholder" :config="config"  class="form-control form-input form-input-bordered w-full flat-pickr" placeholder="Select date" @on-change="parseDate(ungrouped.id)" name="date"> </flat-pickr>
```

**The method im using**
`parseDate() { console.log(this.dateholder) }`

**Comment by ankurk91** [comment]
@marianne-fullstack 
This information is not sufficient, please provide a minimal js fiddle to demonstrate your issue.

Why dont you use `v-model` ?

**Comment by marianne-fullstack** [comment]
Closing this issue now.. had to use the default argument, dateStr. My bad
