### ISSUE TITLE
flatPickr  subtracts 6 hours from the date received

### ISSUE THREAD

**Issue by vgutnar** [ankurk91/vue-flatpickr-component#189]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 8.1.5
* Vue.js version : 2.5.17
* Browser name and version : Chrome|Firefox|MS Edge
* This package version : x.x.x

**Current behavior**
flatPickr  subtracts 6 hours from the date-time received.
Below is an exaple:
Date-time supplied to flatPickr    is:  2020-06-04T11:15:00.000000Z
But flatPickr   displays date-time as:  2020-06-04 04:15 (format is correct)

Below are my flatPickr configurations:
altFormat: this.time ? 'M j, y h:i:K',
altInput: true,
dateFormat: this.time ?  'Y-m-d H:i',
enableTime: this.time,

I did tried to test with the same time format for altFormat and dateFormat, that did not made any difference.

**Expected behavior**
The date-time should be displayed as:  2020-06-04 11:15
My computer is located in PST (Pacific Time Zone) time zone.

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Please report this issue to
https://github.com/flatpickr/flatpickr
