### ISSUE TITLE
AM/PM switch does not always work when selecting a time

### ISSUE THREAD

**Issue by Dahje** [ankurk91/vue-flatpickr-component#19]
[ x ] Bug report

**Tell about your platform**
* flatPickr version : 3.0.6
* Vue.js version : 2.3.3
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 2.4.1

**Current behavior and reproduction**

When using a date and time picker you are unable to swap from PM to AM until you use the hour fields spinner to get to the AM state. After the AM state has been reached once then you can click on AM/PM to change.

**Edit: After a bit more testing it appears that it is simply that the the AM/PM is always stuck on PM when the hour is set to 12 PM.**

**Expected behavior**

A user should be able to click on the AM/PM switch at any time and change it.

**Comment by ankurk91** [comment]
@Dahje 
I could not reproduce the issue, see GIF. AM/PM toggle works fine.

![flatpickr-3-am-pm](https://user-images.githubusercontent.com/6111524/29200496-66c6afd4-7e73-11e7-9a53-6862bd026644.gif)

If you still facing the issue; report it to [flatpickr repo](https://github.com/ankurk91/vue-flatpickr-component) instead.

**Comment by Dahje** [comment]
@ankurk91  I guess I missed one slight detail when I said 12PM it must be exactly 12PM as in 12:00. Based on the example that you are using here it is not reproducible. Also I have tested the issue on the demo page for flatpickr and it does work on theirs and many other libraries that use the same component, but not in your repo.

**Comment by Dahje** [comment]
@ankurk91 I have finally figured out what the real problem is and it lies entirely on the dateFormat config option. If you set a string using 'h'(12 hour) and 'K'(AM/PM) it will not properly switch AM/PM when the hour is set to 12. This is quite strange though as it will work if you set a string using 'H'(24 hour) and 'K'(AM/PM). It appears this will most likely be an issue with the flatpickr repo and is properly a flipped Boolean check.

**Comment by ankurk91** [comment]
@Dahje 
I was able to re-produce this issue. I will look into it.

Here is the config just for future reference -
```js
                enableTime: true,
		 minDate: 'today',
		 altFormat: true,
		 dateFormat: 'F j, Y h:i K',
		 time_24hr: false,
```

**Comment by Dahje** [comment]
@ankurk91 has there been any progress on this issue?

**Comment by ankurk91** [comment]
@Dahje 
Sorry did not get enough time. Will try to debug this weekend.

**Comment by Dahje** [comment]
Thanks for the update! Appreciate it.

**Comment by ankurk91** [comment]
@Dahje
I found the root cause. 
```html
<div>
  <input type="text" placeholder="Select Date.." class=date>
  <button id="set-new">
    Set new value
  </button>
</div>
```
```js
var fp = flatpickr(".date", {
  enableTime: true,
  minDate: 'today',
  altFormat: true,
  dateFormat: 'F j, Y h:i K',
  time_24hr: false,
  onChange: function(s, date) {
    console.log('Final date - ', date);
  }
});

document.getElementById("set-new").addEventListener('click',
  function() {
    console.log('setting new date')
    fp.setDate('September 23, 2017 12:00 AM', true)
  })
```

This is a bug in flatpickr itself. When we try to set a date pragmatically via `setDate` method.
You can see in jsfiddle that we are trying to set a date with 12 hour AM but date picker not accepting it and converting it to PM.
https://jsfiddle.net/tgbd125r/3/

**Comment by Dahje** [comment]
@ankurk91 has this now been properly fixed and available on npm?

**Comment by ankurk91** [comment]
@Dahje
Flatpickr v4 has been released, I will give it a try and will release new version soon ASAP.

**Comment by Dahje** [comment]
Wonderful, thanks for the quick reply 👍

**Comment by adam-goodrich** [comment]
I am still having this issue
