### ISSUE TITLE
Not working as in example

### ISSUE THREAD

**Issue by kikky7** [ankurk91/vue-flatpickr-component#191]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : latest
* Vue.js version : 2.6.10
* Browser name and version : Chrome latest
* This package version : 8.1.5

**Current behavior**
No style of datepicker, placeholder doesn't work.
It opens only on icon click, not whole input.
It simply doesn't work as in demo examples

**Expected behavior**
To work...

This is how it looks:
![datepicker](https://user-images.githubusercontent.com/57031667/87872843-5a0c1f80-c9bc-11ea-8b71-829126a271c4.jpg)

Import:
```
import flatPickr from "vue-flatpickr-component";
import "flatpickr/dist/flatpickr.css";
```

Register component:
```
components: {
    flatPickr
},
```

Render component:
```
<flat-pickr
        v-model="date"
        class="form-control"
        placeholder="Select a date"
></flat-pickr>
```

**Comment by ankurk91** [comment]
Please share an sample on code sandbox
