### ISSUE TITLE
Change Model from String to Date object

### ISSUE THREAD

**Issue by AKWintermute** [ankurk91/vue-flatpickr-component#195]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**

The model object is a string after selection.

**Expected behavior**

I feel like the model would be better served with a Date object or an array of Date objects from flatpackers.selecteddates property and let the view take care of the display. Maybe this could at least be a config option.

**Comment by ankurk91** [comment]
You can join us here
https://github.com/ankurk91/vue-flatpickr-component/issues/190
