### ISSUE TITLE
Error when setting the time with the keys "a" and "b"

### ISSUE THREAD

**Issue by yuniorlaureano** [ankurk91/vue-flatpickr-component#199]
I am using this component and a user of the app I am working on reported me that the hour was not chaging AM to PM. 
After having investigated I found out that when setting the time if you click the AM/PM button everything is ok, but when you use the keys "a" for AM, and "p" for PM it does not trigger the change event and therefore does not register the change in the model object.

**Comment by ankurk91** [comment]
Can you share a minimal js fiddle with that reproduce the issue

**Comment by ankurk91** [comment]
You can start from 
https://jsfiddle.net/wxz96v2b/

**Comment by yuniorlaureano** [comment]
Hello,
It is working, I mean the example you have in jsfiddle.
Maybe I am missing something.
Thanks for taking me in consideration
