### ISSUE TITLE
@on-value-update event is not available

### ISSUE THREAD

**Issue by lucianobosco** [ankurk91/vue-flatpickr-component#201]
As per official flatpickr docs there should be an `onValueUpdate` event. https://flatpickr.js.org/events/
I'm trying to trigger it via `@on-value-update` but no luck so far.
Also I'm seeing under your code the below array in `events.js` file:

```
// Let's not emit these events by default
const excludedEvents = [
  'onValueUpdate',
  'onDayCreate',
  'onParseConfig',
  'onReady',
  'onPreCalendarPosition',
  'onKeyDown',
];
```
Since the `@on-change` event is triggered despite input value is changed or not, when the input lost the focus (blur), I would need to make use of `onValueUpdate` event. Is that possible?

**Comment by ankurk91** [comment]
You can do it like this.

```html
<flat-pickr v-model="date" @on-value-update="yourCallback" :events="eventsToBeEmitted"></flat-pickr>
```

```js
data() {
    return {
         eventsToBeEmitted : [
               'onValueUpdate'
    ]
 }
}
```

This component does not emit all events by default, you can pass your events array, to override the default list of events.
