### ISSUE TITLE
Typescript declaration support

### ISSUE THREAD

**Issue by daomtthuan** [ankurk91/vue-flatpickr-component#202]
I'm using with nuxt/vue (lastest version) with typescript. Of course, when I import your module, it request the declaration file.
Can you write it for supporting the typescript project?

**Comment by volarname** [comment]
+1
also i suggest to use for exampe next branch for vue 3 support instead of master

**Comment by scorpion43** [comment]
This one maybe is not perfect, but if someone need some kind of temporary solution, please add this line to src/shims-vue.d.ts:

`declare module 'vue-flatpickr-component';`

**Comment by ankurk91** [comment]
Can someone test the type definitions

```
npm install vue-flatpickr-component@9.0.7
```

**Comment by Hugo01** [comment]
> Can someone test the type definitions
> 
> ```
> npm install vue-flatpickr-component@9.0.7
> ```

Just tested it
It looks like it is working

**Comment by ankurk91** [comment]
Released on latest channel
```
npm install vue-flatpickr-component@^9.0.8
```
