### ISSUE TITLE
error when call vue flatpickr

### ISSUE THREAD

**Issue by sadilegend** [ankurk91/vue-flatpickr-component#204]
issue when i call your component have this error
https://prnt.sc/v49y3u

**Comment by ankurk91** [comment]
Thanks, the fiddle has been updated to use vue v3.
https://jsfiddle.net/ankurk91/63kzdwLx/

**Comment by sadilegend** [comment]
if i using vue v2 this plugin won't work?

**Comment by SandraRodgers** [comment]
Is it possible to use your component with Vue2 still? I'm getting the error but for my needs, I can't change to Vue 3

**Comment by ankurk91** [comment]
Yes  install the older version

https://github.com/ankurk91/vue-flatpickr-component/tree/8.x
