### ISSUE TITLE
data-toggle/toggle() doesn't work

### ISSUE THREAD

**Issue by grantholle** [ankurk91/vue-flatpickr-component#205]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.6
* Vue.js version : 2.6.12
* Browser name and version : Chrome 86.0.4240.111
* This package version : 8.1.6

**Current behavior**

Trying to use `data-toggle` or calling `$refs.[refname].fp.toggle()` doesn't toggle the input

**Expected behavior**

I should programatically toggle the component open/closed.

**Minimal reproduction of the problem with instructions**

The [example fiddle](https://jsfiddle.net/586whry3/4/) from #33 doesn't work anymore.

**Comment by ankurk91** [comment]
The `data-toggle` is working fine for me.

https://github.com/ankurk91/vue-flatpickr-component/blob/master/examples/App.vue#L55

The fiddle you have shared is using internal methods from flatpickr and may stop working anytime.

**Comment by grantholle** [comment]
Do you have a fiddle. [Here's a fork](https://jsfiddle.net/72ycx5tk/) of _your_ original fiddle. Using `data-toggle` doesn't work.

**Comment by grantholle** [comment]
> The fiddle you have shared is using internal methods from flatpickr and may stop working anytime.

What? This component just wraps flatpickr. Why/how would it stop working and the component still work?

**Comment by grantholle** [comment]
For whatever reason, order matters for the dom. I had my `<flat-pickr/>` nested in a div, not directly next to the button. Odd behavior, but I had to dig into the [docs](https://flatpickr.js.org/examples/#flatpickr-external-elements) more.

```html
<!-- doesn't work -->
<div>
  <div>
    <flat-pickr />
  </div>
  <button data-toggle></button>
</div>

<!-- works -->
<div>
  <flat-pickr />
  <button data-toggle></button>
</div>
```

**Comment by ankurk91** [comment]
I have updated the fiddle
https://jsfiddle.net/krhgws1c/

You were missing `wrap: true`

**Comment by ricky11** [comment]
interested to know how data-toggle is working under the hood, i searched the css file and couldn't find anywhere where toggle would make the component visible?

**Comment by ankurk91** [comment]
@ricky11 
https://github.com/flatpickr/flatpickr/blob/master/src/index.ts#L402
