### ISSUE TITLE
Getting custom events working

### ISSUE THREAD

**Issue by chrisgrim** [ankurk91/vue-flatpickr-component#206]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ x] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.6
* Vue.js version : 2.6.12
* Browser name and version : Chrome
* This package version : x.x.x

**Current behavior**
When I try to add a custom event nothing happens. My code is 
```html
<flat-pickr
                                    v-model="dates"
                                    :config="calendarConfig"
                                    ref="datePicker"                                              
                                    class="form-control"
                                    @on-Ready="showReady"
                                    :events="eventsToBeEmitted"
                                    placeholder="Select date"   
                                    name="dates" />
```
```

data() {
        return {
           eventsToBeEmitted : ['onReady']


    methods: {
              showReady() {
            console.log('test');
        },
```

**Expected behavior**
When the calendar loads I expect it to console 'test'. However the calendar loads with all of the dates and never triggers the method.

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
I could not re-produce it
https://jsfiddle.net/sq0hv9au/

I think there was typo in event name.
```diff
-@on-Ready="showReady"
+@on-ready="showReady"
```
