### ISSUE TITLE
 Error in callback for watcher "modelValue": "TypeError: Cannot read property 'value' of undefined" 

### ISSUE THREAD

**Issue by chrisgrim** [ankurk91/vue-flatpickr-component#207]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ x] Other, Issue after Updating
```

**Tell about your platform**
* flatPickr version : 4.6.6
* Vue.js version : 2.6.12
* Browser name and version : Chrome|
* This package version : 9.0.2

**Current behavior**
I just updated to laravel 8 and I am now getting an error 
```
vendor.js?id=08f2c156deb59cfef1ae:15436 [Vue warn]: Error in render: "TypeError: Object(...) is not a function"
found in
---> <FlatPickr>
Vue warn]: Error in mounted hook: "TypeError: Cannot convert undefined or null to object"
found in
---> <FlatPickr>
[Vue warn]: Error in callback for watcher "modelValue": "TypeError: Cannot read property 'value' of undefined"
found in
---> <FlatPickr>
```
This is strange because I don't remember even having a modelValue option before. If I try to add a modelValue

```
<flat-pickr
                    v-model="dates"
                    :modelValue="dates"
                    :config="config"                                                  
                    class="form-control"
                    ref="datePicker"             
                    name="dates" />
```
In the vue inspector I can see the date in modelValue but I still get the error.

**Expected behavior**
Worked normally before update

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-flatpickr-component#version-matrix
