### ISSUE TITLE
Unable to programmatically update v-model in mobile - native date picker

### ISSUE THREAD

**Issue by brandonwaring** [ankurk91/vue-flatpickr-component#208]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.6
* Vue.js version : 2.6.12
* Browser name and version : Chrome 87.0.4280.66 (mobile device) 
* vue-flatpickr-component version : 8.1.5

**Current behavior**
When invoking an update to the v-model value by changing the variable directly when a button is clicked, the model is updated and prints the new value correctly on the page `v-model: {{date}}`, but the value of the input is not changed. The input is read only and only shows the previous date. This works fine on desktop, the issue only happens when native date picker is used on a device. When using disableMobile: false, the flatpickr works fine in mobile.

**Expected behavior**
The date should be able to change by setting a new value on the model variable.

**Minimal reproduction of the problem with instructions**
After the flatpickr has mounted and I click a button that manually sets a new date `this.date = "2020-12-12"`, I see the `v-model: {{date}}` update on the page, but not the value on the input. 

If you use your example, with the config disableMobile set to false, you will recreate the issue when clicking the "Set new date" button.

**Comment by ankurk91** [comment]
Thanks for detailed explanation, will look into it

**Comment by brandonwaring** [comment]
> Thanks for detailed explanation, will look into it

Thanks for your time, and for adding this component.

I think I figured it out, or found a workaround at least. My solution was to grab the fp instance in my method and use the  setDate method right after setting the modelValue. When I just used setDate, it would fail the first time and then work the second time. I must be missing something or misunderstanding the order of whats happening behind the scenes. When adding both together it worked fine on a device and desktop.

Basically the goal I have is to add a drop down list as part of a form group that lets you pick the number of years from today that you want to set for a deadline, or set one manually using the date picker.

If you have any suggestions, please reply.

```
<template>
    <b-input-group>
        <flat-pickr
            :id="instance.id"
            :config="config"
            v-model="deadline"
            ref="datePickerWrap"
            class="form-control bg-white"
        ></flat-pickr>
        <b-input-group-append>
            <b-dropdown variant="secondary" right>
                <b-dropdown-item
                        v-for="num in milestones"
                        :key="`milestones-${num}`"
                        @click="injectDate(num)"
                    >
                        {{ num }}yr
                    </b-dropdown-item>
                </b-dropdown>
            </b-input-group-append>
        </b-input-group> 
    </b-form-group>
</template>

<script>
import flatPicker from 'vue-flatpickr-component'

export default {
    components: {
        flatPickr,
    },
    data() {
        return {
            config: {
                minDate: 'today',
                wrap: true,
                altInput: true,
                dateFormat: 'Y-m-d',
            },
            instance: {
                id: `deadline-${Date.now()}`,
            },
            deadline: new Date(),
            milestones: ['1', '3', '5', '10', '15', '20', '25', '30'],
        }
    },
    ...
    methods: {
        injectDate(num) {
            let newDate = ''
            ...
            this.deadline = newDate
            this.$refs.datePickerWrapper.fp.setDate(newDate, true, this.config.dateFormate)
</script>
```
