### ISSUE TITLE
Disable datetime range

### ISSUE THREAD

**Issue by lucianobosco** [ankurk91/vue-flatpickr-component#210]
**I'm submitting a ...**  (check one with "x")
```
[X ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 2.6.6
* Browser name and version : Chrome 87.0.4280.66 (Official Build) (64-bit)
* This package version : 8.1.6

**Current behavior**
When disabling a range by using the `disable` property, the first day is always enabled for all hours and the last day is always disabled, no matter the time selected. The dates in between are disabled as expected.

**Expected behavior**
The `from` and `to` datetimes should be validated against datetimes in `disable` array.

**Minimal reproduction of the problem with instructions**
I'm not sure if this is a bug or is not allowed at all.
By setting a `disable` property with below format, the first day is always enabled for all hours and the last day is always disabled :

```js
dateStartOpeningConfig: {
     altInput: true,
     altInputClass: 'form-control pl-0',
     altFormat: 'd/m/Y H:i',
     time_24hr: true,
     allowInput: true,
     locale: Spanish,
     wrap: true,
     clickOpens: false,
     enableTime: true,
     disable: [
          {
                from:'2020-12-05 21:00',
                to: '2020-12-06 08:00'
          }
     ]
,
```

**Comment by ankurk91** [comment]
Are you sure this issue not present in the plain js version?
https://github.com/flatpickr/flatpickr

**Comment by lucianobosco** [comment]
That's a good question. I will ask and keep you posted

**Comment by lucianobosco** [comment]
Hi, as per the package owner I need to add an extra plugin `minMaxTimePlugin`. I'm allowed to add plugins by using your component?
I'll appreciate it if you can point me in the right way to achieve this.

**Comment by ankurk91** [comment]
Yes, you can add this plugin.

You can check examples folder in this repo to see how you can add plugins.
