### ISSUE TITLE
Call stack size exceeded when using ignoredFocusElements

### ISSUE THREAD

**Issue by joel-ns** [ankurk91/vue-flatpickr-component#211]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.6
* Vue.js version : 2.6.12
* Browser name and version : Chrome 87.0.4280.88 and Firefox 83.0
* This package version : 8.1.6

**Current behavior**
Setting the config-property of this component with the ignoredFocusElements option to prevent closing the flatpickr by clicking outside can cause a the maximum call stack size to be exceeded. This, of course, prevents the flatpickr from functioning properly.

The ignoredFocusElements option is not documented on the flatpickr website, but it is an option that is recommended to be used by the flatpickr authors (see for example https://github.com/flatpickr/flatpickr/issues/1553).

This behaviour is caused by the way vue traverses through the config-object. Since the config watcher is set to watch for changes deep in the object graph (deep: true) this will make vue try to traverse through whatever you specifiy in the ignoredFocusElements option. This will cause the above mentioned stack error if there are circular references in the object.

**Expected behavior**
Setting the ignoredFocusElements option should not cause the maximum call stack size to be exceeded.

**Minimal reproduction of the problem with instructions**
https://jsfiddle.net/9a1ejdx0/

**Comment by ankurk91** [comment]
Here is the possible workaround for now.

```js
import flatpickr from "flatpickr

// Global settings
flatpickr.setDefaults({
    ignoredFocusElements: [document],
});

// Init your vue app here
```

**Comment by joel-ns** [comment]
Thanks, I'll try that for now.
