### ISSUE TITLE
Component throws errors "Object(...) is not a function" and "this.$refs.root is undefined"

### ISSUE THREAD

**Issue by StaticallyTypedRice** [ankurk91/vue-flatpickr-component#213]
When a flatpickr component with a `:model-value` attribute is used from a class component, the following errors are thrown:

    [Vue warn]: Error in render: "TypeError: Object(...) is not a function"
    
    found in
    
    ---> <FlatPickr>
          <PriceChecker> at src/main/webapp/app/core/price-checker/price-checker.vue
            <App> at src/main/webapp/app/app.vue
              <Root>

and:

    [Vue warn]: Error in mounted hook: "TypeError: this.$refs.root is undefined"
    
    found in
    
    ---> <FlatPickr>
           <PriceChecker> at src/main/webapp/app/core/price-checker/price-checker.vue
             <App> at src/main/webapp/app/app.vue
               <Root>

This is part of the code that caused the error:

The Vue template code:

    <flat-pickr
        class="form-control"
        :config="flatpickr"
        v-model="form.data.date"
        :model-value="form.data.date"
        name="date"
    />

The TypeScript code:

    @Component({
    components: { 'flat-pickr': flatpickr },
    })
    export default class ClassComponent extends Vue {

        public form = {
            data: {
                date: '2021-01-01',
                // ...
            },
            // ...
        };

        public flatpickr = {
            wrap: true,
            altFormat: 'M j, Y',
            altInput: true,
            dateFormat: 'Y-m-d',
        };

        // ...
    }

In this configuration, Vue says that a `:model-value` is required.

The `flatpickr` package version is 4.6.9 and the `vue-flatpickr-component` package version is 9.0.3.

**Comment by tony19** [comment]
This error occurs when a Vue 2 project uses the latest release of `vue-flatpickr-component` (9.x), which is intended for Vue 3 projects. To use the Vue 2 compatible version of the component, install 8.x:

```
npm install -S vue-flatpickr-component@8
```

reference: https://stackoverflow.com/questions/65543359/object-is-not-a-function-and-this-refs-root-is-undefined-when-using-vu

**Comment by StaticallyTypedRice** [comment]
> This error occurs when a Vue 2 project uses the latest release of `vue-flatpickr-component` (9.x), which is intended for Vue 3 projects. To use the Vue 2 compatible version of the component, install 8.x:
> 
> ```
> npm install -S vue-flatpickr-component@8
> ```
> 
> reference: https://stackoverflow.com/questions/65543359/object-is-not-a-function-and-this-refs-root-is-undefined-when-using-vu

Thanks!!
