### ISSUE TITLE
defaultDate in combination with enable option not working

### ISSUE THREAD

**Issue by treagod** [ankurk91/vue-flatpickr-component#215]
**I'm submitting a ...**  
```
[x] Bug report 
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.6
* Vue.js version : 3.0.0
* Browser name and version : Firefox 84.0.2
* This package version : 9.0.2

**Current behavior**
When I pass following config to the flatpickr component
```javascript
{
  defaultDate: new Date(),
  enable: [new Date()],
}
```
Only the current date will be enabled, which I want, but the default value will not be set.

**Expected behavior**
When I pass following config to the flatpickr component
```javascript
{
  defaultDate: new Date(),
  enable: [new Date()],
}
```
Only the current date is enabled and the current date is also preselected

**Minimal reproduction of the problem with instructions**
Pass following config to the flatpickr component

```javascript
{
  defaultDate: new Date(),
  enable: [new Date()],
}
```

**Comment by ankurk91** [comment]
I will check.

Make sure parent library does not have this issue

**Comment by ankurk91** [comment]
https://jsfiddle.net/cxp2n8r5/

the original flatpickr behaves the same, report it to that repo instead.
