### ISSUE TITLE
How to match core script with specific vue component version?

### ISSUE THREAD

**Issue by vitality82** [ankurk91/vue-flatpickr-component#216]
I still have a number of users on IE11 ( people in corporate environments ) and since this component has dropped support for IE11 the latest version I can use is: 8.1.6

Do you which version of the core flatpickr script should be used with 8.1.6?

Thanks

**Comment by ankurk91** [comment]
You can compile the source.
just importffrom 'src` folder.
or
You can use polyfil.

Btw, The latest version`9` does not workwwith vue 2.x.


You musthhave ffilled iissue ttemplate

**Comment by vitality82** [comment]
Thanks! I'll keep that formatting in mind
