### ISSUE TITLE
Flatpickr with vue js vee-validate need help

### ISSUE THREAD

**Issue by devlloedy** [ankurk91/vue-flatpickr-component#217]
Hi! How can i validate dates using vee-validate ? thanks

**Comment by ankurk91** [comment]
It should work.

What is your vue.js version ?

**Comment by ankurk91** [comment]
It is upto you, how you configure it.
I have shared an example below 

https://codesandbox.io/s/custom-text-input-with-vee-validate-v4-forked-el6vx?file=/src/components/TextInput.vue
