### ISSUE TITLE
ReferenceError: Cannot access 't' before initialization in minified js

### ISSUE THREAD

**Issue by Tharavink** [ankurk91/vue-flatpickr-component#218]
**I am using Laravel framework with Vue front-end**

The flatpickr works perfectly when I compile my js script using
```
npm run dev
```

However, having issue when I compile in production mode
```
npm run production
```

**Platform**
* Vue.js version : 2.6.11
* Browser name and version : Chrome 88.0.4324.150
* Node version : 12.16.0
* Npm version : 6.14.9
* This package version : 8.1.6

**Current behavior**
After compiling assets with
```
npm run production
```
and open the website, chrome debug console shows following error
```
ReferenceError: Cannot access 't' before initialization
    at H (app.js:1)
    at z (app.js:1)
    at U (app.js:1)
    at app.js:1
    at app.js:1
    at E (app.js:1)
    at T (app.js:1)
    at new A (app.js:1)
    at o.mounted (app.js:1)
    at He (app.js:1)
```
The flatpickr is not working when this happens.

**Expected behavior**
Flatpickr to work same as how it works when compiled using
```
npm run dev
```

**Minimal reproduction of the problem with instructions**
1. Install the package in the project
2. Run **npm run production**
3. Open the website
4. The error will be shown in debug console

**Comment by ankurk91** [comment]
i can not help unless you share minimal piece of code, it looks like this issue is specific to your build system

**Comment by ankurk91** [comment]
You said that

> I am using vue 2.9.6

But this is not valid vue version


I will try this with Vue cli tomorrow, will post back here

**Comment by Tharavink** [comment]
Im sorry, my vue version is 2.5.2

**Comment by ankurk91** [comment]
i was able to reproduce it with
```
vue cli v2.9.6
```

https://github.com/webpack/webpack/issues/9173

**Comment by parth-ka-patel** [comment]
@ankurk91 
I am facing same issue in my project here, is my project error after using `npm run prod` 
**: Cannot access 't' before initialization**
so please give me a solution for that

**Comment by Tharavink** [comment]
I think this is Flatpickr issue. When I tried to use JQuery version of Flatpikr, I still faced the issue.
