### ISSUE TITLE
[8.x] Error initialising component

### ISSUE THREAD

**Issue by admxxi** [ankurk91/vue-flatpickr-component#222]
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```
Environment:
* flatPickr version : 4.6.9
* Vue.js version : 2.6.12
* Browser name and version : Chrome 89.0.4389.82
* This package version : 8.1.6

**Current behavior**
Once component loads, inputs keep disabled and some console errors shows up.
ReferenceError: Cannot access 'e' before initialization
TypeError: Cannot read property 'addEventListener' of undefined
<img width="610" alt="Screenshot 2021-03-15 at 15 36 00" src="https://user-images.githubusercontent.com/10850289/111179623-295ca400-85a4-11eb-978c-9bab00ede125.png">

**Expected behavior**
Having the input enabled to be able to pick a date.

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Hey, i will try to re-produce it, meanwhile can u try to re-produce the issue here

https://codesandbox.io/s/optimistic-currying-ie4ro?file=/src/components/HelloWorld.vue

**Comment by Muffinman** [comment]
I'm also getting this on one of my older projects when compiling webpack in production mode. When in dev mode it seems to work correctly.

**Comment by ankurk91** [comment]
Please share a minimal reproduction.

**Comment by Muffinman** [comment]
It's hard to unpick this from the rest of the project at the moment, but I've tracked at least one of the errors down to this section of code in `dist/esm/index.js`

```js
    function buildMonthSwitch() {
        if (self.config.showMonths > 1 ||
            self.config.monthSelectorType !== "dropdown")
            return;
        const shouldBuildMonth = function (month) {
            if (self.config.minDate !== undefined &&
                self.currentYear === self.config.minDate.getFullYear() &&
                month < self.config.minDate.getMonth()) {
                return false;
            }
            return !(self.config.maxDate !== undefined &&
                self.currentYear === self.config.maxDate.getFullYear() &&
                month > self.config.maxDate.getMonth());
        };
        self.monthsDropdownContainer.tabIndex = -1;
        self.monthsDropdownContainer.innerHTML = "";
        for (let i = 0; i < 12; i++) {
            if (!shouldBuildMonth(i))
                continue;
            const month = createElement("option", "flatpickr-monthDropdown-month");
            month.value = new Date(self.currentYear, i).getMonth().toString();
            month.textContent = monthToStr(i, self.config.shorthandCurrentMonth, self.l10n);
            month.tabIndex = -1;
            if (self.currentMonth === i) {
                month.selected = true;
            }
            self.monthsDropdownContainer.appendChild(month);
        }
    }
```

After Webpack has done it's magic this becomes:

```
            function z() {
                if (n.config.showMonths > 1 || "dropdown" !== n.config.monthSelectorType)
                    return;
                n.monthsDropdownContainer.tabIndex = -1,
                n.monthsDropdownContainer.innerHTML = "";
                for (let e = 0; e < 12; e++) {
                    if (t = e,
                    void 0 !== n.config.minDate && n.currentYear === n.config.minDate.getFullYear() && t < n.config.minDate.getMonth() || void 0 !== n.config.maxDate && n.currentYear === n.config.maxDate.getFullYear() && t > n.config.maxDate.getMonth())
                        continue;
                    const t = f("option", "flatpickr-monthDropdown-month");
                    t.value = new Date(n.currentYear,e).getMonth().toString(),
                    t.textContent = g(e, n.config.shorthandCurrentMonth, n.l10n),
                    t.tabIndex = -1,
                    n.currentMonth === e && (t.selected = !0),
                    n.monthsDropdownContainer.appendChild(t)
                }
                var e
            }
```

And it's the `if (t = e,` line that's throwing the error.

It looks like a Webpack issue to me, but I don't know enough about how that works to suggest a fix.

I'm using `laravel-mix@1.7.2` and that includes webpack `^3.5` and babel-core `^6.25.1`.

Obviously these are very old versions, but this project has no budget to upgrade everything to the latest (as I'd like). I'm hoping there's some `.babelrc` preset I can use which may get around this?

**Comment by ankurk91** [comment]
@Muffinman

The piece of code you have shard above, belongs to the parent library.
https://github.com/flatpickr/flatpickr

This vue component is a just a wrapper around this library.
You can report your issue there.

### A few hints to solve the issue: 
* babel and terser-js is doing something behind the scenes which is hard to understand since i dont have access to your project and dont have time to debug
* You can try to load the flatpicker form cdn
```
https://cdn.jsdelivr.net/npm/flatpickr@4
```
* When loading flatpickr from cdn, you can instruct webpack not to include flatpickr from `node_modules` at all.
* https://webpack.js.org/configuration/externals/

```js
  externals: {
    'flatpickr': 'flatpickr'
  },
```
This way webpack will not bundle the library in your dist, and will rely on flatpickr loaded from cdn.

Hope it helps. :)

**Comment by Muffinman** [comment]
Hi @ankurk91 

Splitting the `flatpickr` library out and using the CDN is a good solution for us, I've just tested this and it works great.

Many thanks for your help with this, I know this wasn't an issue with your package!

**Comment by syphon1c** [comment]
Hey there,

I seem to be experiencing the exact same issue, havent quiet yet figured out how to load the flatpickr component via cdn, when loading from externals in webpack I get an error 'flatpickr is not defined'. Will poke some more at it (:

**Comment by ankurk91** [comment]
You can load both libraries from cdn, see js-fiddle.

https://jsfiddle.net/ankurk91/63kzdwLx/

**Comment by jeroendewilde** [comment]
I also have the issue when compiling Webpack in production mode.

@Muffinman @ankurk91 Any news on this yet? If the issue belongs to the parent library, do the creators of [flatPickr](https://github.com/flatpickr/flatpickr) know about this?

**Comment by ankurk91** [comment]
I never faced this issue in my own projects.
I am also using webpack 5

**Comment by jeroendewilde** [comment]
Apparently I'm not the only ones facing this issue.
