### ISSUE TITLE
ReferenceError: Cannot access 'e' before initialization

### ISSUE THREAD

**Issue by bonis955** [ankurk91/vue-flatpickr-component#225]
## Describe the bug
when I use yarn dev to compile while development Flatpickr is working fine but when compile the whole application to deploy it on the server it gives the following error in the console

![Screenshot from 2021-05-13 13-12-20](https://user-images.githubusercontent.com/47026176/118118306-0a845d80-b3ed-11eb-91cb-e2fdac5494b2.png)

## Version
"vue-flatpickr-component": "^8.1.6"
"vue": "^2.5.17",

## Test Environment
Linux, Vue

**Comment by ankurk91** [comment]
Please share a minimal reproduction, above was not helpful

**Comment by bonis955** [comment]
What info do you need?

**Comment by ankurk91** [comment]
I don't have access to your tooling (webpack), it could be a browser issue as well.

Are you  using laravel mix, which version?

Can you try to make a production build on your local machine and check for same error.

> What info do you need?

Just place yourself into my place and see what would i need to re-produce the issue:)

**Comment by bonis955** [comment]
sorry i found other post that describe this bug, this wasn't an issue with your package

I close this issue, i try to follow your advice in that post

thanks for all
