### ISSUE TITLE
Inconsistency in allowInput

### ISSUE THREAD

**Issue by baaskoen** [ankurk91/vue-flatpickr-component#228]
**I'm submitting a ...**
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Current behavior**
Let's assume you have 2 inputs, one has time disabled, and one has time enabled:

Input 1: `1995-08-23`
Input 2: `1995-08-23 16:00`

If you click on input 1, and change the day 23 to 24 (by typing in the input), click away from the input and the new value will be:
`1995-08-24`
This happens too when you press tab and enter instead of clicking away.

If you click on input 2, and change 16:00 to 16:05 (by typing in the input), click away from the input and the new value will be:
`1995-08-23 16:00`
When you press tab or enter instead of clicking, the value will actually change to `1995-08-23 16:05`

**Expected behavior**
Either make it consistent so both fields will reset upon clicking away, or make both fields change the actual value when clicking away (I think this is the preferred way).

If this is not possible, please explain how you can control the value before events are emitted (perhaps via a blur event)

**Minimal reproduction of the problem with instructions**
vue-flatpickr-component": "^8"

```js
const config = {
      altInput: true,
      allowInput: true,
      altInputClass: 'dateTimePicker',
      dateFormat: 'Y-m-d H:i',
      altFormat: this.dateTimeMask.short,
      enableTime: true,
      time_24hr: this.time_24hr,
      defaultHour: 0,
      defaultMinute: 0
    }
```

**Comment by Jhawins** [comment]
+ 1

**Comment by ankurk91** [comment]
The vue-flatpickr-component was not made to keep 2 input fields in sync, it has to be handled in userland.
