### ISSUE TITLE
Any chance of supporting plugins?

### ISSUE THREAD

**Issue by humblecoder** [ankurk91/vue-flatpickr-component#23]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 3.0.0
* Vue.js version : 2.4.2
* Browser name and version : Chrome|Firefox|Safari [ALL]
* This package version : x.x.x

**Current behavior**
Adding ```"plugins": [new confirmDatePlugin({})]``` to "config" results in error: ```ReferenceError: confirmDatePlugin is not defined```

**Expected behavior**
Need support for plugins in general -- specifically ```"plugins": [new confirmDatePlugin({})]```

**Minimal reproduction of the problem with instructions**
(see current behavior)

**Comment by ankurk91** [comment]
@humblecoder

Plugin support is already there.
Did you imported the plugin file ?
See example ->
https://github.com/ankurk91/vue-flatpickr-component/blob/2581aa6305db879626d0c55be77323b07075555e/examples/App.vue#L192-L193

**Comment by humblecoder** [comment]
*facepalm*

Case sensitive issue.  Apologies.  Appreciate the response.
