### ISSUE TITLE
How to get FlatPicker Date Range onChange selectedDates array as return?

### ISSUE THREAD

**Issue by consciousnessdev** [ankurk91/vue-flatpickr-component#231]
**I'm submitting a **
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[X] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.9
* Vue.js version : 2.6
* Browser name and version : Chrome
* This package version : 8.1.6

**Current behavior**
Flatpickr set as date range, when pick range it return 'start date to end date', ex: "2021-07-01 to 2021-07-04"

**Expected behavior**
I Expect output get from selectedDates value on onChanges Hooks, which is an array value : ["2021-07-01", "2021-07-04"]

This is my flatpickr calendar config
```
calendarConfig: {
    mode: 'range',
    dateFormat: 'Y-m-d',
    wrap: true,
    // eslint-disable-next-line
    onChange: function(selectedDates) {
    return selectedDates.map(date => dayjs(date).format('YYYY-MM-DD'))
  },
},
```

**Comment by ankurk91** [comment]
I could not get what you are trying to achieve

**Comment by consciousnessdev** [comment]
So, when i use flatpickr range calendar, i get output when choosing range date like this 
```
2021-07-01 to 2021-07-04
```

On official documentation section Event & Hooks (https://flatpickr.js.org/events/), flatpickr can use onChange hooks, which is contain 3 data : selectedDates, dateStr & instance

Default output is use dateStr (example: 2021-07-01 to 2021-07-04)
i want get output from selectedDate, which is output like this ["2021-07-01", "2021-07-04"]

**Comment by ankurk91** [comment]
The v-model value will always be string.

If you a different format, you can use hooks. 

If you are unable to use hooks. I can not help you. 
Search for previous issues with you are not alone.

**Comment by quantumwebco** [comment]
@ankurk91 I would really like to be able to return the selectedDates property too, without the need for explicitly listening to the onChange event and setting it manually in the callback

If I did a PR to add a config option to set the model value, i.e. selectedDates or dateStr would you accept?

**Comment by ankurk91** [comment]
v-model will always be a string .

If it was easy i would have done it in 1st version
