### ISSUE TITLE
Date  change to date today when updating the time

### ISSUE THREAD

**Issue by leahfkd** [ankurk91/vue-flatpickr-component#232]
**I'm submitting a ...**
```
[x ] Bug report 
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 3.x

**Current behavior**
I have 2 flat-picker initialized, one shows only the date (option is no time picker), and the other one just the time.(option is noCalendar)
Both have the same v-model.

If I change the time using manual input, once the clock picker is closed, the date also changed with the date today.

**Expected behavior**
If I change the time using the 2nd flat-picker via manual field input, the time value should change, but the date should retain.

**Minimal reproduction of the problem with instructions**

Here's a working sample https://jsfiddle.net/npryhqvx/1/

**Comment by ankurk91** [comment]
Thanks for sharing a re-production url.

But,
I dont think it is related the vue component, you should report it to the parent repo instead.
This is the intended behavior.
Flatpickr was never made to work like this (two picker, same model)

https://github.com/flatpickr/flatpickr
