### ISSUE TITLE
Error on change

### ISSUE THREAD

**Issue by DanielDebreczeniDesktop** [ankurk91/vue-flatpickr-component#235]
### Discussed in https://github.com/ankurk91/vue-flatpickr-component/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **DanielDebreczeniDesktop** August 16, 2021</sup>
I got error message on change in console:

![Képkivágás](https://user-images.githubusercontent.com/64101693/129546597-223781a7-4d7c-43d9-958b-f31bd4750d44.JPG)

The code is the following:
![Képkivágáss](https://user-images.githubusercontent.com/64101693/129546763-8df943ac-e114-409a-9201-f44b1bc4990b.JPG)

This error showing somewhere else, but annoying if i have no other console error in my application.
Has somebody idea to solve it?

Thanks</div>

**Comment by ankurk91** [comment]
This piece of code does not belong to this component.
