### ISSUE TITLE
method value change 

### ISSUE THREAD

**Issue by TUCA33** [ankurk91/vue-flatpickr-component#239]
**I'm submitting a ...**  (check one with "x")
```
[x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 8.1.7
* Vue.js version : 2.6.12
* Browser name and version : Chrome|Firefox|Edge  CHROME 92.0.4515.15
* This package version : x.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

hello, I'm using "flatPickr" with vuejs, everything works fine at first and today's date is written on the input from the start.
When I want to add a date to the value value with the method alone, the date does not change in any way.
As far as I understand it doesn't change after "flatPickr" runs unless you manually change the date. It is not treated as a method in any way. When I say "Chrome Inspect" I can see that the value has changed, but the preview still has the same date. What should I do for it ?
[vue-flatpickr-component](https://github.com/ankurk91/vue-flatpickr-component)
```vue
<template>
  <div>
    <div class="btn-group">
      <button @click="getDate(1)" class="btn">TODAY</button>
      <button @click="getDate(7)" class="btn">7 DAY</button>
      <button @click="getDate(14)" class="btn">14 DAY</button>
      <button @click="getDate(30)" class="btn">30 DAY</button>
      <button @click="getDate(45)" class="btn">45 DAY</button>
      <button @click="getDate(60)" class="btn">60 DAY</button>
    </div>
    <div>
      <input-date v-model="data.date"></input-date>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      data: {
        date: "",
      },
    };
  },
  methods: {
    getDate(days) {
      const now = new Date();
            const tmpDate = now.setDate(now.getDate() + day);
            const newDate = new Date(tmpDate);
            const days = newDate.toISOString().slice(8, 10)
            const mounth = newDate.toISOString().slice(5, 7)
            const years = newDate.toISOString().slice(0, 4)
            this.data.date= days + '.' + mounth + '.' + years
    },
  },
};
</script>
```

```
<template>
    <flat-pickr
        v-model="date"
        :config="config"
        class="form-control"
        placeholder="Select date"
        name="date">
    </flat-pickr>
</template>

<script>
import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
import {Turkish} from 'flatpickr/dist/l10n/tr.js';

export default {
    name: 'yourComponent',
    data() {
        return {
            date: new Date(),
            config: {
                altInput: false,
                dateFormat: "d.m.Y",
                allowInput: true,
                locale: Turkish,
            },
        }
    },
    components: {
        flatPickr
    },
}
</script>
```

**Comment by ankurk91** [comment]
Fill up the issue template.
Explain the expected vs buggy bahaviour.
Share a minimal reproduction with steps

**Comment by TUCA33** [comment]
I edited the question

**Comment by TUCA33** [comment]
I also noticed a while ago. When I post the transaction, the value is sent null.

**Comment by ankurk91** [comment]
Please create a codesandbox.io/

Help me run your code

**Comment by TUCA33** [comment]
https://codesandbox.io/s/vue-flatpickr-demo-forked-0ifcv?file=/src/App.vue

here you go

**Comment by ankurk91** [comment]
https://codesandbox.io/s/vue-flatpickr-demo-forked-5s919?file=/src/App.vue

This is how you do it. You were doing it wrong.

Please learn vue.js, specially v-model.

Tip: Dont ask a package maintainer to teach you Vue.js

**Comment by TUCA33** [comment]
ok but I want to work with a separate component instead of using it this way, it still doesn't accept.

**Comment by ankurk91** [comment]
Thats why i asked you to learn about `v-model`, i am sorry but i am not your teacher on Github.
