### ISSUE TITLE
Can't retrieving the flatpickr instance

### ISSUE THREAD

**Issue by dennisbrandenberger** [ankurk91/vue-flatpickr-component#24]
Inside a .vue file:

In my script i import flatpickr:
```
import flatPickr from 'vue-flatpickr-component';
```

in my template I have:
```
<input type="text" id="myID" />
```

and then I try to get the instance like this in a mounted() hook:
```
    mounted () {
      const fp = flatPickr('#myID', {})
    }
```

Then in the console I get something like:
```
[Vue warn]: Error in mounted hook: "TypeError: __WEBPACK_IMPORTED_MODULE_1_vue_flatpickr_component___default(...) is not a function"
```

Obviously the component is not meant to work the same way as the chmln/flatpickr - but then how to I get the instance ?

**Comment by ankurk91** [comment]
You need to use ref,
```html
<flatpickr ref="date" v-model"date"/>
```
Then in mounted hook
```js
// fp in the instance
this.$refs.date.fp

```
