### ISSUE TITLE
Enable Date Option is Missing in Config

### ISSUE THREAD

**Issue by zahidhasanemon** [ankurk91/vue-flatpickr-component#240]
I am using 

* Vue.js version : 2.6.12
* This package version : 8.1.6

**Current behavior**
I am trying to set [enable](https://flatpickr.js.org/examples/#disabling-all-dates-except-select-few) dates. but this is not working.
`<flat-pickr
                            id="h-start"
                            ref="datePicker"
                            v-model="start"
                            class="form-control flat-pickr-group"
                            :config="{ wrap: true, enableTime: false, dateFormat: 'd/m/Y', enable: enabledDates }"
                          />` 
and my enable dates is 
`enabledDates = [
          {
            from: '2021-09-29',
            to: '2021-09-30',
          },
        ]`
but this enables January 20 instead of September 29 and 30

 
![current behave 1](https://user-images.githubusercontent.com/23102888/133769697-17d60f4f-586d-4843-b398-3572856f9ec2.jpg)
![current behave 2](https://user-images.githubusercontent.com/23102888/133769747-51e4c3c2-3f6f-485a-b8a9-55aa6c0c9491.jpg)

So I further inspects and console the component
`console.log(this.$refs.datePicker.fp)`
and found config enable option is missing
![flatpickr](https://user-images.githubusercontent.com/23102888/133770221-8fcd339d-5fc5-412e-a379-470ba6cc4389.jpg)
Is this intentional? A version update can fix this? What is the possible solution?

**Comment by ankurk91** [comment]
please share a re-production with minimal steps

**Comment by zahidhasanemon** [comment]
[this ](https://jsfiddle.net/L04tqngr/) is the js fiddle of the thing i am talking about.

**Comment by zahidhasanemon** [comment]
if i want to set the dates dynamically in beforeMount hook
`const enable = [
          {
            from: this.event.startDate,
            to: this.event.endDate,
          },
        ]
        this.flatPickrConfig.enable = enable`
this only enables september 30 where this.event.startDate is sep 29 and this.event.endDate is sep 30
![dynamic issue](https://user-images.githubusercontent.com/23102888/133777426-e9ecb1fe-3b3d-4769-81cc-ee454047f883.jpg)
.

**Comment by ankurk91** [comment]
Your js fiddle is using vue V3,but issue template mentioned v2.

**Comment by zahidhasanemon** [comment]
The behavior is same in both vue 2 and vue 3. however this resolves if I use config as a property as whole
`<flat-pickr id="h-start" ref="datePicker" v-model="start" class="form-control flat-pickr-group" :config="flatPickrConfig" />`

data property 
`flatPickrConfig: { wrap: true, enableTime: false, dateFormat: 'd/m/Y', enable: [], },`
but when I use axios request to fetch data in beforeMount hook like
```
beforeMount() {
    this.$http.get(`front-end/events/${this.$route.params.slug}/show`)
      .then(response => {
        this.event = response.data.event || {}
        console.log(response.data.event.startDate) // prints 2021-09-29T00:00:00.000Z
        console.log(response.data.event.endDate) // prints 2021-09-30T00:00:00.000Z 
        this.start = this.dateFormat(this.event.startDate)
        const enable = [
          {
            from: response.data.event.startDate,
            to: response.data.event.endDate,
          },
        ]
        this.flatPickrConfig.enable = enable
      })
  },
```
I am expecting to get 29 and 30 September to be enabled but getting only September 30 enabled. What may be the possible issue here??

**Comment by ankurk91** [comment]
Please use config as property, and for the dates are not correct issue, report to parent repository

**Comment by zahidhasanemon** [comment]
this is somehow related to the date format issue. If I use date in YYYY-MM-DD format this does not work but if I use DD/MM/YYYY format, this works.
