### ISSUE TITLE
Cannot get month view example working

### ISSUE THREAD

**Issue by cberthiaume** [ankurk91/vue-flatpickr-component#241]
**I'm submitting a ...**  (check one with "x")
```
[X] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : ?
* Vue.js version : 3.2.20
* Browser name and version : Firefox
* This package version : 9.0.5

**Current behavior**
The month picker is displayed but the styling is not correct as compared to the examples [here](https://ankurk91.github.io/vue-flatpickr-component/). A similar issue was reported in issue [191](https://github.com/ankurk91/vue-flatpickr-component/issues/191).

<img width="389" alt="image" src="https://user-images.githubusercontent.com/27117141/137042844-49c237a0-1c45-4745-a93d-0073a4fc0f16.png">

**Expected behavior**
<img width="353" alt="image" src="https://user-images.githubusercontent.com/27117141/137042867-fd0f1207-aaf0-4525-8451-d8ebe56accf9.png">

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/stupefied-pine-hcr4g?file=/src/main.js

**Comment by cberthiaume** [comment]
Thanks. That would be helpful to have in the documentation.

**Comment by ankurk91** [comment]
https://flatpickr.js.org/plugins/
