### ISSUE TITLE
[vue-3] Uncaught TypeError: Cannot read properties of undefined (reading 'defaultConfig')

### ISSUE THREAD

**Issue by amchconsult** [ankurk91/vue-flatpickr-component#244]
Hi,
Using Vue3 as CDN.

```html
<flat-pickr v-model="birthdate" :config="{ dateFormat: 'Y-m-d', allowInput: false, altInput: true, altFormat: 'm/d/Y', disableMobile: 'true',}" class="form-control form-control-sm bg-white"></flat-pickr>
```

```
[Vue warn]: Unhandled error during execution of mounted hook 
  at <FlatPickr modelValue=null onUpdate:modelValue=fn<onUpdate:modelValue> config= {dateFormat: 'Y-m-d', allowInput: false, altInput: true, altFormat: 'm/d/Y', disableMobile: 'true'}  ... > 
  at <App>
warn$1 @ vue.global.js:8035
logError @ vue.global.js:8209
handleError @ vue.global.js:8201
callWithErrorHandling @ vue.global.js:8155
callWithAsyncErrorHandling @ vue.global.js:8161
hook.__weh.hook.__weh @ vue.global.js:3475
flushPostFlushCbs @ vue.global.js:8347
render @ vue.global.js:6393
mount @ vue.global.js:4673
app.mount @ vue.global.js:10619
(anonymous) @ index-1.html:91

vue.global.js:8215 Uncaught TypeError: Cannot read properties of undefined (reading 'defaultConfig')
    at vue-flatpickr.js:196
    at Array.forEach (<anonymous>)
    at Proxy.mounted (vue-flatpickr.js:194)
    at callWithErrorHandling (vue.global.js:8152)
    at callWithAsyncErrorHandling (vue.global.js:8161)
    at Array.hook.__weh.hook.__weh (vue.global.js:3475)
    at flushPostFlushCbs (vue.global.js:8347)
    at render (vue.global.js:6393)
    at mount (vue.global.js:4673)
    at Object.app.mount (vue.global.js:10619)
(anonymous) @ vue-flatpickr.js:196
mounted @ vue-flatpickr.js:194
callWithErrorHandling @ vue.global.js:8152
callWithAsyncErrorHandling @ vue.global.js:8161
hook.__weh.hook.__weh @ vue.global.js:3475
flushPostFlushCbs @ vue.global.js:8347
render @ vue.global.js:6393
mount @ vue.global.js:4673
app.mount @ vue.global.js:10619
(anonymous) @ index-1.html:91
```
Thank you

**Comment by ankurk91** [comment]
Please share a minimal reproduction, to replicate the issue

**Comment by ankurk91** [comment]
And fill out the issue template

**Comment by amchconsult** [comment]
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>VUE 3 TEST 1</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="public/assets/flatpickr-4.6.9/flatpickr.min.css" rel="stylesheet">
</head>
<body>

<style>
    
</style>

<div id="app">
    <div class="container mt-4">
        
        <div class="col-6 col-md-4 col-lg-4">
            <label class="form-label-sm">Date of Birth</label>
            <flat-pickr v-model="birthdate" :config="{ dateFormat: 'Y-m-d', allowInput: false, altInput: true, altFormat: 'm/d/Y', disableMobile: 'true',}" class="form-control form-control-sm bg-white"></flat-pickr>
        </div>

    </div>
</div>

<script src="public/assets/flatpickr-4.6.9/flatpickr.min.js"></script>

<script src="public/assets/vue-flatpickr-component-9.0.5/dist/vue-flatpickr.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script>
    var vm = Vue.createApp({
        components: {
            FlatPickr: VueFlatpickr
        },
        data(){
            return {
                birthdate:null,
            }
        },
    })
    .mount('#app')
</script>

</body>
</html>
    `

**Comment by ankurk91** [comment]
Your given example is in-complete, i was unable to re-produce the issue. 
See my example in action here
https://jsfiddle.net/ankurk91/63kzdwLx/3148/

**Comment by amchconsult** [comment]
Thank you for your help. I got it working now.
