### ISSUE TITLE
[Feature request] Using a custom input

### ISSUE THREAD

**Issue by mrOrlando** [ankurk91/vue-flatpickr-component#246]
**I'm submitting a feature request** 

**Tell about your platform**

* flatPickr version : 4.6.9
* Vue.js version : 2.6.11
* Browser name and version : Chrome 97.0.4692.99
* This package version : 8.1.7

**Current behavior**

It is not possible to use a custom component for the input field. For example from Vuetify.

**Expected behavior**

it is possible to use a custom component for the input field

**Minimal reproduction of the problem with instructions**

I would like to pass the component I need through the slot and get the values and events I need
```
<flat-pickr v-model="date" :config="config">
  <template #input="{ props, events }">
    <my-custom-input v-bind="props" v-on="events" />
  </template>
</flat-pickr>
```
for example, how is it done in [vue2-datepicker](https://github.com/mengxiong10/vue2-datepicker/blob/master/src/date-picker.js#L469)

**Comment by ankurk91** [comment]
I never used vuetify. 

This component has a minimal HTML,
https://github.com/ankurk91/vue-flatpickr-component/blob/ac10e6504dbcb8af5c6d1ff382995aa74197d9cf/src/component.js#L14

You can extend the component and override the render function.
