### ISSUE TITLE
How to use rangePlugin in vue3

### ISSUE THREAD

**Issue by blackawn** [ankurk91/vue-flatpickr-component#247]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 4.x.x
* Vue.js version : 3.2.25
* Browser name and version :  Edge 97.0.1072.76
* This package version : 9.0.5

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

How to operate on rendered nodes? 
For example I want to render as 
`<input .../> <span>to<span> <input .../>`

**Vue template**
```html
<flat-pickr
    v-model="date"
    :config="config"
    placeholder="select date"
    class="form-control"
    name="date"
/>
```
**Setup**
```js
let config = reactive({
  plugins: [new rangePlugin({}),],
})
```
**Render result**
```html
<input type="text" data-input="true" placeholder="select date" class="form-control flatpickr-input" name="date" readonly="readonly">
<input type="text" data-input="true" placeholder="select date" class="form-control flatpickr-input" name="date" readonly="readonly" data-fp-omit="">
```

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-flatpickr-component/issues/64
