### ISSUE TITLE
Allow Time Change

### ISSUE THREAD

**Issue by u7540936** [ankurk91/vue-flatpickr-component#250]
Currently, the "time input fields" do not accept keyboard typing, only clicking on the arrows. Can someone please add an option like "AllowTimeInput"? It works on the flatpickr official docs (website) but not for Vue3 components.

**Comment by ankurk91** [comment]
https://github.com/flatpickr/flatpickr

Report it here

**Comment by tiagocarvalhomk** [comment]
Hello

Any news about that situation?
