### ISSUE TITLE
Limit Flatpickr version to 4.6.9. because it introduces a bug.

### ISSUE THREAD

**Issue by blazpavlica** [ankurk91/vue-flatpickr-component#252]
**I'm submitting a Feature request**  

**Tell about your platform**

* flatPickr version : 4.6.10
* Vue.js version : 3.2.31
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 9.0.5

**Current behavior**
Flatpickr version 4.6.10 introduced several bugs:
https://github.com/flatpickr/flatpickr/issues/2647
https://github.com/flatpickr/flatpickr/issues/2645
https://github.com/flatpickr/flatpickr/issues/2651

**Expected behavior**
The Flatpickr version number should be limited to 4.6.9. to avoid propagating the bug to this repo.

**Comment by francescocatalano** [comment]
+1

**Comment by ankurk91** [comment]
You can install specific version of flatpickr as a root level dependency and your webpack (or similar) should pick your version instead.

**Comment by Leogio360** [comment]
> You can install specific version of flatpickr as a root level dependency and your webpack (or similar) should pick your version instead.

Not a great idea.

@blazpavlica 
As a quix fix I recommend to add to your package.json this property (only for NPM >= 8)
  "overrides": {
    "vue-flatpickr-component": {
      "flatpickr": "4.6.9"
    }
  }
