### ISSUE TITLE
Throwing TypeError while binding async data for v-model 

### ISSUE THREAD

**Issue by sachinkumar121** [ankurk91/vue-flatpickr-component#253]
**I'm submitting a Bug Report**

**Tell about your platform**

* flatPickr version : 4.6.11
* Vue.js version : 3.2.31
* Browser name and version : Chrome 99.0.4844.84
* This package version : 9.0.5

**Current behavior**
I was working on Vue 3 application where I am using your package to input the time value only. The data is null at the initial level, and the data is fulfilled after fetch is called(for a demo I use setTimeout)

But it returns the error 

> TypeError: Cannot set properties of undefined (setting 'tabIndex')at buildMonthSwitch 

**Expected behavior**
It should render the flatpickr when the data is available.

**Minimal reproduction of the problem with instructions**
*STEPS TO REPRODUCE*

- create a demo vue.js application with the following content

**_FlatPickerTest.vue_**

```vue
<template>
  <div>
        Demo Time: {{demoTime}}
        <flat-pickr 
            v-model="demoTime" 
            :config="time_picker_config" 
            placeholder="Start Time" />
  </div>
</template>
<script>
import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
export default {
    name: 'FlatPickerTest',
    components:{
        flatPickr
    },
    data () {
        return {
            demoTime: null,
            time_picker_config: {
                altInput: true,
                noCalendar: true,
                enableTime: true, 
            },
        }
    },
    created() {
        let that = this;
        // here we call the api which will set the demoTime data.
        setTimeout(() => {
            that.demoTime = 1613376000000;
        }, 2000)
    },
}
</script>
```

**_main.js_**

```js
import { createApp } from 'vue'
import FlatPickerTest from './FlatPickerTest.vue'

createApp(FlatPickerTest).mount('#app')
```

**Comment by ankurk91** [comment]
Please create a codesandbox to re-produce this issue.

https://codesandbox.io/s/vue-3

The error message indicates that error is coming from flatpickr itself, not from this vue-component

**Comment by sachinkumar121** [comment]
Ok. I am looking for the best testing environment for you to test the package. BTW The link you shared is not working(i.e didn't render the vue 3 application).

**Comment by ankurk91** [comment]
You can use https://jsfiddle.net/

**Comment by ankurk91** [comment]
https://github.com/flatpickr/flatpickr/issues/2367

**Comment by ankurk91** [comment]
I could not re-produce the issue in code sandbox,

https://codesandbox.io/s/flatpickr-in-vue-js-v3-forked-v0i42b?file=/src/Datepicker.vue

I used your configs.
