### ISSUE TITLE
Calendar like Google Analytics

### ISSUE THREAD

**Issue by afrasiyabhaider** [ankurk91/vue-flatpickr-component#255]
I want to create a **calendar like google analytics** with comparison checkbox so it can select 2 ranges 1 in blue 2nd in orange. Is there any way to achieve this task using [vue-flatpickr-component](https://github.com/ankurk91/vue-flatpickr-component)?

![image_2022_04_22T10_41_44_535Z](https://user-images.githubusercontent.com/25869253/165077318-ac5d4b39-dee0-473a-97fc-a175328a9ea9.png)

**Comment by ankurk91** [comment]
Sorry, not possible

**Comment by afrasiyabhaider** [comment]
https://github.com/Owumaro/vue-date-range-picker
