### ISSUE TITLE
Validate with Vee-Validate v4 

### ISSUE THREAD

**Issue by danielcharrua** [ankurk91/vue-flatpickr-component#256]
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

* flatPickr version : 4.6.13
* Vue.js version : ^3.2.33
* Browser name and version : Safari 15.3
* This package version : ^9.0.6

Hello, I'm trying to validate this field with Vee-Validate v4 using [components validation](https://vee-validate.logaretm.com/v4/guide/components/validation). Any ideas on how to use validation with 
the `<flat-pickr />` component and Vee-Validate?
Maybe my approach is wrong and need to use [Composition API validation](https://vee-validate.logaretm.com/v4/guide/composition-api/validation).

I have searched for examples but can't find any and I really like your component! 
Thank you.

**Comment by ankurk91** [comment]
I have not used vee validate from long but looking at docs, you sppose to do it like

```vue 
<Field v-slot="{ handleChange, value }">
  <CustomInput :modelValue="value" @update:modelValue="handleChange" />
</Field>
```

**Comment by danielcharrua** [comment]
Hello @ankurk91 you are right, the only to add is a name prop, so working example would be:

```
<Field name="date" v-slot="{ handleChange, value }">
  <flat-pickr :modelValue="value" @update:modelValue="handleChange" />
</Field>
```

Thank you.
