### ISSUE TITLE
Wait till both date is selected in range mode to update v-model

### ISSUE THREAD

**Issue by zahidhasanemon** [ankurk91/vue-flatpickr-component#257]
I am using the following versions
* Vue.js version : 2.6.12
* This package version : 8.1.6

**Current behavior**
In range mode, when I select the first date, it triggers the v-model update. I am using watcher on the v-model, so it is called twice for that v-model. And after selecting the first date, if I click outside, flatpickr closes and nothing on the input field but v-model still holds the value. [Fiddle](https://jsfiddle.net/90tLyx2a/)
```
flatPickrConfig: {
  wrap: true, mode: 'range', dateFormat: 'd/m/Y', enableTime: false,
},
```

**Expected behavior**
I want to wait till both the date (or just same date selected twice like the current behavior) are selected to trigger v-model update. Is there any config for this?

**Comment by ankurk91** [comment]
I don't know what are you trying to achieve.

This vue component depends on it parent library and can not act differently

**Comment by zahidhasanemon** [comment]
Data binding is on the vue end, right?? I want to populate v-model value when both date is selected.

**Comment by ankurk91** [comment]
Sorry, I can not help in this.

This requirement is not related to this package.
