### ISSUE TITLE
disableMobile setting not working, repro linked in issue

### ISSUE THREAD

**Issue by Jogai** [ankurk91/vue-flatpickr-component#258]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 9.0.6
* Vue.js version : 3.2.33
* Browser name and version : Chrome 104.0.5112.14 
* This package version : 9.0.6

**Current behavior**
Behavior is the same, regardless of the disableMobile setting.

**Expected behavior**
Native date should be shown in the mobile view.

**Minimal reproduction of the problem with instructions**
https://codesandbox.io/s/wizardly-engelbart-qfjs7p

**Comment by ankurk91** [comment]
It is working fine for me on my mobile with ms edge browser

**Comment by ankurk91** [comment]
You may want to report the issue on parent repo
https://github.com/flatpickr/flatpickr

**Comment by Jogai** [comment]
Thanks. In an actual mobile browser it does seem to work. And the parent project has the same issue. Thanks for answering quickly!

**Comment by ankurk91** [comment]
When i said "on my mobile with ms edge", i meant the actual mobile device.
