### ISSUE TITLE
because I get a different date by changing the format d/m/Y

### ISSUE THREAD

**Issue by webpackages** [ankurk91/vue-flatpickr-component#26]
![dfsdfsdf](https://user-images.githubusercontent.com/5165935/31042891-94183a40-a577-11e7-9e03-0b5330e27954.JPG)

![dsfsdfsdf](https://user-images.githubusercontent.com/5165935/31042870-1084e890-a577-11e7-859a-cd9a3bec9aea.JPG)
![aaaaaaaaaaaaaa](https://user-images.githubusercontent.com/5165935/31042871-1fdf4844-a577-11e7-8a50-05735ba036d1.JPG)
![asdsfsdfsdfsdf](https://user-images.githubusercontent.com/5165935/31042872-23f4e0ba-a577-11e7-90a4-c6c56e57407c.JPG)
![asdfsdfsdf](https://user-images.githubusercontent.com/5165935/31042873-27356e02-a577-11e7-9fdb-9fee904390de.JPG)

**Comment by ankurk91** [comment]
Can you describe your issue ?
What you want to achieve ?

**Comment by webpackages** [comment]
I want to show my date in d/m /Y format.
for example:

In the database I have a DATETIME field  => 2017-10-26 04:13:26
To the end user I want to give the format      26/10/2017 04:13PM

THE PROBLEM IS THE CHANGE OF DATE

**Comment by ankurk91** [comment]
`altInput` and `altFormat` options should solve your problem
https://chmln.github.io/flatpickr/examples/#human-friendly-dates

**Comment by webpackages** [comment]
Thanks for your help, it works perfectly.
