### ISSUE TITLE
Unknown html tag flat-pickr

### ISSUE THREAD

**Issue by bcorcoran** [ankurk91/vue-flatpickr-component#260]
Using vue-flatpickr-component ^9.0.6 and Vue 3

I am importing as such:

```js
import flatPickr from 'vue-flatpickr-component'
```

and using it in my `<template>` as such:

```
<flat-pickr v-model="x" name="y" ... />
```

My editor is PHPStorm (but I'm sure this would occur in Webstorm or any other Jetbrains IDEs as well) -- it complains that:

"Unknown html tag flat-pickr"

This is the only package I've got that has this issue which makes me wonder if there's something about the way it has been exported? Most packages seem to require the `import { something } from 'somewhere'` format.

FWIW, the package works fine, but the IDE just can't tell that it's a component.

**Comment by ankurk91** [comment]
Please follow the documentation Readme.

Looks like you did not register the component

**Comment by bcorcoran** [comment]
Tried that, same issue. IDE does not recognize it as a component so it thinks it's an invalid html tag.

I also tried `app.component('flat-pickr', VueFlatPickr)` and same result- IDE does not recognize it.

**Comment by ankurk91** [comment]
I can not teach you vue j's on Github.
