### ISSUE TITLE
Extra date not listed in `enable` is partially enabled 

### ISSUE THREAD

**Issue by ashiful-kyos** [ankurk91/vue-flatpickr-component#262]
**I'm submitting a** 

```
[x] Bug report
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

Irrelevant. It's a visual issue. Even can be seen in the example of the documentation 

**Current behavior**
If dates are in the `enable` an extra date gets enabled and selectable in the date-time picker. The extra enable date seems to to be the date first enabled date + 1 month. Although this extra date is selectable but selecting that date gets the value of the first enabled date. For example say configuration has `enable: ['2025-03-30']` the date time will show two enable dates 2025-03-30 and 2025-04-30. The extra enable date 2025-04-30 visually looks different but selectable. 

**Expected behavior**
Only listed date in `enable` should be selectable. 

**Minimal reproduction of the problem with instructions**
- go to https://flatpickr.js.org/examples/#disabling-all-dates-except-select-few 
- the example lists enable dates `enable: ["2025-03-30", "2025-05-21", "2025-06-08", new Date(2025, 8, 9) ]`
- find date `2025-04-30`. You will be able to select this date.

**Comment by ashiful-kyos** [comment]
![Screenshot 2022-09-26 at 10 30 57](https://user-images.githubusercontent.com/39823335/192231877-58c059a9-7d8a-4c71-b5b8-c0e700a63f69.png)

**Comment by ankurk91** [comment]
I am not responsible for flatpickr repo
