### ISSUE TITLE
Translate placeholder with altInput

### ISSUE THREAD

**Issue by marciado** [ankurk91/vue-flatpickr-component#264]
**I'm submitting a ...**  (check one with "x")

```
[X] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 4.6.x
* Vue.js version : 2.7
* Browser name and version : Chrome|Firefox|Edge
* This package version : 8.1.7

**Current behavior**

I can not understand how the issue #148 is solved. This is no solution to set `altInput` to `false`.
I need to use `altInput` and want to translate my placeholder. This is not possible. 
![image](https://user-images.githubusercontent.com/94978135/194861940-a73bb197-c698-40d5-96a4-8b2b67ad7ec4.png)
The input field generated by original flatpickr is right, the placeholder changes. The input field of vue-flatprickr does not change the placeholder.
I also use the `confirmDatePlugin`. When I use a translation string (vue  i18n string) for `confirmText`. The translation does not work also.

**Expected behavior**

The placeholder should change translation.

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Dont use `altInput`, please read past issues
