### ISSUE TITLE
Wrapping elements do not fire open picker event

### ISSUE THREAD

**Issue by Codermar** [ankurk91/vue-flatpickr-component#267]
**I'm submitting a ...**  (check one with "x")

```
[ x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 4.6.x
* Vue.js version : 3.2
* Browser name and version : Chrome
* This package version : 11.x.x

**Current behavior**

Adding wrapping elements (as shown in the [flatpicker doc example](https://flatpickr.js.org/examples/)) do not fire events to open and clear picker input

I used your [example](https://github.com/ankurk91/vue-flatpickr-component#detailed-example)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
I could not reproduce it 

https://jsfiddle.net/Lfbhq5ze/6/
