### ISSUE TITLE
flatpicker is not properly work with Vuetify's dialog components

### ISSUE THREAD

**Issue by alokVishu** [ankurk91/vue-flatpickr-component#270]
```
[x] Bug report => search GitHub for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version: 4.6.x
* Vue.js version : 3.2
* Browser name and version: Chrome 
* This package version: 11.0.1

**Current behavior**
I am trying to use the flatpicker with vuetify's dialog components when I select the date the dialog gets closed.

**Expected behavior**
The dialog should not be closed when the flatpicker date select.

**Minimal reproduction of the problem with instructions**
https://codepen.io/alokvishu/pen/rNrJpbm?editors=101

**Comment by ankurk91** [comment]
https://github.com/flatpickr/flatpickr/issues/1241
