### ISSUE TITLE
Question About Version Numbers

### ISSUE THREAD

**Issue by jwbats** [ankurk91/vue-flatpickr-component#271]
I'm still on 11.0.1, but npm outdated tells me there's a lower, but newer version: 8.1.8.

[Browsing the branches](https://github.com/ankurk91/vue-flatpickr-component/branches), 11 isn't even listed anymore.

I've never seen this before. Can you explain what happened with the version numbers, here?

Can I update from 11.0.1 to 8.1.8 and expect things to stay in working order?

**Comment by ankurk91** [comment]
Hi,

Thats weird.

Version 11 is still the latest version.
I recently released a patch on  version 8.

I will be bump version 11 on Wednesday to fix the npm issue

**Comment by jwbats** [comment]
Thanks for the feedback. I'll close this ticket later this week, when the npm outdated issue goes away.

**Comment by ankurk91** [comment]
Version 11.0.2 has been released

https://www.npmjs.com/package/vue-flatpickr-component/v/11.0.2

**Comment by jwbats** [comment]
Problem solved.

Tnx.
