### ISSUE TITLE
On day create event dont exist

### ISSUE THREAD

**Issue by Tiberiu96** [ankurk91/vue-flatpickr-component#274]
I am using vue flatpickr on my vue2 proiect, i read all documentations, i've tried every way possible to use on day created event but seems the event does not exist, the others are just fine, the purpose is to change color for disabled dates. 

Thanks! Waiting for answers.

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-flatpickr-component/blob/bbce594b9c4a7499c2629c02df22010cf60b1d69/src/events.js#L14
