### ISSUE TITLE
flatpickr altFormat bug with locale

### ISSUE THREAD

**Issue by galbeni** [ankurk91/vue-flatpickr-component#279]
**I'm submitting a ...**  (check one with "x")

```
[X] Bug report
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 4.6.x
* Vue.js version : 3.2
* Browser name and version : Chrome, Safari, Firefox
* This package version : ^9.0.5 (vue-flatpickr-component)

**Current behavior**
When you open the flatpickr (with datetime, enabled altInput and with locale (e.g. "en") configuration) and select a date or time, then the input shows the datetime format like this: **Apr 27, 2023 2:00 AApr** instead **Apr 27, 2023 2:00 AM** or in hu locale: **2023. 05á6. 6. 2:00** instead **2023. április 4. 2:00** It shows very strangely, with random characters..

```
data() {
    return {
        config: {
            enableTime: true,
            defaultHour: 24,
            time_24hr: true,
            allowInput: false,
            altInput: true,
            minDate: moment().format(),
        }
...
```

I use an onchange method to change altFormat dinamically like this:

```
<flat-pickr
  v-model="date"
  :config="config"
  @on-change="onDateTimeChange"
/>

onDateTimeChange(selectedDates, dateStr) {
      this.config["altFormat"] = moment(dateStr).format("lll");
},
```

**The problem is still appears with or without momentjs format!**
I tried with flatpickr.js.org component too and does the same thing.

**Expected behavior**
When you open the flatpickr and choose a datetime should be show the correct datetime format:
**May 6, 2023 2:00 PM,** but it shows like this: **Maya23 6, 2023 2:00 AMay**

**Minimal reproduction of the problem with instructions**
[https://codesandbox.io/s/vue-flatpickr-locale-boybul?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/vue-flatpickr-locale-boybul?file=/src/components/HelloWorld.vue)

Pick a day or time, you'll see the bug (e.g. Apr 27, 2023 2:00 AApr instead of Apr 27, 2023 2:00 AM) or test it with changing locale to "hu".

**Comment by ankurk91** [comment]
It the problem persist with parent library then i think you should report the issue there.

**Comment by galbeni** [comment]
Alright, thank your for your respond.
