### ISSUE TITLE
flatpickr not working with vuematerial input

### ISSUE THREAD

**Issue by hanxue** [ankurk91/vue-flatpickr-component#28]
#### Environment
* flatPickr version : 3.1.2
* Vue.js version : 2.3.4
* Browser name and version : Firefox 56.0, Chrome 63.0.3234

**Current behavior**
After selecting a date, the input field does not display the text

![image](https://user-images.githubusercontent.com/760008/31314162-fcebb1ae-ac2b-11e7-945d-097a44f9b118.png)

**Expected behavior**
flatPickr component should display the date, and can be bound to vue.js instance data

**Minimal reproduction of the problem with instructions**
Relevant code:

```html
              <md-input-container>
                <md-icon>schedule</md-icon><label>Project Deadline</label> 
                <flat-pickr v-model="projectDeadline">
                </flat-pickr>
              </md-input-container>
<script>
import Vue from 'vue'
import flatPickr from 'vue-flatpickr-component'
import 'flatpickr/dist/flatpickr.css'

export default {
    components: {
        flatPickr
    },
    data () {
        return {
            projectDeadline: null,
        }
    },
}
</script>
```

**Comment by ankurk91** [comment]
Seems like `md-input-container` has some ui issues.
I was able to make it working like this -
```html
 <div class="md-input-container md-theme-default md-has-value">
    <md-icon>schedule</md-icon>
    <label>Project Deadline</label>
    <flat-pickr v-model="projectDeadline" input-class="md-input" placeholder="Select a date">
    </flat-pickr>
  </div>
```
`md-input-container` renders a empty div and i am just copied the rendered html here.
You may also notice the prop `input-class="md-input"`

See jsfiddle in action -
https://jsfiddle.net/ankurk91/r1en6te0/

**Comment by hanxue** [comment]
@ankurk91 Many thanks for your assistance and fast response. I use the code snippet above and indeed it is working. 

Does it mean the `md-input-container` is a bug when it generates an empty `<div>`? If so I will open a new Issue on upstream (vue-material). 

From the documentation, **Available Props** list `input-class`, but in the Bootstrap 3 example, there is a `:class` attribute

```html
        <flat-pickr
                v-model="date"
                placeholder="Select date"
                :config="config"
                :required="true"                
                :class="form-control custom-input-class"                
                name="date">
```

What is the difference of `input-class` and `:class`?

**Comment by ankurk91** [comment]
I have fixed the docs about css class prop.
The right syntax is 
```html
 <flat-pickr
                v-model="date"
                input-class="md-input"
>
```

I meant `md-input-container` component is just a wrapper and renders a div, i am not sure if there is a bug or not.
I feel there is a CSS issue regarding font-size.

I have updated the fiddle -
https://jsfiddle.net/ankurk91/r1en6te0/3/
You will notice when i add `font-size` to input it works well.
```html
<md-input-container>
  <flat-pickr v-model="projectDeadline" input-class="md-input" style="font-size:16px!important">
    </flat-pickr>
  </md-input-container>
```
So yes you can report this to upstream repo.
