### ISSUE TITLE
Missing dropdown to select year when locale Vietnamese

### ISSUE THREAD

**Issue by HuanVo** [ankurk91/vue-flatpickr-component#280]
Missing dropdown to select year when locale Vietnamese.
![image](https://github.com/ankurk91/vue-flatpickr-component/assets/25062070/560df477-44a4-4661-a596-788e867fee01)

My setting: 

```js
const config = ref({
  //wrap: true, // set wrap to true only when using 'input-group'
  dateFormat: 'd-m-Y',
  locale: Vietnamese, // locale for this instance only
});`
```

**Tell about your platform**

* flatPickr version : 11.0.3
* Vue.js version : vue/cli 5.0.8
* Browser name and version : Chrome
* This package version : 9.6.6

**Comment by ankurk91** [comment]
Can you please create a JSFiddle to demonstrate the issue?
https://jsfiddle.net/

**Comment by HuanVo** [comment]
> Can you please create a JSFiddle to demonstrate the issue? https://jsfiddle.net/
Vietnamese characters are long.
I increased the width of the flatpickr-current-month element to 100%.
It solved the problem.
Do you have any other solution?
![image](https://github.com/ankurk91/vue-flatpickr-component/assets/25062070/021bb8cd-860b-45fe-b6f8-372418e4af61)

**Comment by HuanVo** [comment]
Looks like my stylesheet is conflicting somewhere. I will fix this conflict on my source code side. Many thanks @ankurk91 !
