### ISSUE TITLE
Support predefined date ranges in calendar

### ISSUE THREAD

**Issue by nguyenquocdaile** [ankurk91/vue-flatpickr-component#289]
Does this component support this UI? If not. Is there any way to customize it?

![image](https://github.com/ankurk91/vue-flatpickr-component/assets/12345613/9a9345de-605a-44a8-b9fa-04ce9996134d)

**Comment by ankurk91** [comment]
https://flatpickr.js.org/examples/

**Comment by nguyenquocdaile** [comment]
Hi @ankurk91 , In the example of Flickr, I don't see what example supports predefined date ranges

**Comment by ankurk91** [comment]
Then what I can do?
