### ISSUE TITLE
Cannot override "flatpickr-wrapper" class

### ISSUE THREAD

**Issue by mohsin889** [ankurk91/vue-flatpickr-component#291]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 4.5.x
* Vue.js version : 2.5
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 5.0.5

**Current behavior**
I have added scoped style but it is not overriding the class.

**Expected behavior**
It should oerride the class width to 100%.

**Minimal reproduction of the problem with instructions**
I'm using bootstrap vue and in the bootstrap modal i have a form and in the form i have vue-flatpickr-component. i have config 

{
       static: true,
        altInput: true,
        altFormat: "Y-m-d H:i",
        enableTime: true,
        minuteIncrement: 15,
        defaultHour: 16,
        defaultMinute: 0
}

**Comment by ankurk91** [comment]
Please create a reproduction of the issue
