### ISSUE TITLE
webpack build fails ("unexpected token")

### ISSUE THREAD

**Issue by kermorgant** [ankurk91/vue-flatpickr-component#3]
```
[X] Other : support
```
Hello,

I've integrated your component (thanks for it !) but src/index.js makes my production webpack build fail with this message

```
ERROR in vendor.9cd50ac0.js from UglifyJs
Unexpected token: operator (>) [./~/vue-flatpickr-component/src/index.js:4,0][vendor.9cd50ac0.js:9,147031]

```
Seems related to es6 syntax in file below, but I have no idea about a fix.

```
 install: (Vue, options) => {
    Vue.component('flat-pickr', component);
    require('flatpickr/dist/flatpickr.css');  
```

Any suggestion ?
Thx

**Comment by louisbourque** [comment]
Can confirm, I'm getting the same error. Version 2.0.0 worked fine.

@kermorgant, adding 
```
{
    test: /\.css$/,
    loader: 'css-loader'
},
```
to my webpack.config.js allows the build to complete: 

```
loaders: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      },
      {
        test: /\.css$/,
        loader: 'css-loader'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
    ]
```
You'll also have to `npm install -D css-loader`



The error I get after upgrading to 2.1.0:
```
ERROR in ./~/flatpickr/dist/flatpickr.css
Module parse failed: /home/louis/git/liveagent/node_modules/flatpickr/dist/flatpickr.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/home/louis/git/liveagent/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/louis/git/liveagent/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/louis/git/liveagent/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/louis/git/liveagent/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ ./~/vue-flatpickr-component/dist/vue-flatpickr.min.js 1:82-121
```

**Comment by ankurk91** [comment]
@kermorgant 
It was not syntax error, it was webpack who was treating css file as js file in absence of a loader.

Since version [v2.1.0](https://github.com/ankurk91/vue-flatpickr-component/compare/2.0.0...2.1.0) i have introduced a [new way](https://github.com/ankurk91/vue-flatpickr-component#as-plugin) to use this package.
```js
  import Vue from 'vue';
  import {flatPickrPlugin} from 'vue-flatpickr-component';  
  // Register a global component and import required css
  Vue.use(flatPickrPlugin);
```
Most of the webpack users already have **css-loader** configured, so it should not bother all users.
I am going to a note about css-loader in changelog.

### I dont to configure **css-loader**, how can i still use this package ?
```
// You still need 'vue-loader'
import flatPickr from 'vue-flatpickr-component/src/flatPickr.vue';
// Include css yourself
```

Let me know if you still have question.

**Comment by kermorgant** [comment]
Hi,

@louisbourque and me do not have the same problem (css loading fine on my config).

I modified the src/index.js file (see below) to check my assumption about es6 syntax (reading https://survivejs.com/webpack/optimizing/minifying/ mentions this I think) and it built without error

```
const flatPickrPlugin = {
  install: function(Vue, options) {
    Vue.component('flat-pickr', component);
    require('flatpickr/dist/flatpickr.css');
  }
};
```

Here's the content of my .babelrc file which maybe lacks something ? 

```
{
"presets": ["es2015"],
"plugins": ["transform-runtime", "transform-object-rest-spread"],
}
```

**Comment by ankurk91** [comment]
@kermorgant 
Version 2.4.0 should fix your issue.
``
npm install vue-flatpickr-component@2.4.0
``
I was using right ES6 syntax but i dont know why Uglify JS was unable to parse it.

**Comment by mmitrasish** [comment]
How to solve this problem similar to @kermorgant 
Here is the problem->
`ERROR in static/js/vendor.77cf78914d6c09634b2d.js from UglifyJs
Unexpected token: operator (>) [./~/ipfs-http-client/src/dht/index.js:5,0][static/js/vendor.77cf78914d6c09634b2d.js:11,24]

  Build failed with errors.`
Here is the webpack.prod.conf.js->
`var path = require('path')
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config/webpack')
var merge = require('webpack-merge')
var baseWebpackConfig = require('./webpack.base.conf')
var CopyWebpackPlugin = require('copy-webpack-plugin')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')

var env = process.env.NODE_ENV === 'testing'
  ? require('../config/webpack/test.env')
  : config.build.env

var webpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({
      sourceMap: config.build.productionSourceMap,
      extract: true
    })
  },
  devtool: config.build.productionSourceMap ? '#source-map' : false,
  output: {
    path: config.build.assetsRoot,
    filename: utils.assetsPath('js/[name].[chunkhash].js'),
    chunkFilename: utils.assetsPath('js/[id].[chunkhash].js')
  },
  plugins: [
    // http://vuejs.github.io/vue-loader/en/workflow/production.html
    new webpack.DefinePlugin({
      'process.env': env
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
    }),
    // extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
    // Compress extracted CSS. We are using this plugin so that possible
    // duplicated CSS from different components can be deduped.
    new OptimizeCSSPlugin({
      cssProcessorOptions: {
        safe: true
      }
    }),
    // generate dist index.html with correct asset hash for caching.
    // you can customize output by editing /index.html
    // see https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: process.env.NODE_ENV === 'testing'
        ? 'index.html'
        : config.build.index,
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
        // more options:
        // https://github.com/kangax/html-minifier#options-quick-reference
      },
      // necessary to consistently work with multiple chunks via CommonsChunkPlugin
      chunksSortMode: 'dependency'
    }),
    // keep module.id stable when vender modules does not change
    new webpack.HashedModuleIdsPlugin(),
    // split vendor js into its own file
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function (module, count) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf(
            path.join(__dirname, '../node_modules')
          ) === 0
        )
      }
    }),
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      chunks: ['vendor']
    }),
    // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
    ])
  ]
})

if (config.build.productionGzip) {
  var CompressionWebpackPlugin = require('compression-webpack-plugin')

  webpackConfig.plugins.push(
    new CompressionWebpackPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp(
        '\\.(' +
        config.build.productionGzipExtensions.join('|') +
        ')$'
      ),
      threshold: 10240,
      minRatio: 0.8
    })
  )
}

if (config.build.bundleAnalyzerReport) {
  var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
  webpackConfig.plugins.push(new BundleAnalyzerPlugin())
}

module.exports = webpackConfig
`

**Comment by ankurk91** [comment]
@mmitrasish
You issue is not related to this package.

**Comment by mmitrasish** [comment]
But I want help in solving this.

**Comment by ankurk91** [comment]
Do you about stackoverflow?

**Comment by mmitrasish** [comment]
Yeah I know about that
