### ISSUE TITLE
Can't Disable Dates Reactively

### ISSUE THREAD

**Issue by jericopulvera** [ankurk91/vue-flatpickr-component#32]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[X ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.0.0
* Vue.js version : 2.4.2
* Browser name and version : Chrome
* This package version :4.0.0

**Current behavior**
Disabling Dates In Config is not working reactively

**Expected behavior**
I should be able to disable dates reactively.

**Minimal reproduction of the problem with instructions**
https://jsfiddle.net/63kzdwLx/18/

**Comment by ankurk91** [comment]
Modify configs with `this.$set`

https://vuejs.org/v2/api/#vm-set
I will post updated fiddle link here soon.

**Comment by jericopulvera** [comment]
@ankurk91 It's not working

**Comment by jericopulvera** [comment]
this is my updated jsfiddle using this.$set
https://jsfiddle.net/63kzdwLx/21/

**Comment by ankurk91** [comment]
@jericopulvera
There are two ways to do this 
```js
// completely overwrite configs so that vue can detect changes
this.config = Object.assign({},this.config,{disable:['2017-10-26']})
// OR
// go native ; like you did
 this.$refs.datepicker.fp.set('disable',['2017-10-26']);
```
This is Vue limitation that it can not detect changes in object type props properties.

**Comment by jericopulvera** [comment]
@ankurk91 thanks it works now.

https://jsfiddle.net/63kzdwLx/24/

**Comment by jericopulvera** [comment]
@ankurk91 is there a way to reactively add disabled dates asynchronously such as pushing to the array.
collecting them before assigning is a heavy process which causes lag in browser

**Comment by ankurk91** [comment]
If i knew this, i would have implemented
