### ISSUE TITLE
How to use open() on vuejs

### ISSUE THREAD

**Issue by youyi1314** [ankurk91/vue-flatpickr-component#33]
**I'm submitting a ...**  (check one with "x")
```
[x] How to trigger open() on vuejs
```

**Tell about your platform**
* flatPickr version : 4.0.0
* Vue.js version : 2.1.10
* Browser name and version : Chrome
* This package version : 4.0.0

**Current behavior**
NONE

**Expected behavior**
Trigger flatpickr with custom button

**Minimal reproduction of the problem with instructions**
Below is my code:
`Index.vue`
```
<template>
<div>
<button @click="chooseBooking" class="btn btn-pink">Book Now</button>
</div>
</template>
<script>
    import flatPickr from 'vue-flatpickr-component';
    import 'flatpickr/dist/flatpickr.css';
    import 'flatpickr/dist/themes/material_blue.css'
    export default {
        components: {
            flatPickr
        },
        data(){
            date: new Date()
        },
        methods: {
                chooseBooking(){
                         // Trigger flatpickr
                }
        }
    }
</script
```

**Comment by ankurk91** [comment]
```html
<template>
<div>
<flat-pickr v-model="date" ref="datePicker"></flat-pickr>
<button @click="chooseBooking" class="btn btn-pink">Book Now</button>
</div>
</template>
<script>
    import flatPickr from 'vue-flatpickr-component';
    import 'flatpickr/dist/flatpickr.css';
    import 'flatpickr/dist/themes/material_blue.css'
    export default {
        components: {
            flatPickr
        },
        data() {
           return {
              date: new Date()
          }
        },
        methods: {
                chooseBooking(){
                         // Trigger flatpickr
                   this.$refs.datePicker.fp.open();
                }
        }
    }
</script>
```

**Comment by youyi1314** [comment]
Thanks @ankurk91  for the fast reply =) 
i try but it show `Uncaught TypeError: Cannot read property 'open' of undefined`

**Comment by ankurk91** [comment]
Try this jsfiddle

https://jsfiddle.net/63kzdwLx/32/

**Comment by youyi1314** [comment]
@ankurk91 oh... sorry my bad, i duplicated the <flat-pickr v-model="date" ref="datePicker"></flat-pickr>
so it become multiple datePicker is loaded.
i try debug with console.log(this.refs.datePicker); just found the problem ...

**Comment by jungleBadger** [comment]
This approach do work but it is kinda buggy.

When you click the button after calendar is opened, like to toggle or confirm an operation, it will close and open again due the natural listener of datepickr (click outside to close).

This can be reproduced on fiddle provided by ankur above.

**Comment by byronferguson** [comment]
@ankurk91 I appreciate your swift response. For some reason `open()` won't actually open the calendar, but I can see the `onOpen` event fire and the other methods work. Thoughts? (code can be provided)

**Comment by byronferguson** [comment]
@ankurk91 just a note for this thread. My issue was not uncommon, and the base library resolved this issue based on this ticket: [https://github.com/flatpickr/flatpickr/issues/399](https://github.com/flatpickr/flatpickr/issues/399)

You need to use the `wrap: true` config option to watch for `.open()` events on another part in the DOM.

**Comment by ankurk91** [comment]
@byronferguson
If you really want me help you. Explain your issue in detail. Provide code examples.

This is most likely parent library issue, not this Vue component.

The jsfiddle above in this thread is still working fine. I can open date picker by clicking a button.

**Comment by ankurk91** [comment]
I have updated the above fiddle with the latest versions.
https://jsfiddle.net/586whry3/4/

So there are two ways to get flatpickr instance.

```
this.$refs.datePicker.fp.open()
this.$refs.datePicker.$el._flatpickr.open()
```

**Comment by byronferguson** [comment]
Current issue I've had is it isn't mounting to the right element if I need to hide the input node

Byron Ferguson

**Comment by ankurk91** [comment]
@byronferguson 
I really wants to help, but you have to help me first.
Please create a jsfiddle and write steps so that i can re-produce the issue.
Thanks.

**Comment by tamb** [comment]
To access the flatPicker methods you need to add a `ref` to the `<flat-pickr ref="myRef">.
Then access the ref `this.$refs.myRef`
And access the fp instance on that ref `this.$refs.myRef.fp`
And you can call `.open()` on that.
