### ISSUE TITLE
enableTime popup wont close when click on background.

### ISSUE THREAD

**Issue by youyi1314** [ankurk91/vue-flatpickr-component#34]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report
 (I not sure my problem or bug, I try both **time** only and **date time** also got this problem, I think problem is when using **enableTime: true**)
```

**Tell about your platform**
* flatPickr version : 4.0.6
* Vue.js version : 2.1.10
* Browser name and version : Chrome
* This package version : 4.0.0

**Current behavior**
NONE

**Expected behavior**
click background will close the time picker like date picker.

**Minimal reproduction of the problem with instructions**
Below is my code:
`Index.vue`
```
<template>
<div>
<flat-pickr v-model="date" :config="dateConfig" ref="datePicker"></flat-pickr>
<flat-pickr v-model="time" :config="timeConfig" ref="timePicker"></flat-pickr>
</div>
</template>
<script>
    import flatPickr from 'vue-flatpickr-component';
    import 'flatpickr/dist/flatpickr.css';
    import 'flatpickr/dist/themes/material_blue.css'
    export default {
        components: {
            flatPickr
        },
        data(){
               date: "today",
                time: "00:00",
               dateConfig: {
                    minDate: "today",
                    dateFormat: "d-m-Y",
                    placeholder: 'Select Booking Date',
                    disable: [
                        function(date) {
                            // const curDate = new Date();
                            return (date.getDay() === 5 || date.getDay() === 6);

                        }
                    ]
                },
                timeConfig: {
                    enableTime: true,
                    noCalendar: true,
                    altFormat: "H:i",
                    dateFormat: "H:i",
                    placeholder: 'Select Booking Time',
                },
        },
        methods: {
           
        }
    }
</script
```

> NOTE: It can close only when keyup esc key.

**Comment by ankurk91** [comment]
Could not reproduce

![flatpickr](https://user-images.githubusercontent.com/6111524/32208352-ff79a760-be27-11e7-9f9a-d5860c6d0493.gif)

**Comment by abhishek-x47d** [comment]
I just ran into the same issue. It looks like Flatpickr listens to clicks on the body rather than the document. In some cases, the body is not tall enough to include the picker(which is absolutely positioned), so you're clicking outside the body and this isn't picked up by Flatpickr.

![vue-flatpickr](https://user-images.githubusercontent.com/33653185/32787258-1c1f5bbc-c97c-11e7-821c-69fdb7da626a.png)

A simple fix is to set the html, body height to 100%(if that makes sense for your application).
chmln/flatpickr/#964 could also be the same issue.

**Comment by ankurk91** [comment]
Thanks @abhishek-x47d , awesome description.

Agree with you. Can you also report this issue on flatpickr again with same description.

**Comment by abhishek-x47d** [comment]
Hi @ankurk91, rather than open a new issue, I've added a comment to the existing issue(#964).
Thanks!
