### ISSUE TITLE
range plugin not supported

### ISSUE THREAD

**Issue by ankurk91** [ankurk91/vue-flatpickr-component#38]
The [range plugin](https://flatpickr.js.org/plugins/#rangeplugin-beta) not supported at the moment.
Range plugin requires two inputs, in our case these will be two different components and each component will have its own scope.

**Comment by Cosbgn** [comment]
I can access the two dates in the onClose function in the config:

```
data() {
  return {
      message:'Hello',
      flatPickrConfig: {
            dateFormat: "Y-m-d",
            mode: 'range',
            maxDate: "today",
            onClose: function(selectedDates, dateStr, instance) {
                        const startDate = selectedDates[0].toISOString().slice(0, 10);
                        const endDate = selectedDates[1].toISOString().slice(0, 10);
                        console.log(startDate,endDate)
                        // This all works, but I can't get startDate and endDate out of here.
                         // All the following return undefined!
                        // this.message = startDate; message=startDate; etc. Same for:
                        // this.$eventHub.$data.startDate = startDate
                        // this.$eventHub.$data.endDate = endDate
                        // this.$eventHub.$emit('change', { startDate, endDate });
                        },
      },
  }
}
```

Any way I can access startDate and endDate? for Ranges?

**Comment by theianjohnson** [comment]
Would love to see the range plugin supported, is it being worked on?

**Comment by ankurk91** [comment]
Range plugin is the complex one.
You can achieve similar functionality via events. See example

https://github.com/ankurk91/vue-flatpickr-component/blob/e58b4467d6d9e6f6151c4ff7ffd1bf27d6da086f/examples/App.vue#L352-L358

**Comment by ankurk91** [comment]
Hi, 
There has been lots of conversation done already on this topic.
This component mimics flatpickr behavior.
If you want array value then you can create a computed property or listen to `on-change` event.

**Comment by radudalbea** [comment]
Then why don't you update the docs to say that the v-model will only be string? And about using the events, it's not the change, it's also the initial value for the picker which right now it should be set also with startDate to endDate. Anyway, the issue here is to update the docs and you won't receive this kind of issues. If I could see the limitations of a package from upfront I would just look for another one.

Thanks.

**Comment by javiercbk** [comment]
I was able to do this without any issue, check [this PR](https://github.com/ankurk91/vue-flatpickr-component/pull/133)
