### ISSUE TITLE
test cases wont run on node v8

### ISSUE THREAD

**Issue by ankurk91** [ankurk91/vue-flatpickr-component#39]
Test case hangs on node v8.9.0 LTS.

**ps**
It works well on node v9 and node v6

**Comment by Accontech-Tigran** [comment]
Sorry for inappropriate placing of request.Thank you for an awesome component! Could you plaese clarify how to set globally the "locale" of plugin.How to use vue.set ? Assuming I`m loading the locale. import { Spanish } from "flatpickr/dist/l10n/es.js";

**Comment by ankurk91** [comment]
@Accontech-Tigran
You should be creating new issue.
You can globally set the locale as you would do in plain js as described here
https://chmln.github.io/flatpickr/localization/

``js
const flatpickr = require("flatpickr");
const Russian = require("flatpickr/dist/l10n/ru.js").default.ru;
flatpickr.localize(Russian); 
```

**Comment by Accontech-Tigran** [comment]
Thank you very much for your efforts! flatpickr.localize did the trick.  I thought  there was a Vue.js way of doing this.

**Comment by ankurk91** [comment]
Switched to node 9
