### ISSUE TITLE
With vue-router, only first route's flatPickr instances are loaded

### ISSUE THREAD

**Issue by AdamSweeneyCreative** [ankurk91/vue-flatpickr-component#40]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 3.1.2
* Vue.js version : 2.2.1

**Current behavior**

When using the component with vue-router using single-file components, instances of the flatpickr component only load for the first route visited. When I visit additional routes that include the component, those flatpickr instances are not being loaded.

**Expected behavior**

Ideally I'd be able to use instances of flatpickr throughout the app on any route visited. Is there a way to force the component to refresh or find new instances of flatpickr when new routes are visited?

**Comment by ankurk91** [comment]
I have been using this component is several single page apps and i never faced such issue.
Something is wrong in your implementation.
Can you describe more, what error did you see in console?
Share the code on how you are using this package.

**Comment by marcinsnt** [comment]
This is problem of using wrong wrapping element.

You can use:

`config: {
          wrap: false, // set wrap to true when using 'input-group'
}`

Or check my commit to fix this issue

**Comment by ankurk91** [comment]
Closing due to response from OP
