### ISSUE TITLE
Support passive event listeners

### ISSUE THREAD

**Issue by Mark-de-Haan** [ankurk91/vue-flatpickr-component#41]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : N/A
* Vue.js version : 2.5.2
* Browser name and version : Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* This package version : 4.0.0

**Current behavior**
I create a form with one or more <flat-pickr> instances
When the page loads, I get the following message in my console:
```
flatpickr.js?1b10:579 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Expected behavior**
VueJS now supports @click.passive (https://github.com/vuejs/vue/pull/5132)
I do not want this message

**Comment by ankurk91** [comment]
You should report this to flatpickr repo instead.
This package has nothing to do with this.
