### ISSUE TITLE
load livereload.js failed

### ISSUE THREAD

**Issue by Chiyaoching** [ankurk91/vue-flatpickr-component#42]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.1.1
* Vue.js version : 2.5.3
* Browser name and version : Chrome 62.0.3202.94
* This package version : 4.0.0

**Current behavior**
`GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED`

**Expected behavior**
GET http://localhost:35729/livereload.js?snipver=1 success

**Minimal reproduction of the problem with instructions**
When I loaded page, chrome console will show 

`GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED`
![2017-11-16 14 30 56 png 3](https://user-images.githubusercontent.com/5266103/32877113-e25ab7c2-cada-11e7-9de3-bdf1e9147039.png)

**Comment by ankurk91** [comment]
Related to https://github.com/chmln/flatpickr/issues/1117
Please update your [flatpickr](https://www.npmjs.com/package/flatpickr) version to 4.1.2

**Comment by Chiyaoching** [comment]
@ankurk91 thx
