### ISSUE TITLE
Inline date time issues with the time in multiple mode

### ISSUE THREAD

**Issue by Chinese1904** [ankurk91/vue-flatpickr-component#44]
**I'm submitting a ...**  (check one with "x")
```
[#] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.1.4
* Vue.js version : 2.5.9
* Browser name and version : Chrome 62
* This package version : 5.0.0

**Current behavior**

If you inline flatpickr and enable the time and multi multiple mode, you will realize that it is not as intuitive changing the time and it the first chosen time (earliest date) is the one that will be reactive always.

![bug](https://media.giphy.com/media/l3mZbOwdu4zW5UH16/giphy.gif)

**Expected behavior**
the latest chosen date time should be reactive.

**Minimal reproduction of the problem with instructions**

https://jsfiddle.net/63kzdwLx/99/

I would truly appreciate any advice as how I can workaround this bug or any help on fixing it would be amazing!

Thanks so much for this great component.

**Comment by ankurk91** [comment]
@Chinese1904 
Thanks for the detailed bug report.
I found that this is a bug in [flatpickr](https://github.com/chmln/flatpickr) itself.
Here is the example in plain js
```html
<input type='text' id="flatpickr" />
```
```js
var fp = flatpickr(document.querySelector('#flatpickr'), {
  altFormat: "F j, Y",
  altInput: true,
  inline: true,
  enableTime: true,
  mode: "multiple",
  onChange: function(selectedDates, dateStr, instance) {
    console.log('date: ', dateStr);
  }
});
```
You will notice that flatpickr is not updating time on all dates.

![screen-capture](https://user-images.githubusercontent.com/6111524/33590175-b8a82eb4-d9a3-11e7-9c4b-736d7d0cfb36.gif)

Here is jsfiddle -
http://jsfiddle.net/ankurk91/jmxcrknt/

**Comment by Chinese1904** [comment]
@ankurk91 now that I look at it more closely, it seems that the behavior is correct in what you display, but just not with the Vue component chmln reported back as well saying it doesn't appear to be a bug.

Any ideas?

**Comment by ankurk91** [comment]
The Vue component is updating v-model value same as returned from flatpickr and i want to keep the behaviour same.
I agree with **chmln** that you should hook into `onChange` method.

**Comment by Chinese1904** [comment]
Hi @ankurk91 

I think I kindly have to disagree here. The behavior is different from Flatpickr to your Vue wrapper.

Flatpickr will change the last selected date's time if I change the time after I added dates. Which is the correct behavior. 

Your Vue wrapper will change the date's time of the earliest selected date. Which is not very intuitive nor handy because if I change the time after I added dates already, I want to change the last selected date and ongoing selections.

**Comment by ankurk91** [comment]
I see, I will look into it.

**Comment by Chinese1904** [comment]
Thanks a lot @ankurk91 
Appreciate all the work you've already put into it!

**Comment by ankurk91** [comment]
@Chinese1904 
Update to version 5.0.2.
Feel free to reopen.

**Comment by Chinese1904** [comment]
amazing! Thanks for the fix @ankurk91 ! Appreciated a lot!
