### ISSUE TITLE
Available range after day passes

### ISSUE THREAD

**Issue by theaarontaylor** [ankurk91/vue-flatpickr-component#45]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x ] Question
```

**Current behavior**
If a user is inactive from one day to the next, the current date is not available when they visit the next day.

For example, if they use the app on Dec 4, the most recent available date is Dec 4. But if they come back on Dec 5 and don't refresh, Dec 5 won't be available.

What's the best way to handle this situation? (Using range picker)

Thanks for the plugin and for your help!

**Minimal reproduction of the problem with instructions**
If you set your system date back one day, use flatpickr, then change the date forward, the current date should be unavailable

**Comment by ankurk91** [comment]
@theaarontaylor 
Please ask such questions on [flatpickr](https://github.com/chmln/flatpickr).
We should only concern about vue.js here.


#### Answer to question can be -
Date picker is doing what you instructed.
You set min date to be today's date.
At the time of initialisation the date was 4th dec.
The instance will be in memory unless you manually destroy of refresh the page.
When user look at the same browser tab next day and try to select, this is same datepicker that was initialised yesterday. So it should behave same and min date should be 4th dec (NOT 5th dec).
This is same situation where user session is expired when they did not interact with site for long time and he is trying to submit the form next day.

**Comment by theaarontaylor** [comment]
Got it, thanks for answering anyways!
