### ISSUE TITLE
required attribute not working

### ISSUE THREAD

**Issue by DeepakAryal** [ankurk91/vue-flatpickr-component#47]
I set the required prop to true but the form validation does not stop the form from subit.
here is a sample code:
`<Datepicker
              :config="date_to.config"
              :placeholder="$t('outbound.survey.form.date_to.placeholder')"
              :required="true"
              class="form-control"
              id="to"
              name="to"
              ref="to"
              v-if="!date_from.update"
              v-model="survey.dateTo"
              ></Datepicker>`

**Comment by ankurk91** [comment]
@DeepakAryal 

The vue component render correct html.
I just tried flatpickr without vue.js and behaviour is same.

https://jsfiddle.net/nsgzerfk/6/

**Comment by ankurk91** [comment]
You should read this
https://github.com/chmln/flatpickr/issues/892
