### ISSUE TITLE
How to set the local globally ?

### ISSUE THREAD

**Issue by lamberttraccard** [ankurk91/vue-flatpickr-component#49]
Hi, first thanks for your work, it makes working with flatpickr a joy.

I was wondering how I could set the local globally for all the instances of my component ?

Thanks a lot.

**Comment by ankurk91** [comment]
Hi, @lamberttraccard 
Glad that you found this package useful.

Here is how you can set default locale for all flatpickr instances.
```js
// bootstrap.js
import flatpickr from "flatpickr";
import { Russian } from "flatpickr/dist/l10n/ru.js"
flatpickr.localize(Russian); // default locale is now Russian
```
https://chmln.github.io/flatpickr/localization/

And here is how you can set default options.
```js
// bootstrap.js
import flatpickr from "flatpickr";
flatpickr.setDefaults(
{
// default options here
dateFormat : 'm-d-Y'
}
)
```
Any vue component can override these global configs.

**Comment by sbstnplcn** [comment]
Hello, 
I have this error when i try to set default locale : 
__WEBPACK_IMPORTED_MODULE_16_vue_flatpickr_component___default.a.setDefaults is not a function
I'm using webpack with Vue2. Where I'm wrong ?

my code from my main.js : 
`
import flatPickr from 'vue-flatpickr-component'
import 'flatpickr/dist/flatpickr.css'
import { French } from 'flatpickr/dist/l10n/fr.js'
Vue.use(flatPickr)
flatPickr.setDefaults({
  locale: French,
  enableTime: true,
  dateFormat: 'd-m-Y H:i',
  time_24hr: true,
  minDate: 'today'
})
`
Thanks for your awesome component and your response

**Comment by ankurk91** [comment]
You should read the code carefully.
https://github.com/ankurk91/vue-flatpickr-component/issues/49#issuecomment-352961928

**Comment by sbstnplcn** [comment]
oh, damn, i'm so sorry...

**Comment by iShotFT** [comment]
Hello, I'm still struggling to figure this problem out, the last reply was to read the code carefully...
Can someone be a bit more descriptive and point us in the correct direction on how to configure items globally?

**Comment by Firstrings** [comment]
> Hi, @lamberttraccard Glad that you found this package useful.
> 
> Here is how you can set default locale for all flatpickr instances.
> 
> ```js
> // bootstrap.js
> import flatpickr from "flatpickr";
> import { Russian } from "flatpickr/dist/l10n/ru.js"
> flatpickr.localize(Russian); // default locale is now Russian
> import VueflatPickr from 'vue-flatpickr-component'  
> ```
> 
> https://chmln.github.io/flatpickr/localization/
> 
> And here is how you can set default options.
> 
> ```js
> // bootstrap.js
> import flatpickr from "flatpickr";
> flatpickr.setDefaults(
> {
>     // default options here
>     dateFormat : 'm-d-Y'
> }
> )
> ```
> 
> Any vue component can override these global configs.
> 
> Bonus: There are lots of hidden goodies in the code, take a look https://github.com/chmln/flatpickr/blob/master/src/index.ts#L2631-L2653

Thank you very much！This reply save me！
