### ISSUE TITLE
Emit Date instead of string

### ISSUE THREAD

**Issue by NoFrank** [ankurk91/vue-flatpickr-component#50]
Great component to work with FlatPickr in Vue.js!

Just one question: the component emits the string value from the input field on change. If I have a date in my model, FlatPickr sets the initial date correctly but returns a string when a user selects a new date. Is there a way to get date object instead? Couldn't the component emit the date object from the FlatPickr instance instead of the input value?

**Comment by ankurk91** [comment]
The vue component mimic the original flatpickr behavior.
Original flatpickr does not emits Date Objects.
The vue component hooks into "input" event and just emits `event.target.value` .

**Comment by NoFrank** [comment]
Thanks for the fast response. I might be wrong but as I understand it the original flatpickr does not emit any value at all but I can get the value from the fp instance or via events. Within the fp-hooks I get an array of the selected dates and a string representation of the last selected date. Wouldn't make it sense if this component would return the array of the selected dates (or the first one if no date range is configured)? Then I could bind this component directly to a date attribute in the model and it would be updated correctly.

**Comment by NoFrank** [comment]
Yeah, ok. That's a solution to get the raw dates. Thanks!
