### ISSUE TITLE
can not set null date time value initially

### ISSUE THREAD

**Issue by DeepakAryal** [ankurk91/vue-flatpickr-component#51]
![flatpicker](https://user-images.githubusercontent.com/17777925/34350843-1867b038-ea41-11e7-809d-f99e536296d2.png)

template:
`<Datepicker
                  :config="until.config"
                  :placeholder="$t('user.salesperson.until.placeholder')"
                  class="form-control"
                  id="until"
                  name="until"
                  ref="until"
                  v-model="user._salesperson.until">
                </Datepicker>`

config:
`config: {
          altFormat: 'j M  Y',
          altInput: true,
          dateFormat: 'Y-m-d',
          locale: this.$store.getters.locale,
          wrap: true,
        }`

**Comment by ankurk91** [comment]
@DeepakAryal 

Can you please elaborate more about your issue.
What is the value of
`
user._salesperson.until
`
in your app?

`null` is a valid value for `v-model`.
Here is the fiddle:
https://jsfiddle.net/ankurk91/63kzdwLx/

**Comment by DeepakAryal** [comment]
My mistake. thank you
