### ISSUE TITLE
Date format issues

### ISSUE THREAD

**Issue by jsodeman** [ankurk91/vue-flatpickr-component#54]
**I'm submitting a ...**  (check one with "x")
```
[ x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 6.0.0
* Vue.js version : 2.5.6
* Browser name and version : Chrome

**Current behavior**
```
<flat-pickr
	v-model="filter.start"
	class="form-control date white-flatpickr"
	placeholder="Start date"
	dateFormat="n/j/Y"
	allowInput="true"
	name="start">
</flat-pickr>
```
With the dateFormat as shown when selecting a date like 1/7/2018 it first shows in the format 2018-01-07 and then when the picker is closed it switches to 01/07/2018.

**Expected behavior**
The n/j/Y format should render the date as 1/7/2018 and not have the date shown in a different format while open.

**Comment by ankurk91** [comment]
@jsodeman 
The right way to pass config option is to use `:config` prop.
`dateFormat="n/j/Y"` is not a valid prop and i never documented these props that you have used in your example.
