### ISSUE TITLE
Old vue-flatpickr and vue-flatpickr-component retrocompatibility question

### ISSUE THREAD

**Issue by alexsandro-xpt** [ankurk91/vue-flatpickr-component#55]
I'm always use `npm install vue-flatpickr` but today I recive that message ` deprecated vue-flatpickr@2.3.0: this package has been deprecated`

So I found this `vue-flatpickr-component` and install it to replace older `vue-flatpickr` then I saw config `parseDate` options stop work, this event never more was fired, my config is:

      fpOptions: {
        minDate: '2018-01-01',
        maxDate: new Date(),
        locale: pt,
        // dateFormat: 'Y-m-d',
        altFormat: 'd/m/Y',
        altInput: true,
        allowInput: true,
        parseDate: function (e) {
          if (e.indexOf('/') > 0) {
            let parts = e.split('/');
            let ee = new Date(parseInt(parts[2], 10),
              parseInt(parts[1], 10) - 1,
              parseInt(parts[0], 10));
            return ee;
          }
          let parts = e.split('-');
          let ee = new Date(parseInt(parts[0], 10),
            parseInt(parts[1], 10) - 1,
            parseInt(parts[2], 10));
          return ee;
        },
        onReady: function (a, b, c) {
          Mask.bind(c.altInput, { value: '99/99/9999' });
          c.altInput.addEventListener('keyup', (e) => {
            if (c.altInput.value.length >= 10) {
              c.setDate(c.altInput.value);
              setTimeout(() => { c.close(); }, 300);
            }
          });
        }
      },

What is wrong?

**Comment by ankurk91** [comment]
Hello,
You should report this issue on flatpickr repo instead 
Some has already reported
https://github.com/chmln/flatpickr/issues/1196
