### ISSUE TITLE
Issue with Vue's async event loop

### ISSUE THREAD

**Issue by emileindik** [ankurk91/vue-flatpickr-component#56]
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```
Hi there,

Thank you for this component.
I ran into an issue caused by Vue's async event loop.

To reproduce, go to this fiddle: https://jsfiddle.net/6b94mxes/
- Open calendar, the time should be updating every second
- Scroll up once on the minutes location to increase the minute by one. Do this right before the seconds is about to change to the next second

Expected behavior: The minute place will increase and the calendar will stop updating until one minute has passed. 

Current behavior: DOM input takes a few moments to change v-model. So this.date is not updated quickly enough and the minute place reverts back to what it was. 

Any advice on how to work around this?

Thanks!

**Comment by EmileIndik** [comment]
Your example is working correctly.
However, if you wait a little longer to click, just before the second is about to change, then the bug occurs.
Can you see it in my example?

![bug](https://user-images.githubusercontent.com/8562758/35026802-f4eb4e68-fb01-11e7-96bb-c51236a7add9.gif)

**Comment by EmileIndik** [comment]
Your example has it working correctly.
However, if you wait a little longer before clicking, just before the second is about to change, then the bug will occur.
Can you see it in my example?
![bug](https://user-images.githubusercontent.com/8562758/35027001-12c89796-fb03-11e7-9fef-caa4c3c551dd.gif)

**Comment by ankurk91** [comment]
I can see the issue.
Here is what happening behind the scenes.

The component is watching for `v-model` value and on every change made from parent component it updates DOM. However this also triggers the `input` event on input element which emits the value to parent component and update `v-model` value.

This may take time to debug. I will try to debug this weekend but i can not promise anything.

**Comment by bhulsman** [comment]
I'm having a similar issue; when a date is selected and the flatpickr component triggers the input event my app will save the date to the server. But I also had to add another button for a user to reset (empty) the date. The button updates the v-model, but the flatpickr component will trigger an input event which leads to sending two updates to the server.

**Comment by ankurk91** [comment]
@bhulsman 
Your issue is different.
When user clicks on reset (clear) button; v-model value needs to be updated so component emits input event with new value.

**Comment by bhulsman** [comment]
@ankurk91 True, but how can I mitigate emitting the input event when the flatpickr component gets mounted? I had to use the workaround because of that.

**Comment by ankurk91** [comment]
@bhulsman
I made some adjustments so that component will not emit `input` event on load.
Check `dev` branch, not released yet.

**Comment by copitz** [comment]
@ankurk91 IMHO the setDate call in the value watcher shouldn't happen with the triggerChange option as this breaks how the update loop is supposed to be. Instead currently with the following...

```html
<flat-pickr :value="myDate || Date.now() + 24 * 60 * 60 * 1000" @input="myDate = $event"/>
```

`myDate` will immediately be set to the default value passed with `:value` which shouldn't happen.

I fixed this for myself by overriding the value watcher:

```javascript
import FlatPickr from 'vue-flatpickr-component'

FlatPickr.watch.value = function value (newValue) {
  this.fp && this.fp.setDate(newValue)
}
```

**Comment by allpereira** [comment]
This issue was solved?

**Comment by ankurk91** [comment]
This will never sold. This is how js works.
