### ISSUE TITLE
How to validating fields via Vee-Validate?

### ISSUE THREAD

**Issue by koddr** [ankurk91/vue-flatpickr-component#57]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 4.2.4
* Vue.js version : 2.5.13
* Vee-Validate: 2.0.3
* Browser name and version : Safari 11.0.3
* This package version : latest

**Current behavior**

I try to use `Vue-Flatpickr-component` with Vee-Validate as single Vue-component. My config for fields for Vee-Validate is simple: `v-validate="'required'"`.

But Flatpickr make my inputs to `type="hidden"` and place his own input near. If I submit this input with empty value — Vee-Validate doesn't show error, all is okay (actually not) and form submitted with empty field...

How can I solve this? Help please.

**Expected behavior**

Show error when has errors.

**Comment by ankurk91** [comment]
I already have examples-

https://github.com/ankurk91/vue-flatpickr-component/blob/b3583b77977e3795ea75ec1884fbbff6f0c39470/examples/App.vue#L120-L126

Vee validate does not work in DOM, it works on v-model

Can you share a JSFiddle with your code?

**Comment by koddr** [comment]
I have problem only if my field have `:config="..."` element.

This is NOT show error border:

```html
<flatpickr
  v-model="birthday"
  v-validate="'required'"
  :config="flatpickr_config.birthday"
  :class="{'input': true, 'is-danger': errors.has('birthday')}"
  type="text" name="birthday" id="birthday"
  class="input is-medium" placeholder="Select birthday" required
></flatpickr>
```

And this working great:

```html
<flatpickr
  v-model="birthday"
  v-validate="'required'"
  :class="{'input': true, 'is-danger': errors.has('birthday')}"
  type="text" name="birthday" id="birthday"
  class="input is-medium" placeholder="Select birthday" required
></flatpickr>
```

**Comment by ankurk91** [comment]
I have made a Fiddle for you.
https://jsfiddle.net/xceh17dv/2/

**Comment by koddr** [comment]
@ankurk91 thank you, but this is not what I want.

In your example, if I click to field, nothing to choice and unfocus them — validation doesn't trigger.

**Comment by ankurk91** [comment]
This was not your original requirement.

Does vee validate support such feature?

**Comment by koddr** [comment]
@ankurk91 yes, of course. Like this: http://vee-validate.logaretm.com/#basic-example

**Comment by koddr** [comment]
@ankurk91 for more understand, I make gifs with trigger error on focus/unfocus.

GIF: https://gyazo.com/494cba40e66f1fc8a7603d669a11c543

Code of field:

```html
<flatpickr
  v-model="birthday"
  v-validate="'required'"
  :config="flatpickr_config.birthday"
  :class="{'input': true, 'is-danger': errors.has('birthday')}"
  type="text" name="birthday" id="birthday"
  class="input is-medium" placeholder="Select birthday" required
></flatpickr>
```

GIF: https://gyazo.com/1a216d4d103fcfed49bc30213718cd2a

Code of field:

```html
<flatpickr
  v-model="birthday"
  v-validate="'required'"
  <!!!! delete `:config` attribute !!!!>
  :class="{'input': true, 'is-danger': errors.has('birthday')}"
  type="text" name="birthday" id="birthday"
  class="input is-medium" placeholder="Select birthday" required
></flatpickr>
```

**Comment by ankurk91** [comment]
Check updated fiddle
https://jsfiddle.net/xceh17dv/8/


It just a matter of configuration
```js
 Vue.use(VeeValidate, {

   events: "input|blur|on-close",

 });
```

**Comment by mutuadavid93** [comment]
@ankurk91 am using vue 2 with vue-flatpickr-component@^8.1 

I have the first field as below
```
<flat-pickr 
    class="form-control datetime-picker" 
    id="appointment-date"
    v-model="cartItemForm['appointmentDate']"
    :config="config"
    @on-change="changeAppointmentDate"
    ></flat-pickr>
```

The second field as below
```
<flat-pickr 
    class="form-control datetime-picker" 
    id="appointment-time"
    v-model="cartItemForm['appointmentTime']"
    :config="config"
    @on-change="changeAppointmentTime"
    ></flat-pickr>
```

I need to set config for a second field when the first one is changed so that it is a timeOnly control with the calendar. I have really struggled with this issue using your package for over 3 days. Kindly help

**Comment by ankurk91** [comment]
Hope this helps

https://github.com/ankurk91/vue-flatpickr-component/blob/4384b59e02ed32edbb1957712aeb6fc895f5116a/examples/App.vue#L310-L315
