### ISSUE TITLE
Don't send input event on programmaticly change date

### ISSUE THREAD

**Issue by paparent** [ankurk91/vue-flatpickr-component#58]
**I'm submitting a ...** 
```
[X] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

* flatPickr version : 4.2.4
* Vue.js version : 2.5.13
* Browser name and version : Chrome 63.0.3239.132
* This package version : 6.2.0

**Current behavior**
When updating a date programatically, it sends an input event

**Expected behavior**
It shouldn't send an input event

**Minimal reproduction of the problem with instructions**
I don't think it should send back an input event. We already know that...

Here for the `setDate`, the second parameter should be false https://github.com/ankurk91/vue-flatpickr-component/blob/master/src/component.vue#L132

Imagine I've a dropdown to select pre-defined dates, and I've a custom entry for custom date. When I listen for input event,, I set the dropdown value to custom, and after the datepicker fire an event, which make the dropdown do it's thing and so on.

I believe that this date change should be done silently.

**Comment by ankurk91** [comment]
@paparent
```js
fp.setDate(newDate,false)
```
Above works fine but i don't know the consequences, i will dig it more this weekend.

**Comment by paparent** [comment]
@ankurk91 Indeed, that's what I did to test it out and works fine on my side. When I set directly the model, the date updates but no input event sent. It's only sent when I use the calendar.

Thanks !

**Comment by ankurk91** [comment]
@paparent 
There are many cases when your requested changes can causes other issues.

For example:

Parent component sets v-model value to `new Date()`, child (this) component passes this value to flatpickr instance with `false` as second argument, flatpickr parses this value and convert it to the format specified in `config`, but parent component will never gets notified about the parsed date.

Another example can be when there is `maxDate` and `minDate` set in configs. Parent component tries to set invalid date. Flatpickr will reject the date and parent component will still have invalid date.

There can be many other cases where `v-model` value and flatpickr's value gets out of sync.

**Comment by paparent** [comment]
@ankurk91 Hi ! Thanks for looking into it ! 

I understand the concerns ! I just don't know how to implement my custom widget which is: select a custom select box entry when a use enter manually a date?

**Comment by rahulpanteon** [comment]
@ankurk91 I also faced a problem, I want to call the change event when a user manually changes the date. Is there any workaround?

**Comment by ankurk91** [comment]
@rahulpanteon 
what is meant by "user manually changes the date".
i wont mind if you open a new issue with an example.

**Comment by ankurk91** [comment]
I am asking you; what is meant by "when user changes the date manually."

Do you allow user to type-in into input field ?
OR
User select the date via flatpicker widget?

**Comment by ankurk91** [comment]
The change event does gets fired when user selects a date via flatpickr widget already.
That's why i am asking you to share you your code or jsfiddle.

**Comment by ankurk91** [comment]
Your second [fiddle](https://jsfiddle.net/qc73xshj/) is your custom flatpickr component. You are not taking care of two way sync. 
Your second fiddle does not update the DOM (flatpickr instance), it only update the v-model.

I have already explained why this component always fires `change` event, see my above comment.

Feel free to fork, copy this component and use in your project.
