### ISSUE TITLE
Limit the default events to be emitted

### ISSUE THREAD

**Issue by ankurk91** [ankurk91/vue-flatpickr-component#59]
Right now component listen to all events available in flatpickr, i want to reduce the events list.

Here is events list and i have marked the events i want to keep -

- [x] onChange
- [x] onClose
- [x] onDestroy
- [x] onKeyDown
- [x] onMonthChange
- [x] onOpen
- [x] onYearChange
- [ ] onValueUpdate
- [ ] onReady
- [ ] onPreCalendarPosition
- [ ] onDayCreate
- [ ] onParseConfig

You will be able to override this via `:events="yourEventsList"` prop.

**Comment by ankurk91** [comment]
> The 42 on-day-create events seems like a bug.

It is not a bug, it is a feature.
These events allow you to customize each day, [see](https://flatpickr.js.org/events/#ondaycreate) how.

**Comment by james-brndwgn** [comment]
> These events allow you to customize each day, see how.
Yeah, I read that.. however that's on onCreate event. Though it seems excessive imo, fair enough... however, that should only occur on the initial load of the calendar. These events are firing every time you change the date. To me that sounds like a bug. As in, the plugin should fire 42 on-day-create events when the calendar loads (and I suppose when changing months) but it shouldn't fire the onDayCreate event when selecting a date. I'll try a non Vue implementation and see if the same occurs.

**Comment by james-brndwgn** [comment]
Hmm.. you were right that's how the plugin creators have designed it. Seems excessive. https://jsfiddle.net/1ns783ze/5/

**Comment by ankurk91** [comment]
closed with v7.0.0

**Comment by james-brndwgn** [comment]
@ankurk91 Just upgraded to 7.0.0 and can confirm this works as expected. Thanks for pushing that update 👍
