### ISSUE TITLE
v-model update not working from parent

### ISSUE THREAD

**Issue by mech01nc01** [ankurk91/vue-flatpickr-component#60]
**I'm submitting a ...**  (check one with "x")
```
[x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.2.3
* Vue.js version : 2.5.11
* Browser name and version : Chrome 64.0.3282.119|Firefox 52.0.1|EDGE 41.16299.15.0
* This package version : https://unpkg.com/flatpickr@4/dist/flatpickr.min.js

**Current behavior**
if i set the date programaticly, it changes back to blank (empty string)
**Expected behavior**
the date should stay setted

**Minimal reproduction of the problem with instructions**
my Setup:
```
				flatpickr.l10ns.default.firstDayOfWeek = 1;
				flatpickr.localize(flatpickr.l10ns.de);
				Vue.use(httpVueLoader);
				Vue.use(MultiLanguage, window.LW_Sprachen);
				Vue.use(VueTippy);
				Vue.component('vuemultiselect', VueMultiselect.default);
				Vue.component('flat-pickr', VueFlatpickr);
```

the minimal component Looks like the following:
```
<template>
	<div>
		<flat-pickr v-model="lieferDatum" :config="{enableTime:false, dateFormat:'d.m.Y',weekNumbers: true, minDate:new Date()}" class="input"></flat-pickr>
		<button v-on:click="test">test</button>
		<button v-on:click="test2">test2</button>
		<div>{{lieferDatum}}</div>
	</div>
</template>

<script>
module.exports = {
	data:function() 
	{ 
		return { 
			lieferDatum:null
		};
	},
	methods:
	{
		test:function()
		{
			this.lieferDatum=new Date();
		},
		test2:function()
		{
			this.lieferDatum="30.01.2018";
		}
	}
}

</script>
```

i hope ist not a silly question because i'm a vue.js-newbie, but i don't know where to ask what i'm doing wrong

**Comment by ankurk91** [comment]
Can you take this jsfiddle and reproduce 
https://jsfiddle.net/ankurk91/63kzdwLx/

**Comment by mech01nc01** [comment]
https://jsfiddle.net/63kzdwLx/188/#&togetherjs=8lnVy2KCQ0

this is working, so do you know whats the Problem?

**Comment by ankurk91** [comment]
Try NOT to use inline configs.

**Comment by mech01nc01** [comment]
oh, this works .. thanks! never thought this could make a difference
