### ISSUE TITLE
enableTime:true is throwing an error: Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by jringeisen** [ankurk91/vue-flatpickr-component#63]
**I'm submitting a ...**  (check one with "x")
```
[X] Bug report => getting Uncaught RangeError: Maximum call stack size exceeded.
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : ^3.1.3
* Vue.js version : ^2.4.4
* Browser name and version : Chrome 63.0.3239.132
* This package version : x.x.x

**Current behavior**
Any time I add enableTime: true to the config I get this error. Everything works as expected but in the console, it's throwing this error.

**Expected behavior**
Everything is displaying as expected, I am getting the result I need minus the error being thrown in the console.

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
You did not followed issue template completely.

**Comment by ankurk91** [comment]
Related issues
https://github.com/chmln/flatpickr/issues/642
https://github.com/chmln/flatpickr/issues/689
