### ISSUE TITLE
v-model don't get updated before on-change method execute

### ISSUE THREAD

**Issue by andrijavulicevic** [ankurk91/vue-flatpickr-component#65]
**I'm submitting a ...**  (check one with "x")
```
[X] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.2.4
* Vue.js version : 2.5.8
* Browser name and version : Chrome  63.0.3239.132 (Official Build) (64-bit)
* This package version : 6.2.0

**Current behavior**
I want to emit event with value bound to v-model in method that execute @on-change event, but problem is that emitted value is previous one (null on first change). 

**Expected behavior**
Emitted value should be one that has just been selected. 

**Minimal reproduction of the problem with instructions**
Example is in codesandbox link, code is in /components/Hello.vue. You can see how value changes in console (I am a bit old school, so console.log). 

https://codesandbox.io/s/6l44rkvpvw 

Any help or advice what is wrong or what am I doing wrong so this happens would be very appreciated!

**Comment by ankurk91** [comment]
You are accessing v-model in your listener method.
You should access the method parameters.
```js
listenToOnChangeEvent(selectedDates, dateStr, instance) {
        console.log('listen To OnChange Event', dateStr);
      },
```

You can examples in the repo itself.

**Comment by ankurk91** [comment]
Check the forked codesandbox

https://codesandbox.io/s/jplqrk5rk5

**Comment by Glideh** [comment]
Today `on-change` still doesn't seem to update the model before getting into the callback unlike usual components (if I'm not wrong)
So @ankurk91 (congrats for this great component BTW) how do you suggest to do this kind of job ?

```vue
<template>
    <div>
       <flat-pickr v-model="input1" @on-change="refresh" />
       <flat-pickr v-model="input2" @on-change="refresh" />
       <input v-model="input3" @change="refresh" />
    </div>
<template>
```

```js
export default {
    data() {
        return {
            input1: null,
            input2: null,
            input3: null,
        };
    },
    methods: {
        refresh() {
            const params = {
                input1: this.input1, // Not updated
                input2: this.input2, // Not updated
                input3: this.input3,
            };
            this.$store.dispatch.refresh(params);
        }
    }
}
```

Should I use watchers for `input1` & `input2` or maybe another event ?

**Comment by ankurk91** [comment]
@Glideh 

Move your `input1`, `input2`, `input3` to a parent object and add a deep watcher to it.

```
form : {
            input1: null,
            input2: null,
            input3: null,
        }
```
```
mounted(){

this.$watch('form', this.updateStore, {deep:true})
}
```

**Comment by Glideh** [comment]
That does the job, thanks
