### ISSUE TITLE
How to use the VueJS component with locale within npm?

### ISSUE THREAD

**Issue by petericebear** [ankurk91/vue-flatpickr-component#68]
I have this in a bootstrap.js file:
```
    import flatPickr from 'vue-flatpickr-component'; 
    const Dutch = require('flatpickr/dist/l10n/nl.js');
    Vue.use(flatPickr);
```

How to register globally the dutch language in this case?

**Comment by ankurk91** [comment]
This has been answered several times, please search on GitHub closed issues

**Comment by petericebear** [comment]
I have search but could not find that at a higher level with the use of Vue.use(flatPickr);

**Comment by ankurk91** [comment]
You meant you could not locate this issue.
https://github.com/ankurk91/vue-flatpickr-component/issues/49

**Comment by petericebear** [comment]
Correct, could not found that one.

For other people, this was the solution for me:
```
import flatpickr from "flatpickr";
import {Dutch} from 'flatpickr/dist/l10n/nl';
flatpickr.localize(Dutch);
import flatPickrVue from 'vue-flatpickr-component';
Vue.use(flatPickrVue);
```
