### ISSUE TITLE
flatpickr-component in v-for loop

### ISSUE THREAD

**Issue by MaevskiyE** [ankurk91/vue-flatpickr-component#69]
Hi Ankur.

Could you please give some advice

I'm trying to use flatpickr-component in v-for loop. It's ok..
I bind it to one data property. Obviously when I choose date in one field, I can see it in all another..

How I can avoid this behavior? I need render several date fields, but save only one I choose..

Will be very appreciate for help

**Comment by ankurk91** [comment]
Can you show me you code a little.
You have to bind each flat picker to a different data property.
I can not understand your use case.

**Comment by MaevskiyE** [comment]
I have something like this

```javascript
<form v-for="item in items" v-bind:key="item.id">
     <div>
          <input type="radio" name="items" :value=item.id :id="item.id" v-model="pickedItem"/>
          <label :for="item.id">{{item.name}}</label>
      </div>
      <div>
          <select type="select" v-model="active">
              <option value="">Status</option>
              <option :value="true">Active</option>
              <option :value="false">Inactive</option>
          </select>
      </div>
      <flat-pickr v-model="startDate" placeholder="Select date" :config="config"></flat-pickr>
</form>

export default {
  data () {
    return {
      items: [],
      pickedItem: '',
      active: '',
      startDate: '',
      config: {
        minDate: Date.now()
      }
    }
  },
```

So I have listed items. After I choose only one of listed - I need send object to back-end..
I saw that with select in the same hell...Maybe you know how to solve this ?

**Comment by ankurk91** [comment]
If you change the value of `startDate` then it will cause all datepicker to update itself.
This is how Vue.js works. You can not stop reactivity.

**Comment by MaevskiyE** [comment]
It looks like I found a way to solve my problem. v-model is a sugar for  two-way binding, so I split it how it should be without it. 

```javascript
<flat-pickr :value='temp2' v-on:input="startDate = $event" placeholder="Select date" :config="config"></flat-pickr>
```
value='temp2' is fake that will not send (It's required, so I should to declare something). As a result I have needed behavior

**Comment by ankurk91** [comment]
Cool
