### ISSUE TITLE
[support] update config on input change

### ISSUE THREAD

**Issue by driera** [ankurk91/vue-flatpickr-component#7]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ x ] Other, please describe, support
```

**Tell about your platform**
* flatPickr version : 3.0.6
* Vue.js version : 2.3.4
* Browser name and version : Chrome 59.0.3071.115
* This package version : 2.4.1
* moment js version: 2.18.1

**Current behavior**
First of all I just started with vuejs 2 so I'm still at the beginning of the learning curve.
I'm firing two instances of flatpickr components in my view (check-in & check-out dates), both are working nice and v-model responds ok but I'm not able to figure out how to update the config of the second instance depending on the value of the first one.

**Expected behavior**
What I need is to set "minDate" of the second instance every time the first one changes.
Would be nice to be able to do something like this:
```
<flat-pickr :config="configs.checkin" v-model="checkinDate" on:change="updateMinDate"></flat-pickr>
<flat-pickr :config="configs.checkout" v-model="checkoutDate"></flat-pickr>
```
and on my js:
```
...
data: {
    checkinDate: '',
    checkoutDate: '',
    configs: {
        checkin: {
            dateFormat: 'd/m/Y',
            weekNumbers: false,
            minDate: moment().format('DD/MM/YYYY')
        },
        checkout: {
            dateFormat: 'd/m/Y',
            weekNumbers: false,
            minDate: moment().add(1, 'day').format('DD/MM/YYYY')
        }
     }
},
methods: {
    updateMinDate() {
        this.configs.checkout.minDate = this.checkinDate.add(1, 'day').format('MM/DD/YYYY');
    }
},
...
```
Any help will be appreciated.

**Comment by ankurk91** [comment]
flatpickr exposes some events, here is the example, [read more](https://chmln.github.io/flatpickr/events/)
```js
export default {
  data() {
    return {
      configs: {
        checkin:{
          onChange: this.onChangeIn
        },
        checkout:{
          onChange: this.onChangeOut
        }
      }
    }
  },
  methods: {
    onChangeIn (selectedDates, dateStr, instance) {
      console.log('Date change hook was called');
    },
    onChangeOut (selectedDates, dateStr, instance) {
      console.log('Date change hook was called');
    },
  }
}
```
Alternatively you can try ``mode: 'range'``

**Comment by driera** [comment]
In fact, this solution does not work. 
The only way I found to make it work is binding the method when the instance is created, not at registration time.

`export default {
  data() {
    return {
    checkinDate: null,
    checkoutDate: null,
      configs: {
        ...
      }
    }
  },
  methods: {
    onChangeIn (selectedDates, dateStr, instance) {
      console.log('Date change hook was called');
    },
    onChangeOut (selectedDates, dateStr, instance) {
      console.log('Date change hook was called');
    },
  },
  created: function() {
    this.$data.configs.checkin.onChange = this.onChangeIn;
    this.$data.configs.checkout.onChange = this.onChangeOut;
  }
}`

**Comment by ankurk91** [comment]
Please take help from examples - 
https://github.com/ankurk91/vue-flatpickr-component/blob/master/examples/App.vue#L232
