### ISSUE TITLE
AllowInput not working

### ISSUE THREAD

**Issue by luanht** [ankurk91/vue-flatpickr-component#71]
```
[x ] Bug report
```
* flatPickr version : 4.x.x
* Vue.js version : 2.x.x
* Browser name and version: All
* This package version : 7.x.x

Jsfiddle: https://jsfiddle.net/63kzdwLx/517/
As you can see, v-model wont updated if you edit the input, unless you hit Enter.

**Comment by ankurk91** [comment]
This is the normal behaviour.
