### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by Thib-G** [ankurk91/vue-flatpickr-component#72]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x
* Vue.js version : 2.x.x
* Browser name and version : Internet Explorer 11 (IE11) 11.309.16299.0 on Windows 10 Pro 1709 16299.309.
* This package version : 7.x.x

**Current behavior**
The date picker does not open with IE11. Even on the official JSFiddle: https://jsfiddle.net/ankurk91/63kzdwLx/

**Expected behavior**
The date picker should open. It works in other browsers (tested with Firefox, Chrome and Edge on Windows).

**Minimal reproduction of the problem with instructions**

Open the [JSFiddle](https://jsfiddle.net/ankurk91/63kzdwLx/) with IE11 on Windows. Click on the input field. The date picker does not show up with IE11.

**Comment by ankurk91** [comment]
Can you also reproduce your issue with plain js?

https://jsfiddle.net/ankurk91/jmxcrknt/

**Comment by Thib-G** [comment]
Hi @ankurk91, thanks for the quick reply.

The [plain JS example](https://jsfiddle.net/ankurk91/jmxcrknt/) works correctly with IE11.

**Comment by ankurk91** [comment]
I see, i will try to find the cause, arranging a Windows 10 laptop.

**Comment by ankurk91** [comment]
@Thib-G 
Unfortunately i was unable to reproduce the issue on real machine.
Here are some screenshots.

![version11](https://user-images.githubusercontent.com/6111524/37465378-fb20b6fe-2880-11e8-9c66-60d9ac12d4d9.png)

![ie-on-win10](https://user-images.githubusercontent.com/6111524/37465381-fd373dbe-2880-11e8-8c90-5bfbbc3421d6.PNG)

Do you have a real Window machine to test on ?

**Comment by Thib-G** [comment]
Yes. Here is how it looks like on my machine:
![image](https://user-images.githubusercontent.com/17512495/37466407-ed325246-285d-11e8-96ff-5a92682176df.png)

Maybe a language problem?

**Comment by Thib-G** [comment]
Very weird, when I open the console like you, it works but there is an "Invalid date provided: Select a date" error:

![image](https://user-images.githubusercontent.com/17512495/37466717-c5ea8d7e-285e-11e8-9753-12c52287de52.png)

**Comment by ankurk91** [comment]
Can you clone this repo and then run examples on your machine?
I have limited access to Windows machine. 
I have to borrow it again from my friends again.
I can not setup my Dev environment on their laptops.

**Comment by ankurk91** [comment]
The one more different in your screenshot is that you have loaded `https` version of jsfiddle and I have not.
I will try with https tomorrow.

**Comment by Thib-G** [comment]
The examples work correctly in IE11. 

![vue-flatpickr-ie11-example](https://user-images.githubusercontent.com/17512495/37472606-c83704c8-286c-11e8-8b12-01fce97afe39.gif)

But there is a error ReferenceError: Promise is undefined. This is normal because IE11 needs a polyfill for Promises.

However, in the app I'm developing, I see the same behavior as in the JSFiddle. It only works with DevTools opened and throws Invalid Date errors:

![vue-flatpickr-ie11-app](https://user-images.githubusercontent.com/17512495/37473230-38ea4f08-286e-11e8-91cd-23314c8a9986.gif)

Very strange. 

Thanks for your support!

**Comment by ankurk91** [comment]
I think culprit is this line, not 100% sure, will have to debug.

https://github.com/ankurk91/vue-flatpickr-component/blob/4134c1a750e423628f9df9ba86a84f7b33325dc1/src/component.vue#L83

Somehow illegal value is being passed to flatpicker Instance.

**Comment by Thib-G** [comment]
I think it's linked to this issue of the original flatpickr: https://github.com/flatpickr/flatpickr/issues/1165#issuecomment-361771251
There is an issue with IE11 which prevents using a `placeholder` and `altInput: true` at the same time.

> Apparently in IE11 dynamically changing an input from `text` to `hidden` causes a weird side effect where `value` gets set to the value of `placeholder` on the input element that was modified.

**Comment by ricky11** [comment]
I had to use vue.config.js transpileDependencies to get this to work in ie11 While the flatpickr itself says it supports ie11 (untested) it seems this vue wrapper will need to be transpiled first, otherwise ie11 will throw an error or fail to load the chunk

**Comment by ankurk91** [comment]
vue-flatpickr-component version 8.x supports IE 11

vue-flatpickr-component version 9.x does NOT supports IE 11
