### ISSUE TITLE
time_24hr is ignored on a phone with region:US

### ISSUE THREAD

**Issue by Olindn** [ankurk91/vue-flatpickr-component#75]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.*
* Browser name and version : Safari, iOS
* This package version : 7.0.1

**Current behavior**
On my iPhone (latest OS) where I have US region settings FlatPickr is ignoring time_24hr instead it is showing AM/PM time

**Expected behavior**
Should just display the time in 24h format

**Minimal reproduction of the problem with instructions**
iPhone Language & Region setting to United States, I've tested it by switching back to Dutch region settings, then it works as intended.

```
<flat-pickr id="startTime" class="form-control" v-model="startTime" :config="timePickerConfig"></flat-pickr>
```
```
timePickerConfig: {
enableTime: true,
noCalendar: true,
dateFormat: "H:i",
time_24hr: true
}
```

**Comment by ankurk91** [comment]
Flatpicker loads native mobile timepicker by default. You may want to set `disableMobile` option to true.
Read more
https://flatpickr.js.org/options/

If you are still facing issues, please report it to
https://github.com/flatpickr/flatpickr
