### ISSUE TITLE
How to use this with vuetify input field ?

### ISSUE THREAD

**Issue by rajagopalx** [ankurk91/vue-flatpickr-component#78]
**I'm submitting a help request**

**My platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.x.x
* Browser name and version : Chrome
* This package version : 7.0.1

Demo: https://codesandbox.io/s/j36q0y3zn5

Thanks

**Comment by rajagopalx** [comment]
Thanks for the quick reply.

**Comment by ankurk91** [comment]
After checking your codesandbox, i dont see any issue.
