### ISSUE TITLE
How to use vue-flatpickr without input text box

### ISSUE THREAD

**Issue by rajagopalx** [ankurk91/vue-flatpickr-component#79]
**I'm submitting a** 
```
 Help request
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.x.x
* Browser name and version : Chrome|Firefox|Safari x.x.x

We can programatically open flatpickr. But When i include `<flat-pickr v-model="date"></flat-pickr>` text box get created. Is there any way to open flatpicker on button click without include text box ?

**Comment by ankurk91** [comment]
It is possible to open flatpickr programatically.
Look for `open()` method
https://flatpickr.js.org/instance-methods-properties-elements/

It is not possible to create flatpickr instance without input field.
What are you trying to do, why do you want it without input field.

**Comment by rajagopalx** [comment]
Because all the time we don't need input field to select the date.  On mobile app, input field occupies more spaces.

I think already this request raised on flatpickr:
https://github.com/flatpickr/flatpickr/issues/767
https://github.com/flatpickr/flatpickr/pull/782

**Comment by ankurk91** [comment]
I already have example which cover your requirements
https://github.com/ankurk91/vue-flatpickr-component/blob/a5cea1809ee43858df9727135b06d4795bc1189e/examples/App.vue#L55-L70

As said by **chmln ** you need to wrap your component, you can hide it with css and also you can utilize the new config option `positionElement`

**Comment by rajagopalx** [comment]
I saw https://flatpickr.js.org/options/. There is no option like positionElement.  But `appendTo` looks like relevant to this. 

When I use like below

```
date_config: {
          enableTime: false,
          wrap: true,
          disableMobile: true,
          dateFormat: 'd-M-y',
          appendTo: window.document.querySelector('#myDate'),
},
```

I get flatPickrInstance.open is not a function.

https://codesandbox.io/s/j36q0y3zn5

**Comment by rajagopalx** [comment]
I refered from here: https://jsfiddle.net/hm9ahv97/

**Comment by ankurk91** [comment]
`positionElement` is a valid option
https://github.com/flatpickr/flatpickr/blob/5b33606433a2765006de84dec9aca4d899f2d63b/src/types/options.ts#L210

You can get flatpickr instance in vue like this-
https://github.com/ankurk91/vue-flatpickr-component/blob/a5cea1809ee43858df9727135b06d4795bc1189e/examples/App.vue#L360

**Comment by rajagopalx** [comment]
Thanks for the tip. I faced one problem.  Position Element only works after I resize the window.

Demo: https://j36q0y3zn5.codesandbox.io/
Code: https://codesandbox.io/s/j36q0y3zn5

Reproduction Steps:

1. Click `Open Date` Button
2. You can see date get open at top right
3. Resize the window. You can see now date get displayed at given position.

Pls help on this. Thank you.

```
const flatPickrInstance = this.$refs.datePickerWrap.fp;
flatPickrInstance._positionElement = window.document.getElementById('myDate'); // eslint-disable-line
flatPickrInstance.open();
```

**Comment by ankurk91** [comment]
@rajagopalx
I think you are spending too much on this.
Please try this in plain js first and then progressively apply in vue.js.

https://jsfiddle.net/h93f96t4/4/

You can see same issue with plain js fiddle as well.
You may want to report this on parent repo.

**Comment by guilhermeaiolfi** [comment]
It could be way easier, the solution changes the declarative way of defining the UI to a programmatic approach.

**Comment by gzurbach** [comment]
I've been struggling with this as well and ended up with the following solution:

```html
<div>
  <flat-pickr
    v-model="date"
    :config="datePickerConfig"
    class="hide-me"
  >
  </flat-pickr>
  <button class="btn p-0 text-white" data-toggle>
    <font-awesome-icon
      :icon="['fas', 'calendar-alt']"
      class="mr-2"
    />Dates
  </button>
</div>
```

```js
export default {
  data() {
    return {
      date: new Date(),
      datePickerConfig: {
        disableMobile: true, // native datepicker does not show up when input is not visible
        wrap: true,
        altInput: true, // optional
        altInputClass: "hide-me"  // optional
      }
    };
  }
}
```

```html
<style lang="scss">
.hide-me {
  visibility: hidden;
  width: 0;
}
</style>
```

It seems to be working. Hope this helps!
