### ISSUE TITLE
Support Server Side Rendering

### ISSUE THREAD

**Issue by wushan** [ankurk91/vue-flatpickr-component#8]
```
[ x ] Feature request
```

**Tell about your platform**
* vue-flatpickr-component: ^2.4.1
* flatpickr: 3.0.6
* NPM 5.0.3
* Nuxt.js: 1.0.0-alpha.5

**Current behavior**
```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Expected behavior**
Fully support SSR

**Minimal reproduction of the problem with instructions**
```js
import Vue from 'vue'
import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css'
// Vue.use(flatPickr)
```

```
flat-pickr(v-model="date")
```

**Comment by ankurk91** [comment]
@wushan 
I have not idea of `Nuxt.js`, searching for help.

**Comment by ankurk91** [comment]
I just tried nuxt.js first time.
```html
<!-- pages/index.vue -->
<template>
  <div>
    <h1>Hello world!</h1>
    <nuxt-link to="/about">About page</nuxt-link>
    <hr>
    <br>
    <no-ssr>
      <flatpickr v-model="date"></flatpickr>
    </no-ssr>
  </div>
</template>

<script>
  import flatPickr from 'vue-flatpickr-component';
  import 'flatpickr/dist/flatpickr.css'

  import NoSSR from 'vue-no-ssr'

  export default{
    name: 'index-page',
    data () {
      return {
        date: null
      }
    },
    components: {
      flatPickr,
      'no-ssr': NoSSR
    }
  }
</script>
```
But it is throwing errors like -
`
ReferenceError: window is not defined
`
and
`
Error: render function or template not defined in component: anonymous
`

**Comment by wushan** [comment]
@ankurk91 this is because window object isn't exist when the page is rendering from server-side. A quick fix for that is using `plugins` with client only settings. [Nuxt.js Doc](https://nuxtjs.org/guide/plugins/#client-side-only)

back to the mismatch virtual DOM tree issue, since flatpickr it self seems not support ssr for now, I am forcing the component rendered in `mounted` hook, which always run codes from client side, not pretty but finally get rid of those warning messages.

`component.vue`
```
flat-pickr(v-if="browserSide")
```
```
mounted () {
  this.browserSide = true
}
```

**Comment by ankurk91** [comment]
May be upcoming flatpickr version will have better SSR support.

https://github.com/chmln/flatpickr/pull/969

**Comment by uptownhr** [comment]
in nuxt try wrapping around <no-ssr> component

**Comment by ankurk91** [comment]
Tested Flatpicker v4.0.5 with nuxt 1.0.0.rc11. and it works well now.

https://github.com/chmln/flatpickr/pull/1069
