### ISSUE TITLE
Option enableTime not working on modal

### ISSUE THREAD

**Issue by darius32bit** [ankurk91/vue-flatpickr-component#80]
**Environment**
* flatPickr version : 7.0.2
* Vue.js version : 2.5.13
* Browser name and version : Chrome  66.0.3359.139 | Firefox 59.0.3
* bootstrap-vue version: 2.0.0-rc.1

**Current behavior**
After clicking on flatpickr input, it instantly disappears. It is a pity that the gif image can not display this correctly.
I'm using b-modal component.
In my opinion, it's enableTime option issue. Without this option flatpickr works fine, but I need to display time picker without calendar picker.

![2018-05-07_10-58-36](https://user-images.githubusercontent.com/39047311/39691539-88895742-51e6-11e8-9780-88943daf9b2d.gif)

**Code:**
```javascript
<v-form-group :validator="$v.start" label="Start Time">
   <flat-pickr class="form-control" v-model="start" :config="flatPickrConfig"></flat-pickr>
</v-form-group>
<v-form-group :validator="$v.end" label="End Time">
   <flat-pickr class="form-control" v-model="end" :config="flatPickrConfig"></flat-pickr>
</v-form-group>

flatPickrConfig: {
  enableTime: true,
  noCalendar: true,
  dateFormat: "H:i K",
  time_24hr: false,
  minuteIncrement: 1
},
```

**Comment by ankurk91** [comment]
Related
https://github.com/flatpickr/flatpickr/issues/1352
