### ISSUE TITLE
Confirmation Button

### ISSUE THREAD

**Issue by thejams** [ankurk91/vue-flatpickr-component#81]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[X ] Other, please describe
```
Hi, great library i only have one question, is there a confirmation button or something like that in the picker ? i check the documentation and there is no reference to something like that, it will be great if there is one.

**Tell about your platform**
* flatPickr version : 6.1.0
* Vue.js version : 2.5.11
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
https://flatpickr.js.org/plugins/
