### ISSUE TITLE
Cannot use Hook, for example 'onDayCreate'

### ISSUE THREAD

**Issue by Kellercai** [ankurk91/vue-flatpickr-component#82]
Hi, thanks for your donation. When the project was developed, there was a problem that could not be solved. The method that I used flatpickr Hook like:
![image](https://user-images.githubusercontent.com/20681598/39912996-fd17097a-5532-11e8-95ca-eac814ab1cdb.png)

But it is Useless，and there is a error return:
![image](https://user-images.githubusercontent.com/20681598/39912652-02cc62d0-5532-11e8-83f7-c9286c7e1e5d.png)

I really don't know how to solve this problem, and I don't know whether my coding is right.

Looking forward to your reply，thank you very much!

**Comment by ankurk91** [comment]
Hi,
Not all hooks/events are enabled by default.
If you want to emit `onDayCreate` event then you need to pass this in the `events` prop.

```html
<flat-pickr
                v-model="date"
                :config="config"                                                                        
                :events="yourEventsArrayGoesHere"
                >
        </flat-pickr>
```

You can read more here
https://github.com/ankurk91/vue-flatpickr-component/issues/59

**Comment by Kellercai** [comment]
![image](https://user-images.githubusercontent.com/20681598/39914049-6c88c0ac-5536-11e8-8f43-b9ebb4e9675a.png)
![image](https://user-images.githubusercontent.com/20681598/39914078-8038f6bc-5536-11e8-81a6-d4dd4c4cde54.png)
I am very happy for you reply, but I try the events prop, and it can not help and the same error return, Thanks!

**Comment by ankurk91** [comment]
Please check this jsfiddle
https://jsfiddle.net/63kzdwLx/950/

**Comment by Kellercai** [comment]
thanks, I have solved my it, the reason is that my version is 4.
