### ISSUE TITLE
Get count of days/weeks from range mode?

### ISSUE THREAD

**Issue by koddr** [ankurk91/vue-flatpickr-component#83]
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

**Tell about your platform**
* flatPickr version : latest
* Vue.js version : latest
* Browser name and version : Safari 11.1
* This package version : latest

**Current behavior**

Hello. I have small question, which did not listed in docs.

So, how to get count of days/weeks from Flatpickr with `mode: 'range'`? For example, I choose two dates: `2018-05-12 to 2018-05-20`. This range of `8 days` or `1.1 weeks` (not sure if this useful).

**Expected behavior**

Build-in method for that function — will be save my time 👍

If anybody can get me solution, you're welcome!

**Comment by ankurk91** [comment]
Ask such questions to

https://github.com/flatpickr/flatpickr
