### ISSUE TITLE
change showMonths dynamically

### ISSUE THREAD

**Issue by glutaminefree** [ankurk91/vue-flatpickr-component#86]
**I'm submitting a ...**
```
[x] Bug report
```

**Platform**
* flatPickr version : 4.4.6
* Vue.js version : 2.5.16
* Browser name and version : Firefox 60
* This package version : 7.0.2

**Current behavior**
Looks like [this bug](https://github.com/flatpickr/flatpickr/issues/1299) already fixed. But I'm still experiencing this behavior :( 

My piece of code:
```js
onResize () {
    if (window.innerWidth < 768) {
        if (this.flatPickrConfig.showMonths === 2) {
            this.$set(this.flatPickrConfig, 'showMonths', 1);
        }
    } else {
        if (this.flatPickrConfig.showMonths === 1) {
            this.$set(this.flatPickrConfig, 'showMonths', 2);
        }
    }
},
```

**Comment by ankurk91** [comment]
Seems like it is bug in flatpickr itself
https://jsfiddle.net/63kzdwLx/983/
When loading flatpickr with `showMonths` false it could not load and i can see error in console
```
Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at VM69 flatpickr.js:542
```

**Comment by ankurk91** [comment]
I can  confirm this, this is happening with plain js version as well.
https://jsfiddle.net/63kzdwLx/984/

You should report this to https://github.com/flatpickr/flatpickr/issues/new
