### ISSUE TITLE
Force initialization of component to re-render day class onOpen

### ISSUE THREAD

**Issue by vigorem** [ankurk91/vue-flatpickr-component#88]
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

Hi there,

first of all thanks for this excellent component.

I'm using the [onDayCreate](https://flatpickr.js.org/events/#ondaycreate) event to customize the rendered date in my calendar.

https://jsfiddle.net/nrwb92m7/3/

It works quite well, the only thing is that the onDayCreate event is generated on the creation of the calendar (on the loading of my page). 

The actual behaviour shows (logically) that the onDayCreate is just triggered at initialization of the component :

<img src="https://media.giphy.com/media/WxIC9u1p6tHQjAqknn/giphy.gif" style="max-width:100%;">

In the fiddle above, the onDayCreate is based on random numbers so values will change every time the calendar is created:

    onDayCreate: function(dObj, dStr, fp, dayElem) {
        // Utilize dayElem.dateObj, which is the corresponding Date
        // dummy logic
        if (Math.random() < 0.15)
            dayElem.innerHTML += "<span class='event'></span>";

        else if (Math.random() > 0.85)
            dayElem.innerHTML += "<span class='event busy'></span>";
    },

I would like to find a way to force flatpickr to redraw each time I open the component (or that I ask it). I noticed it seemed to be the case when the v-model value changes.

Will be very appreciate for help

**Comment by vigorem** [comment]
Well, reading some fiddles, I managed to find the solution by adding the following method:

    redraw(){
          this.$refs.date.fp.redraw()
         }

Which in my case works because the redraw will be called on a value change in my vue instance:
https://jsfiddle.net/nrwb92m7/13/

Sébastien

**Comment by ankurk91** [comment]
You can listen to `open` event and redraw the component.

```
// Under Vue js methods
onOpen(selectedDates, dateStr, instance)
{
instance.redraw();
}
```
This way you no need to use `refs`

**Comment by vigorem** [comment]
This is excellent, mixed with your [fiddle](https://jsfiddle.net/63kzdwLx/950/), I managed to do what I wanted.

Thanks
