### ISSUE TITLE
Flatpickr Plugins?

### ISSUE THREAD

**Issue by JeffBeltran** [ankurk91/vue-flatpickr-component#9]
Sorry if this is a really noob question but im pretty new to the JS world and im not sure how i would enable one of the flatpickr built in plugins...

Here is my setup
```js
import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
import 'flatpickr/dist/themes/dark.css';

Vue.use(flatPickr);
```
and the config object
```js
timeConfig: {
              enableTime: true,
              plugins: [new confirmDatePlugin({})],
              noCalendar: true,
              enableSeconds: false,
}
```
The errors i'm getting would indicate that im importing the plugin incorrectly, which wouldn't surprise me but i can't for the life of me figure out how to get it working, so I was hoping to get some help, thanks in advance.

**Comment by ankurk91** [comment]
@JeffBeltran 
I have updated the examples with plugins.
Here is how you can do it -
```js
 import ConfirmDatePlugin from 'flatpickr/dist/plugins/confirmDate/confirmDate';
 import 'flatpickr/dist/plugins/confirmDate/confirmDate.css';
```
```js
timeConfig :{
    enableTime: true,
    plugins: [new ConfirmDatePlugin({confirmText: 'Done'})]
}
```
Plugins are opt-in, you need to import them beforehand.

**Comment by JeffBeltran** [comment]
Thanks @ankurk91 for getting back to me... i tried that but im getting a 

```
TypeError: Cannot read property 'classList' of undefined
    at FlatpickrInstance.hooks.onChange (app.js:21199)
    at triggerEvent (app.js:20412)
    at FlatpickrInstance.clear (app.js:19664)
    at updateValue (app.js:20466)
    at init (app.js:18883)
    at FlatpickrInstance (app.js:20615)
    at _flatpickr (app.js:20918)
    at new flatpickr (app.js:20944)
    at VueComponent.mounted (app.js:39055)
    at callHook (app.js:42983)
```

This is my what my component looks like
```
<flat-pickr v-model="trainingTimes" class="form-control" placeholder="Set Time..." :config="timeConfig"></flat-pickr>
```
my data
```
return {
            trainingTimes: null,
            timeConfig: {
              enableTime: true,
              plugins: [new ConfirmDatePlugin({confirmText: 'Done'})],
              noCalendar: true,
              enableSeconds: false,
              time_24hr: false,
              dateFormat: "h:i K",
              defaultHour: 8,
              defaultMinute: 30,
              minuteIncrement: 15,
            }
        };
```

The flatpickr interface still works but this errors out. Am i doing something wrong?

**Comment by ankurk91** [comment]
@JeffBeltran 
Seems like it is a bug in **confirmDateplugin** itself.

for the meantime, you can update your config like this to get rid of warnings -
```js
 plugins: [new ConfirmDatePlugin({confirmText: 'Done', showAlways:true})],
```

**Comment by JeffBeltran** [comment]
Ah, that did it. Thanks @ankurk91!

**Comment by ankurk91** [comment]
@askshinde

Did you import the plug-in js?

**Comment by askshinde** [comment]
Thank you for your reply

This is how my app.js looks

import VueFlatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
import 'flatpickr/dist/themes/airbnb.css';
import 'flatpickr/dist/themes/material_blue.css';

import ConfirmDatePlugin from 'flatpickr/dist/plugins/confirmDate/confirmDate';
import 'flatpickr/dist/plugins/confirmDate/confirmDate.css';

Vue.use(VueFlatPickr);

I also tried using

Vue.use(ConfirmDatePlugin);

no help the error is still there

**Comment by ankurk91** [comment]
@askshinde

Could not reproduce the issue.

I have this in examples folder -

https://github.com/ankurk91/vue-flatpickr-component/blob/9514383de691bd56f02d849daf93d2862e71e17e/examples/App.vue#L214

https://github.com/ankurk91/vue-flatpickr-component/blob/9514383de691bd56f02d849daf93d2862e71e17e/examples/App.vue#L265
