### ISSUE TITLE
set the locale and firstDayOfWeek together

### ISSUE THREAD

**Issue by scottybo** [ankurk91/vue-flatpickr-component#90]
Currently my FlatPickr config looks like:

```js
                flatPickrConfig: {
                    altInput: true,
                    altFormat: "F j, Y",
                    dateFormat: "Y-m-d",
                    locale: {
                        firstDayOfWeek: 1
                    },
                    weekNumbers: true,
                },
```

I want to be able to also set the locale (e.g. Hindi) but always force the firstDayOfWeek to be 1 (monday) no matter the locale.

I can't see an obvious way to do this - any tips?

**Comment by ankurk91** [comment]
What is the actual issue?

* You dont know how to pass this config to vue component.
* You know how to pass config but the configs are not working.
* You want to change configs dynamically.

Please elaborate

**Comment by ankurk91** [comment]
`firstDayOfWeek` is the part of locate.
https://github.com/flatpickr/flatpickr/blob/91756bbd5a481dca4746af85e5679cd1b8a7b05d/src/l10n/at.ts#L57

You can import any locate you want.
```
import {Hindi as HindiLocale} from 'flatpickr/dist/l10n/hi';
HindiLocale.firstDayOfWeek = 2
```
Then pass this in configs
```
{
locale: HindiLocale,
}
```
Basically we are just manipulating the js object.

**Comment by ankurk91** [comment]
You can also set locale globally for all flatpickr instances, see
https://github.com/ankurk91/vue-flatpickr-component/issues/49#issuecomment-352961928

**Comment by ankurk91** [comment]
Closing, i think i have answered your question.
Feel free to re-open

**Comment by scottybo** [comment]
That's brilliant, thank you - just in case anyone else comes across this issue, this is what I did in the end (I'm using Vuejs and Laravel Spark):

in app.js

```js
// Setup localisation / locale based on the page "lang" attribute
Vue.prototype.DocLang = document.documentElement.getAttribute('lang');
var flatPickrObject = null;

switch(Vue.prototype.DocLang) {
    case 'es':
        flatPickrObject = require('flatpickr/dist/l10n/es');
        Vue.prototype.flatPickrLocale = flatPickrObject.Spanish;
        break;
    case 'nl':
        flatPickrObject = require('flatpickr/dist/l10n/nl');
        Vue.prototype.flatPickrLocale = flatPickrObject.Dutch;
        break;
    default:
        flatPickrObject = require('flatpickr/dist/l10n/default');
        Vue.prototype.flatPickrLocale = flatPickrObject.english;
}

Vue.prototype.flatPickrLocale.firstDayOfWeek = 2;
```

And then in the FlatPickr config I have `locale: Vue.prototype.flatPickrLocale`
