### ISSUE TITLE
unpkg.com  Cannot find module

### ISSUE THREAD

**Issue by hemaka** [ankurk91/vue-flatpickr-component#91]
https://unpkg.com/vue-flatpickr-component@7

Cannot find module "dist/vue-flatpickr.min.js" in package vue-flatpickr-component@7.0.4

**Comment by jzatt** [comment]
This just "broke" my production site. Would like an update on this as well.

**Comment by ankurk91** [comment]
https://cdn.jsdelivr.net/npm/vue-flatpickr-component@7.0.4/dist/vue-flatpickr.min.js

This is an issue from unpkg itself.

Use this CDN, i will update the urls in readme soon.

**Comment by ankurk91** [comment]
Similar #84

**Comment by samimikk** [comment]
Hi, we cannot change our references (https://cdn.jsdelivr.net/npm/.... ) to the production, so we would need also working https://unpkg.com/vue-flatpickr-component@7.0.4. Thanks!

**Comment by ankurk91** [comment]
Okay, then you need to refer exact file
https://unpkg.com/vue-flatpickr-component@7.0.4/dist/vue-flatpickr.min.js

And it should eork

**Comment by samimikk** [comment]
Thanks for tip, unfortunatly we cannot change file paths for the production directly. Future production update we have dropped direct links, but at the moment we would need working  https://unpkg.com/vue-flatpickr-component@7.0.4 :(. I made ticket to unpgk.com.
