### ISSUE TITLE
Need to set Focus when invalid

### ISSUE THREAD

**Issue by Grandizer** [ankurk91/vue-flatpickr-component#92]
So I have a component that wraps the flatpickr and everything is working great.  Except when I validate the page/form and see that the required date is missing.  My code simple sets focus to that input/select whatever the "component" is.  It is not able to find the control in this instance.  Here is the guts of the flatpickr component.

```
<flat-pickr ref="thisInput"
  class="form-control"
  name="date"
  v-model="value"
  :config="config"
  :placeholder="placeholder"
  :class="{ required: isRequired, invalid: !isValid }"
  :required="isRequired">
</flat-pickr>
```

And once the validation fails, I do the following:

`this.$refs.thisInput.focus();`

That returns:

> Uncaught TypeError: this.$refs.thisInput.focus is not a function

I see that there is a nested `input`.  One that is `readonly` and one that is `hidden`.  At least for when showing the *Calendar*.  Seems like only one when just showing the *Time* picker.  Any suggestions?

**Comment by ankurk91** [comment]
You can not focus in flatickr input. 
If you try to, it will open the date picker interface.
You can see this behavior -
https://jsfiddle.net/63kzdwLx/1277/

If you still wants to do that, you can try this line in you code
```js
this.$refs.thisInput.$el.nextSibling.focus()
```

**Comment by Grandizer** [comment]
Thanks. Understood.  I will check it out on Monday.
