### ISSUE TITLE
minDate + vee-validate = infinite events

### ISSUE THREAD

**Issue by Dahje** [ankurk91/vue-flatpickr-component#93]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.0
* Vue.js version : 2.3.3
* Browser name and version : Chrome
* This package version : 7.0.4

**Current behavior**

When using the minDate config option with vee-validate flatpickr will infinitely send off input and on_change events.

**Expected behavior**

The minDate config option should be compatible with vue-flatpickr-component.

**Minimal reproduction of the problem with instructions**

I was able to consistently reproduce this by using the following:
```
<flat-pickr
  name="Selected Date"
  :class="{
    'input':true,
    'is-danger':errors.has('Selected Date'),
    'is-success':!errors.has('Selected Date')&&fields['Selected Date']&&fields['Selected Date'].valid
  }"
  v-validate="'required'"
  :data-vv-delay="50"
  :config="{
    minDate: 'today',
    dateFormat: 'M j, Y',
  }"
  :placeholder="Select a Date"
  v-model="SelectedDate"
/>
```
Note that the classes are from Bulma and in order for the page to actually load it was required that I used data-vv-delay.

P.S. Could you update the issue template with a link for jsfiddle that has the necessary modules pre-loaded?

**Comment by ankurk91** [comment]
Please don't use inline object in :config prop.
Post back here with status once you apply this fix.

**Comment by Dahje** [comment]
This does indeed fix the problem, I was stuck for a few minutes on how to create a dynamically changing minDate without it being inline, but a computed value ended up working nicely.

Also I did not have this issue with the config before I updated to version 7.0.4, but I was previously on version 3.1.3, so quite outdated. I'm assuming there was a major revision that prevented this from working?

**Comment by ankurk91** [comment]
This the vue.js limitation that it does not work well when there is a watcher on a prop and prop has inline object.
