### ISSUE TITLE
return date object not string

### ISSUE THREAD

**Issue by flamner** [ankurk91/vue-flatpickr-component#95]
How to config this plugin to return a date object instead string??

**Comment by ankurk91** [comment]
This vue component mimics the parent library (flatpickr).
Flatpickr does not always returns Date object, it may return array when mode is set to multiple.


If you wan to capture date object, you can listen to change event
```html
<flat-pickr 
v-model="form.date"
:config="configs.wrap"
@on-change="listenToOnChangeEvent">
</flat-pickr>
```
```js
listenToOnChangeEvent(selectedDates, dateStr, instance) {
        console.log('listen To OnChange Event', selectedDates);
},
```

**Comment by ankurk91** [comment]
I am closing this issue, just saw your thumbs up reaction. Feel free to ask more questions.
