### ISSUE TITLE
Using a list of custom objects as dates

### ISSUE THREAD

**Issue by mattkoch614** [ankurk91/vue-flatpickr-component#96]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.1
* Vue.js version : 2.5.16
* Browser name and version : Chrome 67
* This package version : 7.0.4

Is it possible to supply a list of dates to the flatpickr instance that are custom objects? I posted this question on the main flatpickr GitHub repo but realized that this may be the better place as I am relying on this library.

I have a list of JavaScript objects where retaining a reference to an ``id`` parameter is important. The list of dates is in this format:
```
[
    { id: '1', date: '2018-01-01' }, 
    { id: '2', date: '2018-01-02' }, 
    //
]
```

When using flatpickr with the ``multiple`` configuration option, I need a way to retain the identifiers when users select dates so I can submit them to the server.

**Comment by ankurk91** [comment]
Sorry but this vue component does not bring any new features to flatpickr.
AFAIK There is no such feature available.

I am trying to guess the feature you are building.

Lets says you application allows user to select the dates on which they will be on leave in future.
The flatpickr multiple mode will give multiple dates that you saves into a database table.
Each date goes in a new row, something like
```
id - user_id    - date
-------------------------------
1    - 1    - 2018-10-1
2    - 1    - 2018-10-1
2    - 1    - 2018-10-1
```
When user want to edit those dates, you pulls the records from this table and pass it to v-model.
FYI: You can pass array of dates to v-model when multiple mode is on.
Now user can un-select existing or select new dates.
Now you wants to track which dates has been removed and which has been added.
The easiest way to handle the update operation on database if that -
```sql
# delete all dates from database against this user
DELETE * from leaves WHERE user_id = 1

# insert the dates returned by v-model
INSERT INTO leaves ...
```

Hope it helps

**Comment by mattkoch614** [comment]
Hi,

Thanks for taking the time to answer and providing some example code.

My scenario is that I have user created events that have lists of dates associated with them. The dates here represent days on which other users can apply to the event. So this means that each event can have any number of days, with each date being stored with a unique ID number in the database (associated with the parent event via a foreign key.) My original thought was that I'd need these unique IDs to distinguish the event someone is applying to, but now I'm thinking I could just use the event ID itself and not worry about individual date identifiers. I could then verify the dates being passed in are in fact valid for the event being applied to on the back end.

I'll give this a try. Thanks again.
