### ISSUE TITLE
Supplying a date is not working

### ISSUE THREAD

**Issue by canyoudev** [ankurk91/vue-flatpickr-component#97]
I am trying to prepopulate date that I receive from API. I pass it with props. Data format is `2018-07-19T09:35:00.000Z` so it must work. But it doesn't work. 

```js
config: {
        defaultDate: this.value,
        enableTime: true,
        minDate: new Date().toISOString(),
        maxDate: addMonths(Date.now(), 1).toISOString(),
        time_24hr: true,
        locale: Russian
      }
```

**Comment by canyoudev** [comment]
I also tried this, but it doesn't work also

```html
<flat-pickr :value="value" @on-change="setDate" :config="config"></flat-pickr>
```

**Comment by canyoudev** [comment]
Feeling stupid. Found the issue, it's because I am setting `minDate` which is bigger then data that I receive from API. My bad!

**Comment by mtimofiiv** [comment]
Thanks for following up, you saved me some time debugging this exact issue!
