### ISSUE TITLE
Using Range with time enabled breaks after first usage.

### ISSUE THREAD

**Issue by JackSteel97** [ankurk91/vue-flatpickr-component#98]
**I'm submitting a ...** 

- [x] Bug report => search github for a similar issue or PR before submitting
- [ ] Feature request
- [ ] Other, please describe

**Tell about your platform**
* flatPickr version : 4.5.1
* Vue.js version : 2.x
* Browser name and version : Chrome 67.0.3396.99
* This package version : 7.0.4

**Current behavior**
When using range with time enabled. After setting the v-model to anything other than null. The start datetime of the range defaults to midnight on the selected date and cannot be changed.

**Expected behavior**
Match original flatpickr behaviour; time of start date in a range can be changed by setting the range again.

**Minimal reproduction of the problem with instructions**

Steps to reproduce:
Using https://jsfiddle.net/jsteel97/x3yp2hjk/
1. Use flatpickr to select a date range with times.
2. Try and change the date range without refreshing the page. 
3. The start dates time component will default to midnight and cannot be changed.

**Comment by ankurk91** [comment]
@JackSteel97 
I can reproduce the issue on plain js version of flatpickr, see
https://jsfiddle.net/a378L9fj/10/

I dont think this is related to this vue component.

**Comment by JackSteel97** [comment]
Weird, I did check plain flatpickr and couldn't reproduce it before. Thanks, I'll raise this in the flatpickr repo.
