### ISSUE TITLE
:disabled attribute not working

### ISSUE THREAD

**Issue by francsiswanto** [ankurk91/vue-flatpickr-component#99]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.4.4
* Vue.js version : 2.5.2
* Browser name and version : Firefox 61
* This package version : 7.0.1

**Current behavior**
when I write script like this:
`<flat-pickr v-model="item.DEPODT" input-class="date-input" :config="configflp" :disabled="!editmode"></flat-pickr>`

and config:
```
configflp: {
	altInputClass: 'p-0 text-center ',
},
```

then I change value of **editmode** to true, result: the component is still disabled

**Expected behavior**
I expect the component respect disabled attribute

Thank you very much.

**Comment by ankurk91** [comment]
You should pass `allowInput` in config object.
Read more here - https://flatpickr.js.org/options/

**Comment by francsiswanto** [comment]
Sorry if I'm not complete send my config, this is my configuration complete with setDefault:
```
flatpickr.setDefaults(
	{
		// default options here
		altInput: true,
		altFormat: 'd-m-Y',
		dateFormat: 'Y-m-d',
		allowInput: true,
	}
)

and in my page:
configflp: {
	altInputClass: 'p-0 text-center ',
}

```
and the result still not working.
Thanks

**Comment by ankurk91** [comment]
Flatpickr creates two input fields (one is hidden) when we pass `altInput`` to `true`.
![screen shot 2018-07-27 at 12 30 46 pm](https://user-images.githubusercontent.com/6111524/43306573-40931c82-9199-11e8-9aa1-dc6d69fbb1f4.jpg)

Vue component can only pass attributes to initial input field but flatpickr makes it hidden.

**Comment by francsiswanto** [comment]
So I have to change `altInput: false` to make it happen. 
Alright then, thanks for your help

**Comment by dragoono** [comment]
Is there any new solution for this ? In my case I have to use Altinput cause different dateformats

**Comment by ankurk91** [comment]
@dragoono
8.1.0 was released to fix this issue. What is your version ?

**Comment by dragoono** [comment]
In my case I need to use the altInput Option because I need to display different Date Formats.
